### ISSUE TITLE
Screenshot capturing outside display bounds

### ISSUE THREAD

**Issue by monkeybird** [gen2brain/raylib-go#1]
The function `TakeScreenshot` at line 2174 in core.c, captures screen shots of a fixed size, even if the window is partially off screen. The result is that the off screen part of the resulting screen shot is completely black. For examples, see these screen shots I made using the current code:

* [image 1](https://cloud.githubusercontent.com/assets/19928139/22405575/3c78918c-e645-11e6-9ae7-32569a13213f.png):  Here the window is entirely in view. The screen shot looks as intended.
* [image 2](https://cloud.githubusercontent.com/assets/19928139/22405576/3c793e5c-e645-11e6-9e93-91d601ee2e98.png):  Here the window is partially off screen to the right.
* [image 3](https://cloud.githubusercontent.com/assets/19928139/22405574/3c75dad2-e645-11e6-886d-a20a8a6f2034.png):   Here the window is partially off screen at the bottom.

```c
 unsigned char *imgData = rlglReadScreenPixels(renderWidth, renderHeight)
```

This code can be fixed by clamping `renderWidth` and `renderHeight` to the size of the window actually visible on screen. This will result in smaller screen shot files for these cases.

**Note**: I am aware that this issue applies to the C code of raylib and should therefore probably be reported upstream. I am reporting it here as well, because the raylib C sources are included in this repo directly.

**Comment by monkeybird** [comment]
For reference, I submitted the same report upstream: https://github.com/raysan5/raylib/issues/221

**Comment by monkeybird** [comment]
The issue has been addressed upstream in commit https://github.com/raysan5/raylib/commit/a08117155da1a0a439239ad8801a58b85f528014

**Comment by gen2brain** [comment]
Thanks. I will close this issue when I update C source.
