### ISSUE TITLE
Unable to cross-compile

### ISSUE THREAD

**Issue by kaihoukyoku** [gen2brain/raylib-go#10]
On go1.8.3 windows/amd64, using git bash, I attempted to build a raylib game with
`GOOS=linux go build`
and got
`# github.com/gen2brain/raylib-go/raylib
E:\go\src\github.com\gen2brain\raylib-go\raylib\rres.go:145: undefined: OpenAsset`

I tried going to the raylib-go folder and cross-compiling it alone and got the same error
Trying any form of cross-compilation (changing only $GOOS, $GOARCH or both) gets me the same error

`cat rres.go | grep` shows that there was a single call to OpenAsset on rres.go
It seems OpenAsset is defined on platform_*.go, in this case I suppose it should be using platform_desktop.go, which begins with the line `// +build !android,!arm`

I'm not sure how build constraints work, so I'm having trouble making sense of this, but it seems clear that the cross-compiling process is interfering with this somehow
Any help would be appreciated

**Comment by gen2brain** [comment]
Until I check this you can just remove rres.go file. It is still a WIP.

**Comment by gen2brain** [comment]
Ok, just checked, OpenAsset should be defined. Not sure about that windows bash thing, but to cross compile something that doesn't use pure Go, but uses cgo you must prepare your Go installation before cross compiling (recompile for every platform you want with correct CC, CC_FOR_TARGET). 

 Example for Android is here https://github.com/gen2brain/raylib-go/blob/master/examples/android/example/bootstrap.sh , and for rpi is here https://github.com/gen2brain/raylib-go/blob/master/examples/rpi/basic_window/bootstrap.sh . 

For cross compiling for Windows in Linux I use something like this:
GOROOT_BOOTSTRAP=${BUILD_DIR}/bootstrap/go CC_FOR_TARGET=i686-w64-mingw32-gcc GOOS=windows GOARCH=386 CGO_ENABLED=1 ./make.bash --no-clean

**Comment by kaihoukyoku** [comment]
> Not sure about that windows bash thing

It's basically just cygwin, I don't think it matters much

> but to cross compile something that doesn't use pure Go, but uses cgo you must prepare your Go installation before cross compiling

I see, it is a cgo thing then. I think I can figure it out from these examples, thanks for the help
