### ISSUE TITLE
New version of raylib released

### ISSUE THREAD

**Issue by ElhamAryanpur** [gen2brain/raylib-go#106]
New version of raylib released just recent, any plan to update?

**Comment by gen2brain** [comment]
Sure, the plan is when I find time to do that unless someone helps before that.

**Comment by raysan5** [comment]
I'm also considering releasing raylib 3.1 before completing all the points in the 3.1 roadmap...

**Comment by ElhamAryanpur** [comment]
> I'm also considering releasing raylib 3.1 before completing all the points in the 3.1 roadmap...

is there any ETA? I am so excited for it! P.S. i'll see how can I help this repo

**Comment by gen2brain** [comment]
@ElhamAryanpur raylib-go is updated to version 3.1-dev.
