### ISSUE TITLE
Install on non-RPI ARM device?

### ISSUE THREAD

**Issue by theLMGN** [gen2brain/raylib-go#113]
Hi, I'm trying to install this on an ARM SBC (not a RPI) however I'm getting an issue about the bcm_host library missing, however I'm not using a Raspberry Pi, so I don't need (or want) the Raspberry Pi GPU drivers.

**Comment by gen2brain** [comment]
As far as I know, Raylib only has support for RPi in ES 2.0 in native mode, and can support X11 in OpenGL 2.1, are you planning to use X11? Probably something can be done with tags to support such cases, if at all supported by Raylib. If it works in C then something can be done.

**Comment by gen2brain** [comment]
This will be possible soon, see PLATFORM_DRM https://github.com/raysan5/raylib/pull/1388 .

**Comment by kernelkinetic** [comment]
@theLMGN For a first try until https://github.com/raysan5/raylib/pull/1388 is merged you can try https://github.com/kernelkinetic/raylib/tree/platform-drm which is the PR that will get merged with changes.

**Comment by gen2brain** [comment]
PLATFORM_DRM is implemented, and now there are tags `rpi` and `drm`, arm is not related/affected.
