### ISSUE TITLE
Any chance to add Load*FromMemory? 

### ISSUE THREAD

**Issue by dzonerzy** [gen2brain/raylib-go#114]
Any chance to add the the new API like Load*FromMemory?

**Comment by gen2brain** [comment]
`LoadImagePro` was recently removed from raylib, it must have an implementation in C code before it can be used here.
You can use `NewImageFromImage`, which returns raylib Image from Go image.Image, so just create Go image however you want, and load it with this function.

**Comment by gen2brain** [comment]
Added in https://github.com/gen2brain/raylib-go/commit/3908769a219a050c2b09272d95f26fc1eb030f01.
