### ISSUE TITLE
Cant install raylib-go

### ISSUE THREAD

**Issue by notmax6677** [gen2brain/raylib-go#116]
when i run "go get github.com/gen2brain/raylib-go/raylib"
i end up getting a long error after a few seconds:

go: downloading github.com/gen2brain/raylib-go v0.0.0-20200905153824-5b0944b5567a
go get github.com/gen2brain/raylib-go/raylib: github.com/gen2brain/raylib-go@v0.0.0-20200905153824-5b0944b5567a: Get "https://storage.googleapis.com/proxy-golang-org-prod/1a46cdf2c5e2701b-github.com:gen2brain:raylib-go-v0.0.0-20200905153824-5b0944b5567a.zip?Expires=1603378981&GoogleAccessId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=fOhMEx046%2FyPXvuag9e6OgP4ujUXKapY%2BvSfWGhqlalMOS6A6A9kKU6vRc%2BVkSawAeUTe54qrbw%2BfsCBhmZCUmgqScbFvOLdfRicwBMcp00ho7Zp5MjW7voOOkePCJcvqm6dT1a%2Bk%2FUb6AEoBCfIkUOaNTGssVJND9h%2F5Y%2BOm2tkWa29qduwZSJKWBYooa1SrKJQDPjjQMm0J5RQCQ7ghn3OCwMMPOoi8E229xQFDi2kqMpcUjcOEiSbHZqw0kb4hgw4OW8G2JgIg9bgSb8Bfqd%2BhsGcxclK1fz%2B3ud4krVO0bbljxuIOkK7Kd0qWpxRkqpyYkM%2BX9uvBc2J4e5vgw%3D%3D": net/http: TLS handshake timeout

**Comment by gen2brain** [comment]
Not related to raylib-go, but looks related to the Go modules proxy you are using. Try to change GOPROXY, or disable it.

**Comment by W-Axis1** [comment]
> 
> 
> Not related to raylib-go, but looks related to the Go modules proxy you are using. Try to change GOPROXY, or disable it.

how

**Comment by gen2brain** [comment]
E.g. `GOPROXY=https://proxy.golang.org` or set it to off, or direct. It is all in a docs https://tip.golang.org/cmd/go/#hdr-Module_downloading_and_verification.
