### ISSUE TITLE
Compile For Android ( lates ndk version doesn't support androdeabi-gcc )

### ISSUE THREAD

**Issue by raifpy** [gen2brain/raylib-go#117]
https://github.com/android/ndk/issues/1375

So, how can we compile raylib-go for Android?
I can install ndk17..

**Comment by gen2brain** [comment]
https://github.com/gen2brain/raylib-go/tree/master/examples/others/android/example

**Comment by raifpy** [comment]
export PATH=${ANDROID_NDK_HOME}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:${PATH}

in NDK r21d's bin there is no "arm-linux-androideabi-gcc"
so when i try build (like example)
exec: command not found: arm-linux-androideabi-gcc*

**Comment by raifpy** [comment]
pwd 
/home/raif/Android/android-ndk-r21d/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin

ls
arm-linux-androideabi-addr2line  arm-linux-androideabi-dwp      arm-linux-androideabi-ld.bfd   arm-linux-androideabi-objdump  arm-linux-androideabi-strings
arm-linux-androideabi-ar         arm-linux-androideabi-elfedit  arm-linux-androideabi-ld.gold  arm-linux-androideabi-ranlib   arm-linux-androideabi-strip
arm-linux-androideabi-as         arm-linux-androideabi-gprof    arm-linux-androideabi-nm       arm-linux-androideabi-readelf
arm-linux-androideabi-c++filt    arm-linux-androideabi-ld       arm-linux-androideabi-objcopy  arm-linux-androideabi-size

There is no gcc here..

**Comment by gen2brain** [comment]
But you have clang? From some version they removed gcc.

**Comment by gen2brain** [comment]
Android README is updated, I will try later with the latest NDK and update accordingly.
