### ISSUE TITLE
KeyLeftSuper constant is incorrect

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#118]
[It's currently set to the keycode 347, which is the same as KeyRightSuper](https://github.com/gen2brain/raylib-go/blob/master/raylib/raylib.go#L204) - seems like it should be 343.

**Comment by gen2brain** [comment]
Thanks, changed.

**Comment by SolarLune** [comment]
Perfect. Thanks a lot for the fix!
