### ISSUE TITLE
ERROR: MAX_QUADS_BATCH overflow ?

### ISSUE THREAD

**Issue by jhautefeuille** [gen2brain/raylib-go#12]
Hello,
I'm writing here because I don't understand why I can't post anything on your forum project page (Firefox 55.0.2).

I've made a simple test on (Ubuntu 16.04, golang 1.8, raylib 1.7).

```
package main

import (
	"github.com/gen2brain/raylib-go/raylib"
	"log"
)

func main() {
	screenWidth := int32(800)
	screenHeight := int32(450)

	cpos := make([]raylib.Vector2, 0)

	raylib.InitWindow(screenWidth, screenHeight, "RayMantha")

	raylib.SetTargetFPS(60)

	for !raylib.WindowShouldClose() {
		cursorPosition := raylib.GetMousePosition()
		log.Println(cursorPosition)

		raylib.BeginDrawing()
		raylib.ClearBackground(raylib.RayWhite)

		if raylib.IsMouseButtonDown(raylib.MouseLeftButton) {
			cpos = append(cpos, cursorPosition)
		}
		raylib.DrawText("Test", 30, 30, 30, raylib.DarkBlue)
		raylib.DrawCircleV(cursorPosition, 1, raylib.DarkGray)
		log.Println(cpos)

		for _, elem := range cpos {
			raylib.DrawCircleV(elem, 5, raylib.DarkGray)
		}
		log.Println(len(cpos))

		raylib.EndDrawing()
	}

	raylib.CloseWindow()
}
```

I've got ERROR: MAX_QUADS_BATCH overflow error with 453 circles ? How to prevent this ?

thank you for your help.

**Comment by raysan5** [comment]
Hi @jhautefeuille, raylib uses internally a batch system to store vertex data before launching a draw call, those internal buffers are limited to a MAX size. Every frame, batched data is send to GPU and I calculated that MAX size for a good performance ratio... unfortunately, circles require lots of quads and that limit is reached quite early.

**Solution 01**: Just increase MAX_QUADS_BATCH size limit in [raylib base code](https://github.com/gen2brain/raylib-go/blob/master/raylib/rlgl.h#L111).

**Solution 02**: Call `End2dMode()` in the middle of drawing, it forces a draw call launch and reset buffers. It's a bit dirty solution...

**Solution 03**: Just wait a bit (couple of weeks) for raylib 1.8, just solved this issue some time ago and it will be available on next raylib release.

**Comment by jhautefeuille** [comment]
Thank you for your replies, I will use image sprite instead.
I'm going to wait next release of RayLib.
Thank you very much for Raylib ! I like it.

J.H
