### ISSUE TITLE
Windows app never stops

### ISSUE THREAD

**Issue by bombjackm** [gen2brain/raylib-go#120]
Hi,

I tried the simple example on the main page and on Windows 10 the application never stops.
The texture are unloaded but I never get back to the command prompt.
I tried using LockOSThread but it changes nothing.
It works fine on linux.

The rl.CloseWindow() never get back. When I remove it, It works.
Is it intended?

Marc

**Comment by gen2brain** [comment]
Try with the new release and reopen if you still have issues. Nobody complained about that, of course, it is not intended.
