### ISSUE TITLE
Calling FontLoadEx() with different sizes causes segfault

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#121]
Hey, there. I'm trying to load different fonts at runtime for my project, MasterPlan, with different sizes. However, it seems like the `rl.LoadFontEx()` function causes a crash or freeze given enough attempts if the font size changes. Sometimes it crashes after just a few iterations, sometimes it takes more. I've noted that it doesn't happen with repeated `rl.LoadFont()` calls, and it doesn't happen with `rl.LoadFontEx()` if the size is constant. The crash only happens if the size changes.

Here's my simple example program that automatically causes the crash on my system - replace the font name, "excel.ttf", with a font in the same directory to reproduce.

```go

package main

import (
	"fmt"

	rl "github.com/gen2brain/raylib-go/raylib"
)

func main() {

	rl.InitWindow(320, 240, "font load test")

	font := rl.LoadFontEx("excel.ttf", 32, nil, 64)

	fontSizes := []int32{}

	for i := 32; i < 128; i++ {
		fontSizes = append(fontSizes, int32(i))
	}

	fontSizeIndex := 0

	for !rl.WindowShouldClose() {

		font = rl.LoadFontEx("excel.ttf", fontSizes[fontSizeIndex], nil, 256)
		// font = rl.LoadFontEx("pickcell_solarlune.ttf", fontSizes[fontSizeIndex], nil, 256)
		// font = rl.LoadFontEx("Aller_Rg.ttf", fontSizes[fontSizeIndex], nil, 256)

		rl.BeginDrawing()

		rl.ClearBackground(rl.White)

		rl.DrawTextEx(font, "Test draw", rl.Vector2{160, 120}, float32(fontSizes[fontSizeIndex]), 1, rl.Black)

		rl.EndDrawing()

		fontSizeIndex++
		if fontSizeIndex > len(fontSizes)-1 {
			fontSizeIndex = 0
		}

		fmt.Println("Font size: ", fontSizes[fontSizeIndex])

		rl.UnloadFont(font)

	}

}


```

The output from the terminal seems to indicate that it's a problem in raylib's C sources:

```

[signal SIGSEGV: segmentation violation code=0x1 addr=0xfffffffffdaab9a8 pc=0x7fde7342f9b0]

runtime stack:
runtime.throw(0x5ba925, 0x2a)
        /usr/lib/go-1.14/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
        /usr/lib/go-1.14/src/runtime/signal_unix.go:679 +0x46a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4d94e0, 0xc000055e10, 0x59cc00)
        /usr/lib/go-1.14/src/runtime/cgocall.go:133 +0x5b fp=0xc000055de0 sp=0xc000055da8 pc=0x42cd7b
github.com/gen2brain/raylib-go/raylib._Cfunc_LoadFontEx(0x16d8600, 0xc000000063, 0x0, 0x200000100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:3846 +0x57 fp=0xc000055e10 sp=0xc000055de0 pc=0x4be687
github.com/gen2brain/raylib-go/raylib.LoadFontEx(0x5b4ac5, 0x9, 0x100000063, 0x0, 0x100, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/solarlune/go/pkg/mod/github.com/gen2brain/raylib-go@v0.0.0-20201123133337-d123299701ae/raylib/text.go:43 +0xd2 fp=0xc000055eb8 sp=0xc000055e10 pc=0x4bebe2
main.main()
        /home/solarlune/Documents/Projects/Go/rlfontloadtest/main.go:26 +0x230 fp=0xc000055f88 sp=0xc000055eb8 pc=0x4bfe60
runtime.main()
        /usr/lib/go-1.14/src/runtime/proc.go:203 +0x1fa fp=0xc000055fe0 sp=0xc000055f88 pc=0x45b9ba
runtime.goexit()
        /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000055fe8 sp=0xc000055fe0 pc=0x4862b1
exit status 2

```

Any ideas / can anybody else reproduce?

**Comment by SolarLune** [comment]
Interestingly, it seems like it might have something to do with the font itself - the problem doesn't appear for one of my test fonts, but does for two others (one that's my own, [Excel](https://fontstruct.com/fontstructions/show/1748204/excel-4), as well as another one, [Aller Regular](https://fonts.adobe.com/fonts/aller)).

**Comment by SolarLune** [comment]
Further investigations:

On my machine, the following trimmed-down code works:

```go

package main

import (
	"runtime"

	rl "github.com/gen2brain/raylib-go/raylib"
)

func main() {

	runtime.LockOSThread()

	rl.InitWindow(320, 240, "font load test")

	font := rl.LoadFontEx("excel.ttf", 100, nil, 256)

	rl.SetTargetFPS(10)

	for !rl.WindowShouldClose() {

		// font := rl.LoadFontEx("excel.ttf", 100, nil, 256)

		rl.BeginDrawing()

		rl.ClearBackground(rl.White)

		rl.DrawTextEx(font, "Test draw", rl.Vector2{160, 120}, 100, 1, rl.Black)

		rl.EndDrawing()

	}

}

```

But if I replace the first loadFont command with the second one in the window closing loop, it crashes. Strange; it shouldn't be a texture size constraint, as I'm working with an NVIDIA GeForce RTX 2060 - maximum texture size should be 8192x8192. Texture size when it crashes is reported by raylib as being 1024x1024.

**Comment by SolarLune** [comment]
Pinging @raysan5, because [after testing with C with another user](https://discord.com/channels/426912293134270465/427518168995725317/789248416089636894), it seems like this might be a problem in raylib's core.

**Comment by raysan5** [comment]
Hi @SolarLune! yeah, I saw the comments on Discord... it's weird, it could be driver-gpu related... I'll review it.

**Comment by SolarLune** [comment]
Hmm, I see. Thanks for responding! It's a tad hard to peg down exactly what's going on; if you can reproduce it (or not) on your end with vanilla raylib, that would be very helpful.

**Comment by gen2brain** [comment]
@SolarLune there is a new release, please check it.

**Comment by SolarLune** [comment]
Hello, on first inspection, this doesn't _seem_ to be an issue anymore. I'll close it for now. 

Thanks!

**Comment by shiMusa** [comment]
I'm still running into that issue... As soon as I call a second `LoadFontEx` with a different size on the same font, the program crashes.

**Comment by lpisanu1908** [comment]
Same for me. Second call to LoadFontEx crashes raylib

**Comment by gen2brain** [comment]
@lpisanu1908 Can you send a small example that crashes for you, if possible with the font you are using?

**Comment by lpisanu1908** [comment]
Hello,

I am use nodejs

I load the font outside the main loop

  fontSmall = r.LoadFontEx("./Fredoka.ttf", 12, 1, 127);
  fontNormal = r.LoadFontEx("./Fredoka.ttf", 20, 32, 127);

The font comes from Google fonts, downloaded directly from their page

Thx

**Comment by lpisanu1908** [comment]
One more thing I noticed: once crashed, any subsequent call to LoadFontEx fails with segmentation fault.
Look like it "leaves some dirt behind"...

**Comment by lpisanu1908** [comment]
Solved, changed font, it loads correctly.
I forgot: working on a rpi3 armbian

**Comment by mrAndersen** [comment]
I have the same problem loading 95px font in RTX 3070 ...
