### ISSUE TITLE
it's too cool

### ISSUE THREAD

**Issue by AJDevelopment-315** [gen2brain/raylib-go#124]
it's too cool I've been using it for 5 hours and I don't think I'm going to stop

**Comment by kfsone** [comment]
+9001 for being able to install and use the library on windows and linux out of the box without having to stab myself in the eyes, sell my arms, or sacrifice a chicken.

I've looked at dozens of alternatives this last 4 days, and raylib seems to be the go equivalent of pygame.

Rockstar!

**Comment by gen2brain** [comment]
Thanks! The new release is planned, there is a new platform (drm), there are new methods to read files from memory, etc. I am busy currently and had some family issues, but it is on my to-do list.

**Comment by gen2brain** [comment]
The source is updated for the latest (dev) release, you can check it.
