### ISSUE TITLE
App crashes when loading texture

### ISSUE THREAD

**Issue by DaruBrub** [gen2brain/raylib-go#125]
Hello!

I wanted to load some textures but it crashes when a texture is loaded.

Code:

```go
package main

import "github.com/gen2brain/raylib-go/raylib"

import "./consts"

func main() {
	// Initalize
	rl.InitWindow(consts.ScreenWidth,consts.ScreenHeight,"Flappy Bird")
	rl.SetTargetFPS(60)

	background := rl.LoadTexture("res/sprites/bg.png")

	// Game Logic
	for !rl.WindowShouldClose() {
		rl.BeginDrawing()
		rl.ClearBackground(rl.White)

		rl.DrawTexture(background,0,0,rl.White)

		rl.EndDrawing()
	}

	// Close
	rl.UnloadTexture(background)

	rl.CloseWindow()
}
```

**Comment by HeCorr** [comment]
I'm having the same issue, app is crashing with no errors. Why did you close the issue? Did you manage to fix it?

![image](https://user-images.githubusercontent.com/75134774/144668608-169c6b92-135c-40b0-a177-c725a5fb0269.png)

**Comment by HeCorr** [comment]
@gen2brain Should I create a new issue or is there something simple I'm overlooking?
