### ISSUE TITLE
The demo 'obj_loading' have bug,obj file can't be load success

### ISSUE THREAD

**Issue by rhettli** [gen2brain/raylib-go#130]
![Screenshot 2021-03-06 175541](https://user-images.githubusercontent.com/26317003/110202701-68547080-7ea5-11eb-866f-0c8aa86f4430.png)

**Comment by rhettli** [comment]
it be tested at master branch,i test all demo ,just got one error.

**Comment by rhettli** [comment]
And by the way,raylib-go not support write unicode string, why?

**Comment by gen2brain** [comment]
This issue is a duplicate of #72

**Comment by gen2brain** [comment]
This is now fixed. Just use `rl.SetMaterialTexture` like in examples.
