### ISSUE TITLE
Textures with alpha channel not showing through in 3D mode

### ISSUE THREAD

**Issue by harbdog** [gen2brain/raylib-go#132]
Using the version currently at master (`github.com/gen2brain/raylib-go v0.0.0-20210227124741-9d258bad6516`), the billboard example is showing white around the outside of the image, rather than using its alpha channel to see the grid behind the image in the appropriate places.

![billboard_alpha_problem](https://user-images.githubusercontent.com/1300522/115126544-d2c8f800-9f9d-11eb-9d49-3619c3907493.png)

The raylib.com example shows it correctly behind the billboard:
https://www.raylib.com/examples/web/models/loader.html?name=models_billboard
![billboard_alpha_raylib com](https://user-images.githubusercontent.com/1300522/115126596-2fc4ae00-9f9e-11eb-8803-b53c1a401fa7.png)

**Comment by gen2brain** [comment]
Fixed in https://github.com/gen2brain/raylib-go/commit/b9e2059e57f5f045e5adf8014fb19bea8c1b4d3e, order is important.

**Comment by harbdog** [comment]
@gen2brain confirmed works, thanks!
