### ISSUE TITLE
Update raylib to 3.7

### ISSUE THREAD

**Issue by hismailbulut** [gen2brain/raylib-go#133]
There is a lot of changes and fixes since 3.0. Updating raylib version is required.

**Comment by makeworld-the-better-one** [comment]
https://github.com/chunqian/go-raylib supports raylib 3.5 and will be upgrading to 3.7. Not sure if it's helpful to gen2brain or not, but it's nice as a user.

**Comment by hismailbulut** [comment]
Thank you. I will try.

**Comment by gen2brain** [comment]
Updated to 3.8-dev.

**Comment by makeworld-the-better-one** [comment]
@gen2brain why not 3.7? 3.8-dev is unstable

**Comment by gen2brain** [comment]
This repo mostly followed the dev version. When 3.8 is released I can update more easily. I checked commits and issues, nothing is unstable currently.

**Comment by makeworld-the-better-one** [comment]
Okay, thanks. It'd be more helpful to have the latest tagged raylib version on the `master` or `main` branch, and then the dev version on some other branch like `dev`. That way it's obvious what version of raylib is being used and what features are available etc.

**Comment by gen2brain** [comment]
Yes, and that will require more time to manage all that. It is painful enough to follow all renames/additions/removals.
