### ISSUE TITLE
Compiling on windows & linux throws error

### ISSUE THREAD

**Issue by nonunknown** [gen2brain/raylib-go#134]
Here when compiling on windows:
![image](https://user-images.githubusercontent.com/58845030/119389595-3aabe600-bca2-11eb-8907-61e163478ebc.png)

the same is true for linux, but instead the file is cgo_linux.go

**Comment by gen2brain** [comment]
That file is part of the repo, so something weird on your end. I just checked in Linux with both the new modules method and plain go build and everything just works. How do you install, do you use Go modules (go mod init) or just plain go build?

**Comment by nonunknown** [comment]
go mod init

**Comment by gen2brain** [comment]
There is a new release you can try, but that looks like you have some misconfiguration, nobody had similar issues. Reopen if you still have issues with the new release.

**Comment by nonunknown** [comment]
@gen2brain this can mark as solved, i used this to solve the problem: https://github.com/nomad-software/vend

it import all necessary files from external to local vendor folder!

**Comment by gen2brain** [comment]
Ok, I see now what was the problem, thanks.
