### ISSUE TITLE
Places where slices are expected are pointers to underlying value instead (Model, Font)

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#136]
Hello, sorry for the confusing / generic title.

It seems like in a few places where, say, the C sources expect a pointer to the start of an array of elements, it's the exact same in Go. It feels like it should be expecting a pointer to a slice of the underlying elements instead.

For example:

- `rl.LoadFontEx()` still takes a pointer to an `int32` for the font characters to load, when it should presumably be a slice of runes.
- `rl.Model.Materials` is a pointer to a singular `rl.Material`, when it probably should be a slice of the Materials in use on the Model. Same for `rl.Model.Meshes`, `rl.Model.Bones`, and `rl.Model.Materials.Maps`.

**Comment by gen2brain** [comment]
`rl.Model.Materials` I am not touching that again, it is what it is, it caused a lot of problems before. LoadFontEx can be modified, PR is welcomed.
