### ISSUE TITLE
cannot use FlagWindowAlwaysRun as byte value

### ISSUE THREAD

**Issue by Afflictus** [gen2brain/raylib-go#137]
const rl.FlagWindowAlwaysRun untyped int = 256

cannot use rl.FlagWindowAlwaysRun (untyped int constant 256) as byte value in argument to rl.SetWindowState (overflows)

![Code_2Es83t34pp](https://user-images.githubusercontent.com/20441564/121769796-a92fe580-cb76-11eb-9cc2-3dba868cefec.png)

**Comment by gen2brain** [comment]
Fixed in https://github.com/gen2brain/raylib-go/commit/8ff192f923a50fe2a31393ec727fdf58e46ce82c.
