### ISSUE TITLE
Windows Installation Instructions?

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#14]
Hey, there. 

I'm trying to build my test project on Windows for assistance with fixing #13, and I'm having trouble getting Go and raylib-go up and running with MSYS2. I have MSYS2 downloaded and installed, but the instructions for raylib-go don't really mention too much more about how to install raylib-go. For example, I ran the line for Pacman, but `go` wouldn't run in the MSYS2 terminal until I added GOROOT and GOPATH environment variables and tweaked the batch file to inherit the Windows PATH settings. Currently, after calling `go get -v ...` for each dependency of my number, I call `go build` in the directory of my project and get this:

```
$ go build
# _/C_/Users/SolarLuneUser/go/src/SingleScreen
github.com/gen2brain/raylib-go/raylib(.text): strdup: not defined
github.com/gen2brain/raylib-go/raylib(.text): strdup: not defined
github.com/gen2brain/raylib-go/raylib(.text): strdup: not defined
github.com/gen2brain/raylib-go/raylib(.text): strdup: not defined
github.com/gen2brain/raylib-go/raylib(.text): undefined: strdup
github.com/gen2brain/raylib-go/raylib(.text): undefined: strdup
github.com/gen2brain/raylib-go/raylib(.text): undefined: strdup
github.com/gen2brain/raylib-go/raylib(.text): undefined: strdup
```

as a result. It's also a bit surprising that the instructions state to install Go itself instead of just the prerequisites for an existing Go install. Am I supposed to run `go` through the MSYS2 command prompt to build my project? My `GOPATH` is `C:\msys64\mingw64` and my `GOROOT` is `C:\msys64\mingw64\lib\go`. Is that correct?

Thanks for any help anyone can give. I'm running Windows 10 64-bit, by the way.

**Comment by gen2brain** [comment]
Hi,

Instructions for Windows are for MSYS2, but you don't have to use it if you already have Go installed, git in your PATH, and everything else Go needs under Windows. You will also have to install manually OpenAL (not sure how that should be done and where to copy it) so with pacman/MSYS2 at least some generic instructions are possible, try to build it in MSYS2 shell.  raylib-go uses CGO so you will need C compiler, and will also need CGO_ENABLED=1 if it is not set.

I usually just cross compile  .exe on Linux with i686-w64-mingw32 as that is a lot easier for me to do.

**Comment by gen2brain** [comment]
Added info to README that MSYS2 shell should be used. If you or anyone else can write some generic instructions for Go without MSYS2 please open another issue.
