### ISSUE TITLE
Add go module support

### ISSUE THREAD

**Issue by Jack-Ji** [gen2brain/raylib-go#141]
Hi @gen2brain , are there any particular reasons you didn't add go.mod/go.sum into framework?
Cause everytime I want to modify/test code, I have to add them by myself.

**Comment by gen2brain** [comment]
Sure, I will add support. Is there anything that doesn't work currently? I tried to build an example with the module and everything worked, btw there are no 3rd party dependencies

**Comment by Jack-Ji** [comment]
Most stuff works fine, except go tool needs go.mod file in order to test/run examples.
