### ISSUE TITLE
Is it possible to embed files to make distribution easier?

### ISSUE THREAD

**Issue by scarycoffee** [gen2brain/raylib-go#143]
You can [embed](https://pkg.go.dev/embed) files with ebiten, I'm wondering how easy it would be to implement this within raylib-go and if it's in the roadmap at all?

**Comment by gen2brain** [comment]
What needs to be specially implemented, you can just use it? LoadFromMemory functions are added, not sure though if they cover everything. There is also https://github.com/gen2brain/raylib-go/tree/master/rres, but it needs more types added.

**Comment by scarycoffee** [comment]
I was just thinking about convenience, but if a tool already exists then it doesn't matter at all. Thanks!
