### ISSUE TITLE
Remove `rl.Color`

### ISSUE THREAD

**Issue by gravestench** [gen2brain/raylib-go#144]
I would argue that you _should use `color.Color` or `color.RGBA` instead of defining a new `Color` type inside of `raylib-go`_.

**Comment by gen2brain** [comment]
If someone is willing to work on this and all necessary conversions I will happily merge it. I guess `color.RGBA` is more suitable.

**Comment by gen2brain** [comment]
Fixed in https://github.com/gen2brain/raylib-go/commit/29ba3cc50849d5fd09af003e40bb6870974dab8e. `Color` is now just an alias to `image.RGBA`, to not break any code, will be removed later on.
