### ISSUE TITLE
gui font missing (raygui)

### ISSUE THREAD

**Issue by gatoplusplus** [gen2brain/raylib-go#150]
I've noticed that the raygui bindings are slightly lacking and have some important features missing such as loading fonts. Also I'm not too sure if this was just an issue on my end but only .style files loaded into the global gui style and not rgs files which both of these issues weren't existent using https://github.com/Lachee/raylib-goplus although this version of the bindings hasn't been updated in 16 months 
![image](https://user-images.githubusercontent.com/82185981/135736951-f95b13f5-0d58-4699-9307-7ae397cdca20.png) this is from raylib plus

**Comment by rasa-silva** [comment]
Just noticed this today when trying raygui. The `SetFont` binding is missing

**Comment by gen2brain** [comment]
Raygui here is rewritten in Go and not a direct binding to raygui.h. There are probably more issues or PRs where that is stated. Then later I was not able to follow all new features and improvements so it is stuck. The solution would be for someone to improve upon what we have here or to create a C binding the same as is done for raylib.h. I don't have time to do neither of these currently.

**Comment by gen2brain** [comment]
Closed in favor of https://github.com/gen2brain/raylib-go/issues/197.
