### ISSUE TITLE
The signature for UpdateAudioStream seems to be wrong and doesn't match the example for raw audio streams

### ISSUE THREAD

**Issue by rasteric** [gen2brain/raylib-go#151]
I tried following the example in _examples/audio/raw_stream/main.go_ for playing a sine wave but it seems that `UpdateAudioStream` expects an `unsafe.Pointer` to the buffer as second argument. Given that it is a slice to `[]float32` in the example, I'm not sure how to obtain that. When I use `unsafe.Pointer(&data)` where data is `[]float32` I get an error _cgo argument has Go pointer to Go pointer_. 

Ideally, I'd have a `[]byte` buffer that I can update and manipulate while the stream is playing, since using `[]float32` would require copying or major changes to my application (it's a programming language that does not have float slices). But in any case, there seems to be something wrong with `UpdateAudioStream` and the example as it is.

I'd also like to know how to get the frequency right for given sample rate and how to make sure that e.g. a sine wave has zero crossings. Doesn't that mean that the buffer size and sample rate need to be chosen in exactly the right way? I'm a bit at a loss here, Raylib's docs are sparse about this and the raylib-go example mentions crackles.

**Comment by rasteric** [comment]
I got it working, thank you very much! One problem is that (apparently) the internal audio stream default buffer is `sampleRate/30`, e.g. you have to use 1600 for a sample rate of 48000, and there is no access to `SetAudioStreamBufferSizeDefault` in Go. It's a bit CPU intensive to update the internal buffer so often with `UpdateAudioStream` but works. Remaining crackling seems to be due to lack of zero-crossing in the sine wave when the []float32 buffer loops. 

Related discussion in Raylib: https://github.com/raysan5/raylib/issues/1770

**Comment by gen2brain** [comment]
Added function `SetAudioStreamBufferSizeDefault`, raw_stream example now needs to be changed.
