### ISSUE TITLE
Go build does not include image/txt files

### ISSUE THREAD

**Issue by FlorianWoelki** [gen2brain/raylib-go#152]
I've been trying to build a binary from a simple game/example like [this one](https://github.com/gen2brain/raylib-go/tree/master/examples/textures/image_drawing). However, building it to a binary using this command: `go build -o bin/test` does not include the image files.

The error just says that the image was not found. Is there any possible way to integrate images directly into the built file? I was inspecting the [embed package](https://pkg.go.dev/embed). But I cannot manipulate the asset loading of raylib.

In addition, when I extract the asset files into the binary directory it works fine when I run the binary file in a terminal with that exact path.

**Comment by gen2brain** [comment]
There are already functions like `LoadImageFromMemory, LoadWaveFromMemory, LoadMusicStreamFromMemory, LoadFontFromMemory, LoadShaderFromMemory`, there is no need for some special support for `embed`, just use it. 

There is also https://github.com/gen2brain/raylib-go/tree/master/rres for embedding AND encoding but probably needs to be revisited to add support for all FromMemory functions.

**Comment by FlorianWoelki** [comment]
Thank you for the quick answer! I would go with the `LoadImageFromMemory` function. Could you please make a quick example of how to use it?

**Comment by FlorianWoelki** [comment]
Thank you, I've got a working example!
