### ISSUE TITLE
DrawRectanglePro has wrong signature

### ISSUE THREAD

**Issue by DenizBasgoren** [gen2brain/raylib-go#153]
rl.DrawRectanglePro accepts an array of colors: [ ]rl.Color, and then picks only the first one to call the C function. The C function doesn't need arrays and only requires a single color. Expecting an array there is redundant. Other similar functions in go expect a single Color, but this particular function expects an array.

The signature:
`func DrawRectanglePro(rec Rectangle, origin Vector2, rotation float32, colors []Color)`

**Comment by gen2brain** [comment]
Fixed.
