### ISSUE TITLE
Strange interaction with vscode-go debugger

### ISSUE THREAD

**Issue by shingle-bells** [gen2brain/raylib-go#154]
I'm having a really strange bug: when I run my code through `go run .` it all works fine, but when I try to run it in vscode-go's debugger, it exits with the code `3221225477`, which seems to be an access violation error. The console doesn't print anything else. Running through the code, it seems that the error happens on line 24 of platform_desktop.go (`C.InitWindow(cwidth, cheight, ctitle)`), where the problem seems to happen on the C side of things which makes it harder to debug on my end (since delving further won't show me the C source code). If it helps, here's my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}",
            "env": {},
            "args": []
        }
    ]
}
```
Thanks in advance!

**Comment by gen2brain** [comment]
Well, not sure how is that related to raylib-go if everything works just fine without a debugger. Does it actually have support for CGO? I.e., does it supports other CGO projects that initialize OpenGL context but doesn't work only here? No idea, I never needed debugger for Go.
