### ISSUE TITLE
Are model animations supported?

### ISSUE THREAD

**Issue by MelonFunction** [gen2brain/raylib-go#156]
I can't find anything that would suggest they are, but it might be created under a different name than I'm expecting.

**Comment by gen2brain** [comment]
Animations are not supported, it will be a mess because of an array of arrays, etc. similar to model issues. I will try to do something when I find time, any help is welcome.

**Comment by gen2brain** [comment]
Functions are added, without example. Example will need to use `unsafe.Slice`.

**Comment by JupiterRider** [comment]
@gen2brain Could you close this issue please? Thanks
