### ISSUE TITLE
Examples assume they run on a single thread

### ISSUE THREAD

**Issue by strangebroadcasts** [gen2brain/raylib-go#16]
Raylib drawing commands aren't thread-safe - which isn't a huge deal, since OpenGL isn't to begin with - but since the examples don't lock an OS thread, drawing commands could potentially be issued on a different thread after garbage collection (as in [this issue](https://github.com/raysan5/raylib/issues/355)). 

The quick and dirty way of fixing this would be to manually call `runtime.LockOSThread` in the examples. However, this seems like a common enough gotcha with Go and graphics libraries that it might be a good idea to handle it in the binding somehow - possibly by providing a [mainthread](https://github.com/faiface/mainthread)-style helper?

**Comment by gen2brain** [comment]
There is this page that can be linked from README https://github.com/golang/go/wiki/LockOSThread . SDL bindings has this helper https://github.com/veandco/go-sdl2/commit/bc9d5d1882528a19da2e638decae0bc239e78cfd with some examples how to use it https://github.com/veandco/go-sdl2/blob/master/examples/render_goroutines/render_goroutines.go but now sure if that can work here, will need some time to test.

**Comment by strangebroadcasts** [comment]
An alternative to the helper would be to create a `Context` struct (or similar) maintaining an internal work queue, similar to what [mobile/gl](https://github.com/golang/mobile/blob/master/gl/work.go) does, with all raylib functions being defined as methods on that struct. That'd be a little more work, but it would remove the need to wrap everything in `Do` calls.
