### ISSUE TITLE
3D lighting

### ISSUE THREAD

**Issue by jarreed0** [gen2brain/raylib-go#160]
err: undefined NewLight and LightTypeDirection on ln 71 in [examples/shaders/mesh_instancing/main.go](https://github.com/gen2brain/raylib-go/blob/master/examples/shaders/mesh_instancing/main.go)

Does lighting work? I can't seem to figure it out and the example doesn't work

**Comment by jarreed0** [comment]
I tried finding a solution with members on the raylib subreddit and was told to make an issue ticket here.

**Comment by gen2brain** [comment]
Example works fine here. Make sure you are using the latest version of raylib-go (4.0).
Also, NewLight/LightTypeDirection, etc. is defined in `light.go` in that same dir, so you probably are not building correctly (i.e. `go build main.go`, `go run` etc.).

**Comment by jarreed0** [comment]
that was the problem, sorry about that and thank you
