### ISSUE TITLE
warning: 'ALIGN' macro redefined [-Wmacro-redefined]

### ISSUE THREAD

**Issue by kaidesu** [gen2brain/raylib-go#166]
I've been running into the following warning message when compiling/running tests - is this something that needs to be fixed with the bindings provided by `raylib-go`?

```
# github.com/gen2brain/raylib-go/raylib
In file included from raudio.c:209:
/Users/kai/Go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20220116181443-e4777d30ee99/external/jar_xm.h:521:9: warning: 'ALIGN' macro redefined [-Wmacro-redefined]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/i386/param.h:85:9: note: previous definition is here
```

And if it helps, here's how I'm building -- nothing fancy:

```
GOOS=darwin go build -trimpath -o ../dist/mac/ghost cmd/*.go
```

**Comment by Gabe-Lee** [comment]
I'm having the same problem, also building on MacOS. It doesn't SEEM to be affecting anything negatively but it'd be nice to get a fix for it.
