### ISSUE TITLE
Installation error on macOS Monterey (M1)

### ISSUE THREAD

**Issue by evprkr** [gen2brain/raylib-go#168]
```
> go get -v -u github.com/gen2brain/raylib-go/raylib
# github.com/gen2brain/raylib-go/raylib
In file included from raudio.c:209:
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20220116181443-e4777d30ee99/external/jar_xm.h:521:9: warning: 'ALIGN' macro redefined [-Wmacro-redefined]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/arm/param.h:61:9: note: previous definition is here
```

macOS Monterey 12.3 Beta
MacBook Air M1 8GB

**Comment by gen2brain** [comment]
And this is a straight duplicate of previous issue #166.

**Comment by evprkr** [comment]
> And this is a straight duplicate of previous issue #166.

Ah, my bad I didn't see this when I searched before posting.


> That is only a warning? Or you are not able to build?

Running `go build main.go` gives me:
```
main.go:3:8: no required module provides package github.com/gen2brain/raylib-go/raylib: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Comment by evprkr** [comment]
And then if I do `go mod init` and then try to build, I get:
```
package command-line-arguments
	imports github.com/gen2brain/raylib-go/raylib
	imports github.com/gen2brain/raylib-go/raylib: import cycle not allowed
```

**Comment by gen2brain** [comment]
What main.go file, where is it located? Can you compile any of examples?

**Comment by evprkr** [comment]
This is being ran from a new folder with nothing but a main.go file (and now a go.mod file), it's basically a copy/paste of the example from the readme, I'll try another example though

**Comment by evprkr** [comment]
Solved by reinstalling Go. No clue what was wrong, it was a fresh install to begin with.
