### ISSUE TITLE
Cross-compiling from Linux to MacOS

### ISSUE THREAD

**Issue by joaoofreitas** [gen2brain/raylib-go#169]
Anyone knows if  is it possible to cross-compile using this library. I've tried everything but I always get the same error.

![image](https://user-images.githubusercontent.com/31630346/158079625-89e2da66-a583-4b44-873a-5589ad02ff5b.png)

Can you help me with this @gen2brain ?
Best Regards

**Comment by gen2brain** [comment]
Sure, it is possible. You need the macOS toolchain installed from here https://github.com/tpoechtrager/osxcross. Then you will build like this, e.g. `CC=aarch64-apple-darwin21.1-clang CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 go build`. 
You can see a more complicated cgo example here https://github.com/gen2brain/bukanir/blob/master/desktop/make.bash#L143.

Same rules as for C, you need the toolchain.

**Comment by joaoofreitas** [comment]
Thanks for the quick response!
Everything worked out nicely!

Happy code!
