### ISSUE TITLE
Support for PushMatrix and PopMatrix

### ISSUE THREAD

**Issue by nvlled** [gen2brain/raylib-go#171]
It doesn't look like rlPushMatrix(), rlPopMatrix(), and rlLoadIdentity() are supported yet. Let me see if I can add it myself.

**Comment by gen2brain** [comment]
Only functions from the public `raylib.h` API are implemented and nothing from low-level APIs. That is something that is changing a lot, it is not only a matter of implementing but also later maintaining them.

**Comment by nvlled** [comment]
`rlPushMatrix` and others are defined in `rlgl.h`, and [rlgl.go](https://github.com/gen2brain/raylib-go/blob/master/raylib/rlgl.go) already uses `rlgl.h`, so it's only a matter of adding wrapper functions for them. The functions might be low-level, but they are fundamental part of the API. I can't even do something basic like drawing a rotated cube without them. Lots of raylib examples also uses these functions, so it's not like they are internal API that shouldn't be exported. Omitting them makes the binding rather incomplete IMO.

**Comment by gen2brain** [comment]
@nvlled, @Technerder added some support here https://github.com/gen2brain/raylib-go/issues/186. If one of you can actually make it work, and you add all rl* functions, together with some useful 3rd party examples I may reconsider and add such functions to the repo.

**Comment by gen2brain** [comment]
Implementation and example are added to the repo.
