### ISSUE TITLE
No way to pass null shader source to `LoadShaderFromMemory`

### ISSUE THREAD

**Issue by drako0812** [gen2brain/raylib-go#172]
In my program I need to load only a fragment shader from a `string` and I would like to keep the default vertex shader.

In C/C++ I could do the following:

```.cpp
Shader myShader = LoadShaderFromMemory(NULL, myFragmentShader);
```

But in Go the closest equivalent would be:

```.go
myShader := rl.LoadShaderFromMemory("", myFragmentShader)
```

but that just passes an empty string for Raylib to try to load and then OpenGL fails to compile it, thus leaving the Shader in an unusable state. So either the solution would be to either specially handle an empty string or possibly more idiomatically Go, provide a function like `rl.LoadFragmentShaderFromMemory(fsCode string) Shader`.

**Comment by gen2brain** [comment]
Allowed in https://github.com/gen2brain/raylib-go/commit/b14428548163b00cb9f98c7aa98aa03ad93c6676.
