### ISSUE TITLE
Window doesnt launch up

### ISSUE THREAD

**Issue by pixthehe** [gen2brain/raylib-go#177]
Hi, so my issue is that I initialize a project and then I install this repo to it and I copy the example code and it just doesnt throw an erorr or anything it just doesnt work.

btw I run 

go run main.go

please tell me if im doing anything wrong.

**Comment by JupiterRider** [comment]
Hey,

did you install a C compiler as well on your pc? Like [MinGW](https://www.mingw-w64.org/) for example?

Raylib-go uses cgo. Maybe also look at their Documentation: [https://github.com/golang/go/wiki/cgo#windows](https://github.com/golang/go/wiki/cgo#windows)

**Comment by pixthehe** [comment]
INFO: Initializing raylib 4.0
WARNING: GLFW: Error: 65542 Description: GLX: GLX extension not found
WARNING: GLFW: Failed to initialize Window
FATAL: Failed to initialize Graphic Device
exit status 1




I just got this error

**Comment by pixthehe** [comment]
well I am running on vnc right now but on my main computer it just doesnt do anything when I run go run.

**Comment by JupiterRider** [comment]
Please make sure this issue is Raylib-go related.
Maybe try a "Hello World" go program, and make sure your environment works properly. [https://go.dev/doc/tutorial/getting-started](https://go.dev/doc/tutorial/getting-started)

If it does, try without vnc.

**Comment by pixthehe** [comment]
Now its working so yay I guess.
