### ISSUE TITLE
raygui - keys are registered twice 

### ISSUE THREAD

**Issue by dysoco** [gen2brain/raylib-go#18]
Good Evening.

Trying the GUI module I ran into the problem that keys are registered twice (i.e. I type 'e' I get 'ee') when typing into a raygui.Textbox.

This does not seem to be related to the framerate, and apparently it's only a problem with the textbox (keyboard works fine with the camera demos).

You can try the [basic controls](https://github.com/gen2brain/raylib-go/blob/master/examples/gui/basic_controls/main.go) demo which reproduces the error in my PC (this happened every single time I've tried it so far).

I'm using Go 1.7.4 x86_64 running in Ubuntu 17.04.

I wonder if this is somehow related to #13 ? Not sure how this works internally but my problem happens when pressing the key quickly and not when holding the key down for a second.
Thanks.

**Comment by gen2brain** [comment]
Hello,

There have been some changes to GUI and library. Can you try now with latest version from master.
Didn't happen before to me, when I hold the key it does repeat, but not when typing quickly.

**Comment by gen2brain** [comment]
I will close this one, please file a new issue or reopen if you have more info on this.
