### ISSUE TITLE
Some functions require ints which causes jumping between pixels

### ISSUE THREAD

**Issue by drum445** [gen2brain/raylib-go#187]
This has been raised and fixed in the main raylib repo a few years back [(link)](https://github.com/raysan5/raylib/issues/527) and I was wondering if there are any plans to fix it here.

I'm finding the same problem as described in the above issue when trying to use DrawText as I have to convert my float pixels to ints, which means they can't be rendered smoothly per-tick

Thanks

**Comment by gen2brain** [comment]
Thanks, PR is welcomed, especially if you are aware of the problem and know how to fix.

**Comment by drum445** [comment]
Cheers, haven't got round to looking into a codefix for this, but for anyone else that stumbles across this issue, the work-around is to use:  
* DrawTextEx
* DrawTexturePro

As both of these accept float types.

Ta
