### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by tek967** [gen2brain/raylib-go#191]
Building a raylib-go project right now, and during the build it says
`# github.com/gen2brain/raylib-go/raylib
rcore.c:1041:1: warning: non-void function does not return a value [-Wreturn-type]
rcore.c:2648:1: warning: non-void function does not return a value [-Wreturn-type]
rcore.c:4431:22: error: use of undeclared identifier 'eglGetProcAddress'`

strange, any fixes?

**Comment by gen2brain** [comment]
This is duplicate of #71. There is nothing strange, bsd is not supported. You are welcome to add the support.

**Comment by gen2brain** [comment]
Closed in favor of https://github.com/gen2brain/raylib-go/issues/71.
