### ISSUE TITLE
Thanks (not an issue)

### ISSUE THREAD

**Issue by nicholasimon** [gen2brain/raylib-go#193]
Just want to say thanks I managed to use the bindings to make a game with Go and Raylib, after many years of trying. Is not great however I really appreciate the work you do.

View on Youtube here https://www.youtube.com/watch?v=TmP7JscCXqw
Game on itch.io here https://nicholasimon.itch.io/the-endless-dungeons-of-pixel
Code on Github here https://github.com/nicholasimon/endless_dungeons_of_pixel

**Comment by gen2brain** [comment]
Thanks, the game looks great. Btw. version 4.2 is released.
