### ISSUE TITLE
Drop Down Box missing

### ISSUE THREAD

**Issue by SiirRandall** [gen2brain/raylib-go#194]
Looking at the RayGUI for C I see a GuiDropDown() I don't see it in this go binding. Is this not yet implemented or am I missing something?

**Comment by gen2brain** [comment]
You are missing a couple of issues, like https://github.com/gen2brain/raylib-go/issues/150#issuecomment-940207107 or https://github.com/gen2brain/raylib-go/pull/183, help is welcome.

**Comment by gen2brain** [comment]
Closed in favor of https://github.com/gen2brain/raylib-go/issues/197.
