### ISSUE TITLE
Question: Recommended Way to Build an .exe File?

### ISSUE THREAD

**Issue by FloatingSunfish** [gen2brain/raylib-go#195]
I use the below command to build .exe files for the **_[example projects](https://github.com/gen2brain/raylib-go/tree/master/examples)_**:

>go build -o main.exe -ldflags -H=windowsgui

**_NOTE:_** `-ldflags -H=windowsgui` is used to hide the Console Window.

My question is, is there a recommended command to build .exe files for `raylib-go` apps?
Is the above command okay, or is there a better one?

**Comment by gen2brain** [comment]
That is fine. You can add "-s -w" to ldflags to strip debuggin symbols and to get smaller binary.

**Comment by FloatingSunfish** [comment]
@gen2brain Thanks for the answer and the tips!

May I ask for a link on where I can read more about the `-s` and `-w` flags to see what they exactly do?
A brief summary/description would also be fine.

This is the first time I've had to work with `ldflags`, so it's all new to me, and I want to make sure I do things right.
I also can't find any documentation about its flags. I use `TDM-GCC`.

**Comment by FloatingSunfish** [comment]
@gen2brain Quick follow-up: Is there a time when I would want to omit `-s` and `-w`?

Or times when I would find the following useful?
- symbol table and debug information
- DWARF symbol table

**Comment by gen2brain** [comment]
They can be useful if you want to debug binary, e.g. with gdb or similar.

**Comment by FloatingSunfish** [comment]
@gen2brain 
Quick question. On Windows, the below command used to work just fine:

    go build -o main.exe -ldflags -H=windowsgui -s -w


However, when I run it now, it returns the following error:

> flag provided but not defined: -s
> usage: go build [-o output] [build flags] [packages]
> Run 'go help build' for details.


It's as if the `-s` and `-w` flags are no longer recognized for some reason (the command works fine without said flags.).

Reordering the flags after `-ldflags` doesn't seem to help either.

Am I doing something wrong? Or do you have any idea what could be happening?

**Comment by gen2brain** [comment]
@FloatingSunfish `-s -w` are ldflags, add quotes, i.e. `-ldflags "-H=windowsgui -s -w"`.

**Comment by FloatingSunfish** [comment]
@gen2brain 
Ah, I knew I was missing something! I didn't realize the flags had to be in quotes.
Many thanks for answering! 😊
