### ISSUE TITLE
Question: How Complete is `raylib-go` as a Binding for `raylib v4.0`?

### ISSUE THREAD

**Issue by FloatingSunfish** [gen2brain/raylib-go#196]
I saw that `raylib-go` is a binding for `raylib v4.0` in the **_[Bindings List](https://github.com/raysan5/raylib/blob/master/BINDINGS.md)_**, and only a few bindings support the recent `v4.2`.

How complete is `raylib-go` as a binding for `raylib v4.0`?
Is it missing any features?

Also, are there plans to support `raylib v4.2` in the future?

**Comment by gen2brain** [comment]
If you find anything missing PR is welcome and will be accepted. When I find time I will update C sources.

**Comment by FloatingSunfish** [comment]
@gen2brain I see. 🙂

Alright, I'll close this issue now and just open a new one if I find any missing features.

Thanks!

**Comment by gen2brain** [comment]
PR would be preferred instead of issue, thanks.

**Comment by gen2brain** [comment]
Raylib-go 4.2 is released btw.
