### ISSUE TITLE
Rewrite/redesign raygui

### ISSUE THREAD

**Issue by gen2brain** [gen2brain/raylib-go#197]
Raygui was rewritten in Go a long time ago. In the meantime, the C version is rewritten and new features are added. Some possible actions now are to rewrite again in Go or maybe use modernc ccgo and work with that. The other possibility is to create C bindings, which would require a lot of code duplications and will be more difficult to maintain as noted in PR https://github.com/gen2brain/raylib-go/pull/183.

**Comment by Konstantin8105** [comment]
Hello,
At the end of that week I will prepare the PR for widgets.
Have fun.
