### ISSUE TITLE
Update rres

### ISSUE THREAD

**Issue by gen2brain** [gen2brain/raylib-go#198]
Rres now have a final format, Go rres and the resources example should be updated. Also, there are many FromMemory functions that didn't exist before.

**Comment by Konstantin8105** [comment]
Hello, just for information. 
Location of last revision https://github.com/raysan5/rres

**Comment by JupiterRider** [comment]
Hey,
does anyone even use rres? I'm running fine with go embed and the "LoadFromMemory" functions.

**Comment by gen2brain** [comment]
Sure, `go embed` works just fine. The rres also allows users to encrypt their data, i.e. with AES, 3DES, XOR, etc. It also should allow compression, i.e. Deflate, LZ4, Brotli, etc. depending on what can be implemented easily. And having a resource module that is compatible with raylib would be nice.

**Comment by JupiterRider** [comment]
Hey @gen2brain,
currently I'm working on a binding:
https://github.com/JupiterRider/raylib-go/tree/master/rres

I will create a pull request once I'm done

**Comment by JupiterRider** [comment]
It's here now: #264
