### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by iszla** [gen2brain/raylib-go#199]
Hello!

It appears to me like the logging is not working. I might be looking in the wrong place, or doing something wrong but I understand it like this.

```
rl.TraceLog(rl.LogInfo, "Interesting log message")
```

Should print an info level log message with the message "Interesting log message", but as far as I can tell this does not work. I believe that this is due to the logTypeFlags variable being an int instead of a byte and the bitmasking in utils.go is checking if the flag is zero, when it should check if it is not zero.

I can make a PR for this, if I am correct and if I am wrong could someone please explain what I am doing wrong?

Thank you!

**Comment by gen2brain** [comment]
Hi, please send a PR, thanks.

**Comment by JupiterRider** [comment]
What about doing it like the original Raylib? They don't work with bit shifting / bitwise as well:
https://github.com/raysan5/raylib/blob/master/src/utils.c#L107

Here's an example:

```golang
type TraceLogLevel int

const (
	LogAll TraceLogLevel = iota
	LogTrace
	LogDebug
	LogInfo
	LogWarning
	LogError
	LogFatal
	LogNone
)

var logTypeLevel = LogAll

func SetTraceLogLevel(logType TraceLogLevel) {
	logTypeLevel = logType
}

func TraceLog(logType TraceLogLevel, text string) {
	if logType < logTypeLevel {
		return
	}

	switch logType {
	case LogTrace:
		fmt.Printf("TRACE: %s\r\n", text)
	case LogDebug:
		fmt.Printf("DEBUG: %s\r\n", text)
	case LogInfo:
		fmt.Printf("INFO: %s\r\n", text)
	case LogWarning:
		fmt.Printf("WARNING: %s\r\n", text)
	case LogError:
		fmt.Printf("ERROR: %s\r\n", text)
	case LogFatal:
		fmt.Printf("FATAL: %s\r\n", text)
	}
}
```

But I don't want to pull this. It's your turn @iszla  :)

**Comment by iszla** [comment]
It could have been one way to go, but I believe that would be a breaking change with how the logging levels work today.
Which the way it is implemented in raylib you choose a level and that will the print log messages of that log message or higher, while with the bitmask flag you have the possibility to choose exactly which levels to log.
