### ISSUE TITLE
no buildable Go source files

### ISSUE THREAD

**Issue by allochi** [gen2brain/raylib-go#2]
Hi, I get

```
package github.com/gen2brain/raylib-go: no buildable Go source files in ...
```

on macOS with `glfw3` and `openal-soft` installed with `brew` and linked.

**Comment by gen2brain** [comment]
Hello, Just use `go get -v github.com/gen2brain/raylib-go/raylib` changed that in README.

**Comment by allochi** [comment]
Thanks, I tried this on Mac, it works, but now I get 'al/al.h' not found, although I did install openal-soft  using brew.

Any advice on that?

**Comment by gen2brain** [comment]
That should be Al/al.h and AL/alc.h. If they are not in your include path add it to CGO_CFLAGS="-I/path/to/main/include/dir"

**Comment by allochi** [comment]
@gen2brain Thanks a lot of your help so far, unfortunately, I reached a dead end again, even when I use the following:

```
 CGO_CFLAGS="-I/usr/local/Cellar/openal-soft/1.17.2/include -I/usr/local/Cellar/glfw/3.2.1/include" CGO_LDFLAGS="-L/usr/local/Cellar/openal-soft/1.17.2/lib -L/usr/local/Cellar/glfw/3.2.1/lib" go run main.go
```

I get

```
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/audio.go:111: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/audio.go:200: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/audio.go:306: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/audio.go:368: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/core.go:459: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/core.go:466: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/core.go:690: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/core.go:698: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/core.go:706: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/core.go:714: cannot convert ret (type C._Bool) to type int
../../../gocode/src/github.com/gen2brain/raylib-go/raylib/core.go:714: too many errors
```

Could you share some hint on how do manage to run on a mac? thanks!

**Comment by gen2brain** [comment]
Did you try without run?

**Comment by gen2brain** [comment]
I don't have mac, so not sure when I can try, maybe in virtual machine.

**Comment by gen2brain** [comment]
Can you try now? OpenAL installed with brew is "keg only", doesn't link includes and libs. Now system OpenAL.framework is used. Just delete previous source from $GOPATH or update with
`go get -u github.com/gen2brain/raylib-go/raylib`

**Comment by allochi** [comment]
This is amazing! it works now, and it's wonderful! Many, many thanks!!!

I cloned the repo to get the examples, and tried some, they all worked except for one, but everything seems to be well for now.

Many, many thanks for the wonderful job and support you provided!

**Comment by gen2brain** [comment]
Great! I am glad that it worked.  Do you maybe remember which example did't worked?

**Comment by allochi** [comment]
Hi, Sorry got caught up with work, I will test all the examples and give you a full feedback on them in the next day or two.

**Comment by allochi** [comment]
Hi, sorry for being late, as promised the examples that don't work are:

text/ttf_loading
textures/raw_data
