### ISSUE TITLE
SetTraceLog doesn't affect logs of the framework

### ISSUE THREAD

**Issue by JupiterRider** [gen2brain/raylib-go#203]
SetTraceLog should also affect logs of the framework. 
So for example if I would do `rl.SetTraceLog(rl.LogNone)`, it should suppress all Logs, not just the ones I create with rl.TraceLog.

**Comment by JupiterRider** [comment]
```golang
rl.SetTraceLog(7)
```
Suppresses all Logs of the framework

**Comment by gen2brain** [comment]
This should be fixed in https://github.com/gen2brain/raylib-go/commit/dfbb5ab754535ac1b92b83c2523bd929d30a7789.
