### ISSUE TITLE
Missing gui components under raygui

### ISSUE THREAD

**Issue by alanlichen** [gen2brain/raylib-go#205]
Some components are missing under raygui. As an example, GuiScrollPanel does not exist, but it is a component that I really need. Are there any plans for these components to be implemented?

Related to #197

**Comment by gen2brain** [comment]
As you wrote, this is a duplicate of https://github.com/gen2brain/raylib-go/issues/197, you can see there is a plan, when will that happen is unknown, help is welcome.
