### ISSUE TITLE
Getting audio support

### ISSUE THREAD

**Issue by qarlosh** [gen2brain/raylib-go#21]
Hello,

I'm trying to use the audio functions, but I'm not able to link with OpenAL. If I try to run some audio example, I get the expected error:

`audio.c:89:59: fatal error: AL/al.h: No such file or directory`

I downloaded the OpenAL binaries (I am on Windows) from http://kcat.strangesoft.net/openal-binaries/openal-soft-1.18.2-bin.zip, but I don't know where to go from here. I probably should place the include and lib folders where the Cgo system can find them, but I cannot figure where...

Sorry if this is a trivial question, but I am not into C programming - that's why I am trying Go :)

Thank you!

**Comment by gen2brain** [comment]
Hello, 

I am not sure how cgo and Windows work together but it seems you have C compiler. You can do it like this, just pass CFLAGS AND LDFLAGS:
`CGO_CFLAGS="-I/path/to/your/includes" CGO_LDFLAGS="-L/path/to/your/libs" go build`

**Comment by qarlosh** [comment]
Thank you! With your indications I made it work.

To note, the Windows binaries downloaded from http://kcat.strangesoft.net/openal.html has the libs named `libOpenAL32.dll.a`, so I had to rename it to `libopenal.a`. Apart from this, only needed to set the environment variables as you said.

The `raw_stream` example runs ok but doesn't produce any sound, while the other 3 audio examples play perfectly... could this be another issue?

**Comment by gen2brain** [comment]
Great! I will check raw_stream example, I think there was an issue before on macOS with that example.

**Comment by raysan5** [comment]
`audio_raw_stream` example generates an plays a sine wave but I feel it does not works as expected... listening to it, there is a sound bump every second or so that I'm not sure why happens...

**Comment by qarlosh** [comment]
The sound bump issue happens in the raylib.com web examples,  so I don't think it is something related to the Go wrapper

**Comment by gen2brain** [comment]
OpenAL is not a requirement anymore, on Windows now only C compiler for cgo is needed, mingw-w64, tdm-gcc etc. I will close this issue, for raw_stream example probably better to file an issue at raylib, if there are issues.
