### ISSUE TITLE
Speed up development with CGO (gcc) and VS Code

### ISSUE THREAD

**Issue by JupiterRider** [gen2brain/raylib-go#217]
I work with the source of raylib-go in VS Code and the compiler rebuilds the project whenever I save a file.
The compiling always takes about a minute and this process blocks VS Code.

Is there any way, I can speed this up?

**Comment by gen2brain** [comment]
I am afraid there is no way to speed this up. I use a plain "dummy" editor that will not try to rebuild everything after something is changed.
