### ISSUE TITLE
Is building for mobile and web target supported?

### ISSUE THREAD

**Issue by dbriemann** [gen2brain/raylib-go#22]
I ask because raylib offers building for the web via emscripten and building natively for at least Android. 

Are these features also available for raylib-go?

**Comment by gen2brain** [comment]
Building for android is supported, see here https://github.com/gen2brain/raylib-go/tree/master/examples/android/example . I am working on improved bootstrap script that should work (in theory at least) also on Windows and macOS. 

Emscripten is not supported. Maybe someday, if Go llvm support is matured, and also implemented for other platforms besides x86_64, so code can bi compile to bytecode, and then processed with emscripten, something like that I guess.

**Comment by dbriemann** [comment]
Wow fast reply! 
Great to here that it works for Android already! 

About the web target: have you considered using GopherJS instead of Emscripten? That's what all the other projects use to compile Go to Javascript. I don't really know how much work this would be though..

**Comment by gen2brain** [comment]
I have considered GopherJS, but it seems like a lot of work. raylib-go is wrapper around C library, with C code included in project. Other projects also use cgo where they need, i.e. GL, OpenAL, but have that better isolated. For raylib-go, a lot of parts will need to be rewritten in Go, and then exported back to C code, rlgl.c for example. Something can be done with tags probably, but still a lot of work.

**Comment by dbriemann** [comment]
I had a gut feeling that cgo will be a problem there. I guess then the web target will have to wait :)
Thanks for all the info! Seems like I have to stick to other languages for now sadly.

**Comment by gedw99** [comment]
There is work happening for golang to support WASM. It's looking promising.

Then it's going to be very interesting with regards to how the c code and golang code that are both converted to wasn't will work.

If I had to guess it would be great if when the golang wasm compiler sees a c dependency it does the compilation to wasm for you and then uses the wasm headers to compile your golang code using the wasm headers from the dependency.
But I doubt it will do all that for you from day one. 
I have seen other project use asm.js her with gopherjs but did not look to deeply how they do the binding 

Wasm is going to be amazing though I feel.

**Comment by gen2brain** [comment]
@gedw99 I only now browsed through projects you linked. Not perfect, but i would like to try some combination of emscripten and gopherjs. Will need to investigate and see how everything can be combined of course. Thanks!

**Comment by gedw99** [comment]
no probs.

if you want to be on the tip here is he WASM for golang
https://github.com/neelance/go/tree/wasm-wip

**Comment by gen2brain** [comment]
Web target is now partially implemented, there are problems with _emscripten_set_main_loop() function, see https://github.com/gen2brain/raylib-go/issues/28 .

**Comment by gedw99** [comment]
@gen2brain thats great. Will have a look.
