### ISSUE TITLE
Add example build

### ISSUE THREAD

**Issue by Konstantin8105** [gen2brain/raylib-go#223]
Hello,

I think we can add `go build` for each `example` for checking build.

https://github.com/gen2brain/raylib-go/blob/ce3c8e83dd6dbccab1472e6f8e33ab8b15d9844a/.github/workflows/build.yml#L21

Have fun.

**Comment by gen2brain** [comment]
Doesn't `go build ./...` already builds everything?

**Comment by Konstantin8105** [comment]
Hello, @gen2brain 

Just for information. I see the error if run `Makefile`.
```
konstantin[13:50:57]~/go/src/github.com/Konstantin8105/raylib-go
$ make
Building package github.com/gen2brain/raylib-go/raylib...
no required module provides package github.com/gen2brain/raylib-go/raylib: go.mod file not found in current directory or any parent directory; see 'go help modules'
make: *** [Makefile:8: packages] Error 1
```

**Comment by gen2brain** [comment]
I removed the Makefile, it was used for travis-ci I think.

**Comment by gen2brain** [comment]
I added a build test for examples. Now it fails to compile GUI examples because of missing raylib symbols. When I try locally `go build ./...` for examples workdir it works fine.
