### ISSUE TITLE
Just wondering about Basic Lighting

### ISSUE THREAD

**Issue by nicholasimon** [gen2brain/raylib-go#227]
You are probably busy though I would really like to be able to complete the Basic Lighting Raylib Shaders example, it is not added however would be really great if it could be.

**Comment by nicholasimon** [comment]
Don't want to pester as I am sure you are busy however it would be amazing if the basic lighting could be implemented or at least put on a To Do list at some stage https://www.raylib.com/examples/shaders/loader.html?name=shaders_basic_lighting

**Comment by gen2brain** [comment]
@nicholasimon Is there anything that is missing in raylib-go that is preventing that example to be written in Go? I thought it is just an example, if it is just that, I am not going to work on this. Though, everyone is welcome to send new examples and improve existing ones. If there are missing functions I can work on that.

**Comment by nicholasimon** [comment]
No, I don't mean add the example I mean the implementation of the basic lighting. There is an include as well as functions like CreateLight that I don't think is currently in the Go port of Raylib. I might be wrong however. See code taken from example below.

#include "rlights.h"

 // Create lights
    Light lights[MAX_LIGHTS] = { 0 };
    lights[0] = CreateLight(LIGHT_POINT, (Vector3){ -2, 1, -2 }, Vector3Zero(), YELLOW, shader);
    lights[1] = CreateLight(LIGHT_POINT, (Vector3){ 2, 1, 2 }, Vector3Zero(), RED, shader);
    lights[2] = CreateLight(LIGHT_POINT, (Vector3){ -2, 1, 2 }, Vector3Zero(), GREEN, shader);
    lights[3] = CreateLight(LIGHT_POINT, (Vector3){ 2, 1, -2 }, Vector3Zero(), BLUE, shader);

**Comment by nicholasimon** [comment]
I can't see rlights listed under https://github.com/gen2brain/raylib-go)/raylib/

**Comment by nicholasimon** [comment]
Not urgent as I understand these things take awhile though was just wondering about it

**Comment by gen2brain** [comment]
`rlights.h` is just a part of an example, not part of the library. There will not be bindings for example.

**Comment by gen2brain** [comment]
And it looks simple enough that it can be implemented as part of an example, in one Go file, basically a Light struct and some methods. As I said, PRs for example are welcome.

**Comment by nicholasimon** [comment]
So, in other words it is possible to implement basic lighting currently with the Golang bindings?

**Comment by gen2brain** [comment]
No idea, I take a quick look and it looks possible. Could you try it? Basic lighting is just one of the examples, raylib-go currently has 80+ examples, and I am not motivated to add more but contributions are always nice to have.

**Comment by nicholasimon** [comment]
I will take a look this evening and see if I can do it. I do have time so I can maybe do some examples then in my spare time. Let me start with Basic Lighting and will see how it goes. Sorry, there might be a time lag between replies I am in South Africa

**Comment by nicholasimon** [comment]
OK, unfortunately I am just a hobby coder and taught myself Go and my skills are just not enough to be able to do the lighting example, a little too advanced for me I am afraid. I will however see if I can contribute some of the easier examples when I have some time.
