### ISSUE TITLE
missing raylib.h

### ISSUE THREAD

**Issue by Joematpal** [gen2brain/raylib-go#232]
repo: [example gui](https://github.com/Joematpal/gui)

Here is an example of trying to run one of the example gui apps. Every time I try run `go run main.go` I get this error.

When I don't try to build the raygui app. It compiles fine. Am I running this wrong?

```
go run main.go           
# github.com/gen2brain/raylib-go/raygui
In file included from ../../../../pkg/mod/github.com/gen2brain/raylib-go/raygui@v0.0.0-20221202134249-3b16dbe50482/raygui.go:5:
./raygui.h:209:14: fatal error: raylib.h: No such file or directory
  209 |     #include "raylib.h"
      |              ^~~~~~~~~~
compilation terminated.
```

**Comment by Joematpal** [comment]
If I download the project and point to those files it works fine. Is there a better way? Am I missing something really obvious?

```
CGO_CFLAGS="-I$GOPATH/src/github.com/gen2brain/raylib-go/raylib -I$GOPATH/src/github.com/gen2brain/raylib-go/raygui" go run main.go
```

**Comment by gen2brain** [comment]
Works fine here with GUI examples. I also tested your example, are you sure you are using the latest version?

**Comment by Joematpal** [comment]
The gui examples work fine for me as well. My go version is 1.19.3. I thought I was using the latest version of the project.

**Comment by BubuAnabelas** [comment]
I'm getting the exact same error. Tried to debug it but couldn't find anything useful.

**Comment by Joematpal** [comment]
Thanks @BubuAnabelas! @gen2brain I'm not understanding how that is relevant to this being used as an external dependency on another project. Especially when the modules in the examples folder are replaces to use the modules with in internal project and the internal project has the C files. This is the thing that I'm trying to circumvent if possible. I'm not saying is anything wrong with the project. The project is amazing. I might just be a go convention that I'm not familiar with.


```
// examples/go.mod
replace github.com/gen2brain/raylib-go/easings => ../easings

replace github.com/gen2brain/raylib-go/physics => ../physics

replace github.com/gen2brain/raylib-go/raygui => ../raygui

replace github.com/gen2brain/raylib-go/raylib => ../raylib
```

**Comment by JupiterRider** [comment]
Same issue: #245 

@Joematpal This should be solved now.

**Comment by Joematpal** [comment]
Oh wow! Thanks, mate!
