### ISSUE TITLE
Chinese Font Prom

### ISSUE THREAD

**Issue by daojiAnime** [gen2brain/raylib-go#233]
When I use load to ` rl.LoadFont("fonts/simhei.ttf")` the drawing Chinese characters of Chinese fonts, only horizontal lines appear, and no Chinese characters are displayed.
Except for the different fonts, all the other codes are copied from the examples. I just modified the font file and character content. Here's my code.
```goalng
package main

import (
	"github.com/gen2brain/raylib-go/raylib"
)

func main() {
	screenWidth := int32(800)
	screenHeight := int32(450)

	rl.InitWindow(screenWidth, screenHeight, "raylib [text] example - bmfont and ttf sprite fonts loading")

	msgBm := "THIS IS AN AngelCode SPRITE FONT"
	msgTtf := "你好"

	// NOTE: Textures/Fonts MUST be loaded after Window initialization (OpenGL context is required)
	fontBm := rl.LoadFont("fonts/bmfont.fnt")  // BMFont (AngelCode)
	fontTtf := rl.LoadFont("fonts/simhei.ttf") // TTF font

	fontPosition := rl.Vector2{}

	fontPosition.X = float32(screenWidth)/2 - rl.MeasureTextEx(fontBm, msgBm, float32(fontBm.BaseSize), 0).X/2
	fontPosition.Y = float32(screenHeight)/2 - float32(fontBm.BaseSize)/2 - 80

	rl.SetTargetFPS(60)

	for !rl.WindowShouldClose() {
		rl.BeginDrawing()

		rl.ClearBackground(rl.RayWhite)

		rl.DrawTextEx(fontBm, msgBm, fontPosition, float32(fontBm.BaseSize), 0, rl.Maroon)
		rl.DrawTextEx(fontTtf, msgTtf, rl.NewVector2(75.0, 240.0), 80, 2, rl.Red)

		rl.EndDrawing()
	}

	rl.UnloadFont(fontBm)  // AngelCode Font unloading
	rl.UnloadFont(fontTtf) // TTF Font unloading

	rl.CloseWindow()
}
```

![image](https://user-images.githubusercontent.com/30306060/206465970-383cc550-b6cf-4aa9-b54f-ba19dcf867a6.png)

#### I have tried to switch different Chinese fonts. At present, several ttf fonts I switch cannot display Chinese. My code file is `utf-8` encoded format. Please help me.

**Comment by daojiAnime** [comment]
To add, I tried to draw ` fontData.Text ` and only see symbols, numbers, and Arabic letters.

**Comment by JupiterRider** [comment]
Hey @daojiAnime 

Does this help you: https://github.com/raysan5/raylib/discussions/2499

You can try to use the `LoadFontEx` function and provide a slice with the Chinese UTF-8 character numbers. I think the range is from 4E00–9FFF

**Comment by daojiAnime** [comment]
Hi @JupiterRider 
Thank you very much.It works.
There are a lot of glyph in Chinese, and I very much hope that go-raylib can provide better Chinese support. 
go-raylib is very cool.
