### ISSUE TITLE
Expose UploadMesh

### ISSUE THREAD

**Issue by KrissLaCross** [gen2brain/raylib-go#236]
The function in question: `void UploadMesh(Mesh* mesh, bool dynamic)` in `rmodels.c`

I noticed that this function isn't exposed in the go bindings.
Exposing it would be nice at it's a vital feature for mesh generation on the CPU side.

**Comment by JupiterRider** [comment]
@KrissLaCross 
Could you please close this issue? The function is now there.
Thanks!
