### ISSUE TITLE
Cannot get raylib GUI

### ISSUE THREAD

**Issue by muhdsalm** [gen2brain/raylib-go#239]
I installed raylib, then wanted to use raygui. So I ran this command:
`go get -v -u github.com/gen2brain/raylib-go/raygui`
But I got this error:
`go: github.com/gen2brain/raylib-go/raylib@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000`
What is causing this? How do I use raygui?

**Comment by muhdsalm** [comment]
Alright, so it seems that the problem is that the go.mod file of raygui references raylib-go version 0.0.0-00010101000000-000000000000, which does not actually exist. Is this a repo-side problem?

**Comment by muhdsalm** [comment]
Ok, so I got a hacky solution:
1. Download zip from this repository
2. Go to GOPATH (which you can find using `go env GOPATH`, for any new users), then go to pkg/mod/github.com (make the folders if they don't exist)
3. Create a folder named 'gen2brain'
4. Go into that folder, then create a folder called 'raylib-go'
5. Open (not extract) the downloaded zip file (step 1), then move the 'easings', 'physics', 'raygui', 'raylib' and 'rres' into the raylib-go folder
6. Then go to your project and open your main go file in notepad (vscode with go extension did not work for this step)
7. Add this line to your imports:
`gui github.com/gen2brain/raylib-go/raygui`
8. run `go mod tidy`

Now you can open the project in your IDE. Note that if you want physics, then add the line `"github.com/gen2brain/raylib-go/physics"`, then run `go mod tidy`.

Why does this issue occur, though?

**Comment by JupiterRider** [comment]
@muhdsalm could you reopen your issue please? I'm having the same "issue" and I would like to hear @gen2brain 's opinion on this.

Ty

**Comment by muhdsalm** [comment]
Sure.

**Comment by gen2brain** [comment]
@JupiterRider is probably related to `replace` in `go.mod`, sorry, I cannot check now.

**Comment by RednibCoding** [comment]
I have the same issue:
i ran: ```go get -v -u github.com/gen2brain/raylib-go/raygui```
With this result:
```go: github.com/gen2brain/raylib-go/raylib@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000```

**Comment by JupiterRider** [comment]
I provided a "Fix". 

The intention of @gen2brain was, to have raygui to always point to the latest version of raylib. But that didn't seem to work
