### ISSUE TITLE
How to always reference the latest package versions

### ISSUE THREAD

**Issue by JupiterRider** [gen2brain/raylib-go#246]
If the version of for example `github.com/gen2brain/raylib-go/raylib` changes, how can we make sure, that other packages like `github.com/gen2brain/raylib-go/examples` always use the latest version?

Is the any way instead telling the user to `go get -u -v all`?

**Comment by JupiterRider** [comment]
@gen2brain Maybe some kind of Github Action could do this automatically?
After a new Version has been published, it could automatically updated the dependencies in the other packages.

**Comment by gen2brain** [comment]
For local development there are workspaces, but they also have some limitations. Not really a fan of idea that github actions to update something automatically. When there is a new release it is easy to update modules.
