### ISSUE TITLE
Font setters and getters missing in raygui?

### ISSUE THREAD

**Issue by Wesbalt** [gen2brain/raylib-go#250]
Raygui has set and get functions for the current font, see this link:

https://github.com/raysan5/raygui/blob/master/src/raygui.h#L513

These are particularly useful for people looking to add more controls to raygui. Are there any plans to add these functions to the Go bindings? Thanks.

**Comment by JupiterRider** [comment]
@Wesbalt @gen2brain 
I added these two functions and made a pull request

**Comment by Wesbalt** [comment]
Thanks!
