### ISSUE TITLE
Loading Animations Problem

### ISSUE THREAD

**Issue by nicholasimon** [gen2brain/raylib-go#251]
Okay, so I am trying to load 3d model animations for the first time and get an error as in the image below, that is in the rmodels.go file at line 438 apparently. The model loads fine without animations and I can view it however as soon as I try and load the animations from the model then it returns the error below, I have tried with different models, all have the same problem. Might also be my code, which is at the end. If you are not too busy if you can take a look it would be great.

![image](https://user-images.githubusercontent.com/65644353/226993326-cb5cfabd-5510-4b7f-8177-cd3c4a6b7e0f.png)

So I looked in the rmodels.go file and this is the part that is there. Unfortunately my knowledge of coding is limited so not sure if something is wrong there.

```
// LoadModelAnimations - Load model animations from file
func LoadModelAnimations(fileName string) []ModelAnimation {
	cfileName := C.CString(fileName)
	defer C.free(unsafe.Pointer(cfileName))
	ccount := C.uint(0)
	ret := C.LoadModelAnimations(cfileName, &ccount)
	v := (*[1 << 24]ModelAnimation)(unsafe.Pointer(ret))[:int(ccount)]
	return v
}
```

My code is below for reference, maybe I am doing something wrong not sure 

```
type xmodel struct {
	model     rl.Model
	pos, scal rl.Vector3
	ro        float32
	anims     []rl.ModelAnimation
}

}
func makemodels() { 

	zmodel := xmodel{}

	zmodel.model = rl.LoadModel("models/Zombie.glb")
	zmodel.pos = rl.NewVector3(0, 0, 0)
	zmodel.scal = rl.NewVector3(0.5, 0.5, 0.5)
	zmodel.anims = rl.LoadModelAnimations("models/Zombie.glb")
	models = append(models, zmodel)

}
```

**Comment by JupiterRider** [comment]
Hey @nicholasimon ,

the raylib-go source is fine. 

Can you:
1. Be sure the path "models/Zombie.glb" is correct?
2. Does your model really contain animations?
3. Could you try a different format  (for example gltf or iqm)?
4. Did you make sure to call `rl.InitWindow` before even loading anything?

**Comment by nicholasimon** [comment]
Thanks for the reply, look definitely could be the code, just couldn't get it to work. I was just messing with 3D for the first time and was bugging me. OK, appreciate the help will go back to the code. Thanks again
