### ISSUE TITLE
Update to raylib v4.5

### ISSUE THREAD

**Issue by JupiterRider** [gen2brain/raylib-go#253]
Hey gen2brain,

could you create a new branch (called 4.5-dev or something)?
I am working on an update, but I don't want to make a pull request to the master.

There are many breaking changes.

Ty!

**Comment by gen2brain** [comment]
@JupiterRider Every new version has many breaking changes, they are just tagged with the version. Not sure why now there is a need for a new branch.

**Comment by JupiterRider** [comment]
Created a pull request #255 
This one only includes the new C sources, deletion of obsolete functions and the new rcamera module.

**Comment by gen2brain** [comment]
Ok, I tagged the v4.5.0, thanks for working on the update.
