### ISSUE TITLE
Update raygui

### ISSUE THREAD

**Issue by lambdcalculus** [gen2brain/raylib-go#262]
raygui has recently updated to v4.0 after having been on v3.6 for some time, while raylib-go uses raygui v3.5.

The v4.0 update has some breaking changes in the raygui API which will also require changes in the bindings. I can try to help with that if wanted.

**Comment by JupiterRider** [comment]
Hey @lambdcalculus,

isn't v3.6 the latest version? https://github.com/raysan5/raygui/releases


Anyhow. Help is always welcome :D 

raygui is just a binding. That means: Update the raylib.h, the raygui.h, run a 'go get -u -v all' to update the version of `github.com/gen2brain/raylib-go/raylib` and write your bindings inside raygui.go

**Comment by lambdcalculus** [comment]
Oh, it hasn't been released, oops, just been merged on master. Pardon my sleep-deprived self. Either way, it might be good to have the changes ready in a separate branch for when it does release.

I'll try to spare some time to do it, seems pretty straightforward.

**Comment by nomad-software** [comment]
raygui v4.0 is now released.

**Comment by gen2brain** [comment]
Raygui is updated in https://github.com/gen2brain/raylib-go/commit/4e92726a47c46f9605486760a6743c41bb38edbb.
