### ISSUE TITLE
Custom mesh generation

### ISSUE THREAD

**Issue by RugiSerl** [gen2brain/raylib-go#270]
Hello!

So I've been stuck for a while now and I can't figure out how to generate a custom mesh like the triangle in this example : https://github.com/raysan5/raylib/blob/2061bfc5e814dd4e2b5ff629cb02bef4c972e9f8/examples/models/models_mesh_generation.c#L147C2-L147C2

The thing is, the Mesh object in go contains the pointer to the array of vertices, normals, tangents instead of slices. I'm not very familiar with C but I was able to see the content of the array by doing :

```
mesh = rl.GenMeshCube(1, 1, 1)

vertices := unsafe.Pointer(mesh.Vertices)

size := unsafe.Sizeof(vertices)

for i := 0; i < int(mesh.VertexCount); i++ {
	fmt.Println(*(*float32)(unsafe.Pointer(uintptr(vertices) + size*uintptr(i))))

}
```

However, I don't know how to dynamically allocate array in Golang, it would require to use MemAlloc like in the example, so I was wondering if someone else got any way to do that.

**Comment by JupiterRider** [comment]
Hey @RugiSerl,

here's an example, how to create a custom mesh in Golang and the pitfalls you'll face:
https://github.com/gen2brain/raylib-go/issues/263

If you want to "convert" an C array into a go slice, you can use this:
https://pkg.go.dev/unsafe#Slice

**Comment by RugiSerl** [comment]
Thank you for the explanations. However I think I'll have to switch to another language to achieve this in a "clean" way.
Anyway have a good day :)
