### ISSUE TITLE
How to remove the console?

### ISSUE THREAD

**Issue by Cody-Green** [gen2brain/raylib-go#271]
I have found that you can compile with the flags:
-Wl,--subsystem,windows
Using GCC

I am using TDM-GCC-64 MinGW Command prompt to build from with
go build .

**Comment by RugiSerl** [comment]
Hello! 
You can try to add flag  -ldflags -H=windowsgui 
like this : 
`go build -ldflags -H=windowsgui`

**Comment by Cody-Green** [comment]
> Hello! You can try to add flag -ldflags -H=windowsgui like this : `go build -ldflags -H=windowsgui`

Worked like a charm!
Many thanks!!
