### ISSUE TITLE
The function `DrawBillboardPro` seems to be missing from this binding.

### ISSUE THREAD

**Issue by nomad-software** [gen2brain/raylib-go#272]
The function `DrawBillboardPro` seems to be missing from this binding. Can you add it please?

Reference: https://www.raylib.com/cheatsheet/cheatsheet.html

```
void DrawBillboardPro(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint); // Draw a billboard texture defined by source and rotation
```

**Comment by gen2brain** [comment]
@nomad-software I am on vacation. Sure, PR is welcome.

**Comment by nomad-software** [comment]
I've created a PR for this issue if you would like to take a look. Thanks.

https://github.com/gen2brain/raylib-go/pull/273
