### ISSUE TITLE
DisableCursor() doesn't work

### ISSUE THREAD

**Issue by sk-1197897** [gen2brain/raylib-go#275]
When I try to use rl.DisableCursor() it doesn't work.
I am running on Linux; go version 1.20.6

**Comment by gen2brain** [comment]
What exatctly doesn't work? That should just lock the cursor, do you have an example? You have functions to hide/show and disable/enable  i.e. lock/unlock cursor.

**Comment by sk-1197897** [comment]
package main

import (
	rl "github.com/gen2brain/raylib-go/raylib"
)

const (
	maxColumns = 20
)


func main() {
	rl.InitWindow(800, 450, "raylib [core] example - 3d camera first person")
	camera := rl.Camera3D{}
	camera.Position = rl.NewVector3(4.0, 2.0, 4.0)
	camera.Target = rl.NewVector3(0.0, 1.8, 0.0)
	camera.Up = rl.NewVector3(0.0, 1.0, 0.0)
	camera.Fovy = 60.0
	camera.Projection = rl.CameraPerspective

	heights := make([]float32, maxColumns)
	positions := make([]rl.Vector3, maxColumns)
	colors := make([]rl.Color, maxColumns)

	for i := 0; i < maxColumns; i++ {
		heights[i] = float32(rl.GetRandomValue(1, 12))
		positions[i] = rl.NewVector3(float32(rl.GetRandomValue(-15, 15)), heights[i]/2, float32(rl.GetRandomValue(-15, 15)))
		colors[i] = rl.NewColor(uint8(rl.GetRandomValue(20, 255)), uint8(rl.GetRandomValue(10, 55)), 30, 255)
	}
		rl.ToggleFullscreen()	
    LockCursor()

		rl.SetTargetFPS(60)
	for !rl.WindowShouldClose() {
		rl.UpdateCamera(&camera, rl.CameraFirstPerson) 
		rl.BeginDrawing()
		rl.DisableCursor()
		rl.ClearBackground(rl.RayWhite)

		rl.BeginMode3D(camera)
		rl.DrawPlane(rl.NewVector3(0.0, 0.0, 0.0), rl.NewVector2(32.0, 32.0), rl.LightGray) 
		rl.DrawCube(rl.NewVector3(-16.0, 2.5, 0.0), 1.0, 5.0, 32.0, rl.Blue)               
		rl.DrawCube(rl.NewVector3(16.0, 2.5, 0.0), 1.0, 5.0, 32.0, rl.Lime)                
		rl.DrawCube(rl.NewVector3(0.0, 2.5, 16.0), 32.0, 5.0, 1.0, rl.Gold)                

		
		for i := 0; i < maxColumns; i++ {
			rl.DrawCube(positions[i], 2.0, heights[i], 2.0, colors[i])
			rl.DrawCubeWires(positions[i], 2.0, heights[i], 2.0, rl.Maroon)
		}
		
		rl.EndMode3D()

		rl.DrawRectangle(10, 10, 220, 70, rl.Fade(rl.SkyBlue, 0.5))
		rl.DrawRectangleLines(10, 10, 220, 70, rl.Blue)

		rl.DrawText("First person camera default controls:", 20, 20, 10, rl.Black)
		rl.DrawText("- Move with keys: W, A, S, D", 40, 40, 10, rl.DarkGray)
		rl.DrawText("- Mouse move to look around", 40, 60, 10, rl.DarkGray)

		rl.EndDrawing()
	}

	rl.CloseWindow()
}

func LockCursor(){
    rl.DisableCursor()
}

**Comment by sk-1197897** [comment]
So  basically when i run it it opens a window and when i click inside of it the cursor disappear but still seems to only move with the confines of the screen instead of being able to look anywhere

**Comment by gen2brain** [comment]
Sorry, no time to test currently, but you have rl.DisableCursor in main loop, that looks wrong, you don't want that executed for every frame.

**Comment by sk-1197897** [comment]
Oh yeah. I forgot to edit that out. That is the remains of when I was testing if I was using the DisableCursor wrong, it doesn´t work in any of my projects. I also run on Debain 11 if that helps

**Comment by gen2brain** [comment]
I just tested, and I don't see a problem. The cursor is locked to the window and is not shown until the window/program is closed, mouse movement still works. What do you expect to see instead? The name of the distro doesn't help, but maybe it will help if you can tell do you use X11 or Wayland, I tested on X11.

**Comment by sk-1197897** [comment]
And sometimes it does lock in place like it's supposed to but most of the time it just acts like rl.HideCursor()

**Comment by sk-1197897** [comment]
It also doesn't work when I build it as an executable

**Comment by sk-1197897** [comment]
Wait nevermind I seemed to have fixed it by using the command sudo apt autoremove. But thanks for helping anyway.
