### ISSUE TITLE
UpdateAudioStream and SetAudioStreamCallback

### ISSUE THREAD

**Issue by maxpoletaev** [gen2brain/raylib-go#279]
There are currently two methods of updating audio streams in vanilla raylib: pushing it with `UpdateAudioStream` or setting a callback with `SetAudioStreamCallback` so that raylib can request new samples once the buffer is empty. I see that current raylib [examples](https://github.com/raysan5/raylib/blob/master/examples/audio/audio_raw_stream.c#L73) rely on SetAudioStreamCallback. However, I've noticed that the latter isn't yet implemented in raylib-go.

I'm curious if there's any significant difference between these two? I'm currently facing some weird audio synchronization issues and am wondering if the callback approach might be better somehow. If so, do you think it would be difficult to add a wrapper for `SetAudioStreamCallback` to raylib-go?

**Comment by gen2brain** [comment]
The callbacks in Go can be a real pain, and there are not many places in Raylib where they are used. If there is not an important reason to implement one I would prefer not to include it. If there is any significant difference between these two can tell us someone who can test both ways in some test example.

**Comment by gen2brain** [comment]
SetAudioStreamCallback added in https://github.com/gen2brain/raylib-go/commit/9f257fc589fbf828d40b0d722df43d577af0e80a. It is not tested, if there are issues please report.
