### ISSUE TITLE
How to access multiple materials?

### ISSUE THREAD

**Issue by Gamerfiend** [gen2brain/raylib-go#280]
Hi there! I was looking at an old project I had that used [https://github.com/Lachee/raylib-goplus](url), I was taking a look at updating it to use your bindings as that one is no longer updated :) 

Most things can be resolved easily however one I am having issues with

```go
	tileWall.Materials[0].Maps[r.MapOcclusion].Texture = r.LoadTexture(uriPath + "ao.png")
	tileWall.Materials[0].Maps[r.MapRoughness].Texture = r.LoadTexture(uriPath + "roughness.png")

	tileWall.Materials[0].Shader = tileModel.Materials[0].Shader
	tileWall.Materials[1].Shader = tileModel.Materials[0].Shader
```

I'd be unable to access the the material because 
```
Invalid operation: 'tileWall.Materials[0]' (type '*Material' does not support indexing
```

How is the way around this?

**Comment by dominik-zeglen** [comment]
I was surprised to find out `Model.Materials` and `Model.Meshes` actually return one object instead of array. Or am I missing something?

**Comment by gen2brain** [comment]
@dominik-zeglen PR is welcome.

**Comment by Gamerfiend** [comment]
@gen2brain I'm just trying to figure out the expected behavior :) Is access to one Material only the expected behavior with this library? :)

**Comment by gen2brain** [comment]
These are bindings, expected is to behave the same as in C raylib, of course, it cannot be exactly the same. If something is wrong help is welcome.

**Comment by Gamerfiend** [comment]
Right I agree with that, and I am happy to help and give a PR but I literally don't know *how* to access to the multiple material is what I am asking.

**Comment by dominik-zeglen** [comment]
This is unfortunately the same case for me - I'd do it myself but cgo and bindings are just not my strong side

**Comment by Gamerfiend** [comment]
@unklnik That will set the textures for the first material only. The problem here is that `Materials` should be an array of multiple materials and not a pointer to only one material. The current solution would be to send a PR to fix this issue, which I hope to do :)

**Comment by dominik-zeglen** [comment]
I've tried making `Model.Meshes` an array but I failed horribly and I'm out of ideas:

```go
// Model is struct of model, meshes, materials and animation data
type Model struct {
	// Local transform matrix
	Transform     Matrix
	MeshCount     int32
	MaterialCount int32
	Meshes        []*Mesh
	Materials     *Material
	MeshMaterial  *int32
	BoneCount     int32
	Bones         *BoneInfo
	BindPose      *Transform
}


// newModelFromPointer - Returns new Model from pointer
func newModelFromPointer(ptr unsafe.Pointer) Model {
	model := *(*Model)(ptr)
	model.Meshes = model.Meshes[:model.MeshCount]

	return model
}
```

This results in a segmentation fault when calling `SetMaterialTexture`. After looking into debugger I saw meshes are not properly instantiated so i've tried doing it this way:

```go

// Model is struct of model, meshes, materials and animation data
type Model struct {
	// Local transform matrix
	Transform     Matrix
	MeshCount     int32
	MaterialCount int32
	Meshes        []*Mesh
	Materials     *Material
	MeshMaterial  *int32
	BoneCount     int32
	Bones         *BoneInfo
	BindPose      *Transform
}

type ModelFromPtr struct {
	// Local transform matrix
	Transform     Matrix
	MeshCount     int32
	MaterialCount int32
	Meshes        []Mesh
	Materials     *Material
	MeshMaterial  *int32
	BoneCount     int32
	Bones         *BoneInfo
	BindPose      *Transform
}

// newModelFromPointer - Returns new Model from pointer
func newModelFromPointer(ptr unsafe.Pointer) Model {
	model := *(*ModelFromPtr)(ptr)
	meshes := make([]*Mesh, model.MeshCount)
	for i := int32(0); i < model.MeshCount; i++ {
		meshes[i] = &model.Meshes[i]
	}

	return Model{
		Transform:     model.Transform,
		MeshCount:     model.MeshCount,
		MaterialCount: model.MaterialCount,
		Meshes:        meshes,
		Materials:     model.Materials,
		MeshMaterial:  model.MeshMaterial,
		BoneCount:     model.BoneCount,
		Bones:         model.Bones,
		BindPose:      model.BindPose,
	}
}
```

But it results in the same error though meshes seem to be valid now. I believe resolving this problem will lead to resolving `Model.Materials` issue too.

**Comment by Gamerfiend** [comment]
@dominik-zeglen If you view here another attempt at raylib bindings for go that are outdated. [raylib-goplus](https://github.com/Lachee/raylib-goplus/blob/master/raylib/models.go) They solved it by having a fixed sized array for meshes to start I believe, as raylib has a hardcoded limit.

**Comment by JupiterRider** [comment]
To convert a c-array to a go-slice you can use the function `unsafe.Slice`: https://pkg.go.dev/unsafe#Slice
Here is an example:
```golang
// ...
model := rl.LoadModel("lifebelt.gltf")

materials := unsafe.Slice(model.Materials, model.MaterialCount)
rl.SetMaterialTexture(&materials[1], rl.MapDiffuse, rl.LoadTexture("sprite.png"))
// ...
```

**Comment by JupiterRider** [comment]
> @dominik-zeglen If you view here another attempt at raylib bindings for go that are outdated. [raylib-goplus](https://github.com/Lachee/raylib-goplus/blob/master/raylib/models.go) They solved it by having a fixed sized array for meshes to start I believe, as raylib has a hardcoded limit.

Would that be a performance / memory issue? The array size is 268435456:
https://pkg.go.dev/github.com/lachee/raylib-goplus/raylib#MaxModelMeshes

**Comment by dominik-zeglen** [comment]
I feel like you're smarter than me because I honestly don't have any idea what I'm doing or what you're talking about

![image](https://github.com/gen2brain/raylib-go/assets/6833443/87d40776-10c9-4b8b-ba4e-bad391caaaa0)

**Comment by JupiterRider** [comment]
@gen2brain 
What do you think? 

There are two options:
1. Convert the pointers into a fixed size array (like raylib-goplus does): https://pkg.go.dev/github.com/lachee/raylib-goplus/raylib#Model
2. Leave the structs as they are and provide a getter-method using unsafe.Slice internally. 

I personally prefer the second option. I've done  the same in rres as well: https://github.com/gen2brain/raylib-go/blob/master/rres/rres.go#L67

**Comment by gen2brain** [comment]
@JupiterRider Yes, the second option is better.

**Comment by JupiterRider** [comment]
@Gamerfiend You can now do this:
`tileWall.GetMaterials()[0].GetMap(r.MapOcclusion).Texture = r.LoadTexture(uriPath + "ao.png")`

**Comment by gen2brain** [comment]
@JupiterRider Thanks! I am closing the issue.
