### ISSUE TITLE
external/glfw/src/context.c: No such file or directory

### ISSUE THREAD

**Issue by nomad-software** [gen2brain/raylib-go#281]
I'm trying to build a project using this library but i'm running into issues.
I'm using Ubuntu 22.04.3 LTS - 64-bit (X11)

```
go build main.go
# github.com/gen2brain/raylib-go/raylib
vendor/github.com/gen2brain/raylib-go/raylib/cgo_linux.go:7:10: fatal error: external/glfw/src/context.c: No such file or directory
    7 | #include "external/glfw/src/context.c"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Am I missing a dependency? I've installed all the packages mentioned here: https://github.com/gen2brain/raylib-go#ubuntu
Any idea what is going wrong here?
Thanks.

**Comment by gen2brain** [comment]
You are using vendoring. It will copy only some Go files and will miss all important files. Either do not use vendor or copy manually missing files.

**Comment by nomad-software** [comment]
Ah, that's the problem! :facepalm: Thanks!
