### ISSUE TITLE
  SetExitKey(KEY_NULL);       // Disable KEY_ESCAPE 

### ISSUE THREAD

**Issue by unklnik** [gen2brain/raylib-go#287]
Hi, just want to check, this is in one of the examples on the Raylib site that I am converting to Go. Anyway, there does not appear to be a KEY_NULL in the Go Bindings that I can find. Is there one? How would I go about adding one if there isn't?

Basically   `SetExitKey(KEY_NULL); `  allows you to do other things (create a window etc) before closing the program by setting the key to nothing.

**Comment by JupiterRider** [comment]
@unklnik Thanks for reporting. I provided a pull request #288 to fix this "issue"
