### ISSUE TITLE
Windows MSYS2 -lOpenAL32 compilation error

### ISSUE THREAD

**Issue by egonelbre** [gen2brain/raylib-go#3]
With MSYS2 by following the instructions the result did not compile. I needed to change in `cgo_windows_static.go`  and `cgo_windows.go` from `-lOpenAL32` to `-lopenal`. I did a clean MSYS2 setup to verify.

Not sure whether this was a typo, some differences in how MSYS2 was installed or some left-over dll-s that allowed it to work. 

_Error message:_
```
# github.com/gen2brain/raylib-go/raylib
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lOpenAL32
collect2.exe: error: ld returned 1 exit status
```

**Comment by gen2brain** [comment]
Thanks, you are right, it was a left-over. I tried with mingw in windows and in linux, and there are OpenAL32, openal32 and openal. Not sure what is the best thing to do here to support all cases.

**Comment by egonelbre** [comment]
Forgot to close, this exact issue was fixed with PR.
