### ISSUE TITLE
Cannot get Hybrid Render Example to work rlgl.h LoadTextureDepth function missing

### ISSUE THREAD

**Issue by unklnik** [gen2brain/raylib-go#301]
I am trying to port the Hybrid Render example from https://www.raylib.com/examples/shaders/loader.html?name=shaders_hybrid_render

However, I am stuck, as the function _rl.LoadTextureDepth_ function is not available. I asked on Discord and was told this is because **rlgl.h** is not available. I don't need it desperately myself however did want to point it out that it is missing if you were not aware. Unless it is available and I don't know how to use it. Anyway, just wanted to let you know, the discord chat image is below.

![image](https://github.com/gen2brain/raylib-go/assets/146096950/0ea86136-fc44-40f4-a314-67e0cc411cf6)

**Comment by gen2brain** [comment]
I was already against including any of rlgl functions. If someone needs to add or wants to maintain that part I will accept a PR.

**Comment by gen2brain** [comment]
@unklnik LoadTextureDepth is added in https://github.com/gen2brain/raylib-go/commit/d269b291f22994bddbeb80c2ecbd631eff521a07.

**Comment by unklnik** [comment]
Thanks that is great
