### ISSUE TITLE
Cannot run in windows; libmcfgthread-1.dll was not found

### ISSUE THREAD

**Issue by checkm4ted** [gen2brain/raylib-go#309]
After successfully building the game I tried running it in Windows Sandbox to see if it required any deps. I cannot run because it cannot find libmcfgthread-1.dll
![image](https://github.com/gen2brain/raylib-go/assets/146487129/f9976c6f-f4c4-4115-b5d0-f8eb13bb32a5)

**Comment by gen2brain** [comment]
Not related to raylib/raylib-go. That has everything to do with your toolchain, i.e. old MinGW, broken install, etc. You didn't mention what C compiler are you using.

**Comment by gen2brain** [comment]
You can also compile a static binary, i.e.:
```
$ CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -ldflags "-s -w '-extldflags=-static'"
$ file basic_window.exe
basic_window.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows, 11 sections
```
Anyway, even without `-extldflags=-static` the binary should work without dependencies, try using TDM-GCC, in Windows that one always just worked for me.
