### ISSUE TITLE
PureGo Example or Readme page

### ISSUE THREAD

**Issue by unklnik** [gen2brain/raylib-go#316]
Not an issue however just wondering, in terms of using PureGo, there is little information on how to go about it and an example would be good. I have no idea how to switch from using a C compiler to PureGo and how to build a simple program/game. @JupiterRider it is great work and I am sure you are busy however if you have time an example or a more detailed Readme page would be great.

**Comment by unklnik** [comment]
Just to add, this is not urgent or anything, just for users like me who don't know exactly how to implement PureGo builds it would be helpful to have a little more information available.

**Comment by gen2brain** [comment]
@unklnik You just compile with CGO_ENABLED=0. I added a hint in README.

**Comment by unklnik** [comment]
OK thanks will take a look later today. I just wanted to point out that many users (like me) don't have nearly as much knowledge as  yourself or @JupiterRider so we don't know how to implement things like this as easily.

**Comment by unklnik** [comment]
Sorry again, just not understanding, must I download the Raylib package using this command _CGO_ENABLED=0 go get -v -u github.com/gen2brain/raylib-go/raylib_ and then build with the .dll file?

**Comment by gen2brain** [comment]
No, you just build e.g., some example with `CGO_ENABLED go build`, and that example will panic unless it finds raylib.dll.

**Comment by unklnik** [comment]
OK so I am on Windows 10 and in command prompt that does not work

![image](https://github.com/gen2brain/raylib-go/assets/146096950/023a0078-4d46-45f1-904c-924ed5c6735f)

**Comment by gen2brain** [comment]
That is an environment variable, so however that is used on Windows you must configure it, maybe it needs `""`, or `set` command is used, no idea, I am not a Windows user, but every user should know how to set temporary or globally some ENV.

The point here is, for example, in Linux, I can build the example for Windows just by using `GOOS=windows go build`, before this change I needed A MinGW C compiler, for every platform you need toolchain/compiler. The downside is that binary is not self contained, it requires `raylib.dll` in current dir, or somewhere globally.

**Comment by unklnik** [comment]
OK will do some research later and work it out thanks appreciate the help. If I work it out can I write a small addition to the README for Windows users to get it working and create a PR?

**Comment by gen2brain** [comment]
There is now already a hint about `CGO_ENABLED=0`, I would not want some large manuals in the main README for something trivial, but if you see something of great importance, sure, why not. For example, how do you change GOOS when you want on Windows, it works the same way.

**Comment by unklnik** [comment]
Found the answer must set go environment variables `go env -w CGO_ENABLED=0 ` and then it works, however it doesn't compile because too many things are missing

![image](https://github.com/gen2brain/raylib-go/assets/146096950/ae7549ab-1b4a-40a1-8282-cd8c49fc85b1)

**Comment by unklnik** [comment]
OK got it thanks

**Comment by gen2brain** [comment]
You probably are not using the latest raylib-go.

**Comment by gen2brain** [comment]
Btw. `go env -w` will write that change permanently to file, i.e. will set default, not sure if that is what you want, try also with `"CGO_ENABLED=0"`.

**Comment by rocktavious** [comment]
@unklnik - did you get this working?  @gen2brain i get the same errors when i
```
CGO_ENABLED=0 go build .
```
i get
```
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:196:27: undefined: GetMouseDelta
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:220:56: undefined: GetFrameTime
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:226:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:229:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:232:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:235:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:238:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:241:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:246:8: undefined: IsGamepadAvailable
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:248:29: undefined: IsMouseButtonDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20231230150416-17ce08145200/rcamera.go:248:29: too many errors

```

**Comment by gen2brain** [comment]
@rocktavious Are you on Windows?

**Comment by unklnik** [comment]
@rocktavious Yes, however you need to open command prompt/shell and then enter this `go env -w CGO_ENABLED=0` and it should work. Basically, as far as I understand it disables the CGO compiler. Just remember to set it back to `go env -w CGO_ENABLED=1` when you are done

**Comment by unklnik** [comment]
See this previous PR here https://github.com/gen2brain/raylib-go/pull/317/commits/d9b04a8ac1ac25b2e31056eaf4cd55243fcf9cc8
