### ISSUE TITLE
Arch Linux

### ISSUE THREAD

**Issue by AxewBoTX** [gen2brain/raylib-go#319]
I am using Arch on WSL2 on Windows 11 and I wanted to make a game in go. 
Can you provide me on the things that I should do or install in order to get raylib-go to work for me?
I have tried doing the simple way that is given on the README but when I run `go run main.go` it just keeps on going forever and nothing pops up. I checked the code 3 times and kept the program running for half an hour but nothing opened. 
Consider helping me.
Thanks

**Comment by gen2brain** [comment]
No idea, does WSL actually support OpenGL? Can you run at least X11 GUI apps? You better ask for support on WSL official channels, not here. Also, I am not sure why you want to go this route. Why not just use Windows? Creating a game needs a lot of time, and compiling for all platforms you want needs one day or a couple of minutes. Also, please use `go build`, does it work? Why use `go run`? Go is not interpreted language.

**Comment by AxewBoTX** [comment]
I have used `go build`, when I run the executable file, still nothing shows up and there is nothing in the terminal too.

Yes WSL support OpenGL, I have used node binding for raylib and it still works but the go one doesnt.

I don't like the way windows file system works but I need it for work and study so I just WSL.

**Comment by gen2brain** [comment]
Sorry, nothing that I can do here. There is nothing special or unusual that Go bindings does here.

**Comment by JupiterRider** [comment]
@AxewBoTX 
The first build can take up to several seconds or minutes, depending on the CPU speed.
This is because raylib-go is statically linked when using cgo. It takes some time to compile the C code.

**Comment by AxewBoTX** [comment]
well half an hour is enough time ig
