### ISSUE TITLE
invalid flag in #cgo CFLAGS: -fgnu89-inline

### ISSUE THREAD

**Issue by Pienkaito** [gen2brain/raylib-go#32]
Everytime I try to build the raylib [core] example I get this issue.
`go build github.com/gen2brain/raylib-go/raylib: invalid flag in #cgo CFLAGS: -fgnu89-inline`

Using Go 1.10 with IntelliJ IDEA 2017.1.5 with CGO support enabled

**Comment by gen2brain** [comment]
It seems now there are whitelist/blacklist of CFLAGS, not sure for now what are restrictions, and why, but if you are sure what flags needs to be changed/removed patched are welcomed.

**Comment by gen2brain** [comment]
This is really stupid, something similar happened for another project to me yesterday, I hope this blacklisting is just temporary, and someone will return this to sane state.

**Comment by Pienkaito** [comment]
Unfortunately I'm in the dark if it comes to CFLAGS and such. I've recently started looking into GO in general.
However I could build the example by reverting to an older version of GO.

`go version go1.9.3 windows/amd64`

**Comment by qarlosh** [comment]
You can set an environment variable to allow using the invalid flag.
In Linux: `export CGO_CFLAGS_ALLOW=-fgnu89-inline`

I just had the same problem, and after setting this variable now I can `go build`raylib successfully.

There is more information here:
https://github.com/golang/go/wiki/InvalidFlag

**Comment by gen2brain** [comment]
I would not want to add such requirement, `go build` should just work. I cannot test currently, but can it build with just `-std=gnu99` and without `-fgnu-inline` ? I don't understand clearly what it says here https://gcc.gnu.org/onlinedocs/gcc/Inline.html .

"GCC implements three different semantics of declaring a function inline. One is available with -std=gnu89 or -fgnu89-inline or when gnu_inline attribute is present on all inline declarations, another when -std=c99, -std=gnu99 or an option for a later C version is used (without -fgnu89-inline), and the third is used when compiling C++."

**Comment by qarlosh** [comment]
I tried removing the `-fgnu89-inline` flag from source and it compiled successfully... but I have no idea about the performance implications.
Anyway, if it is appropiate using this flag, it should be requested to be added to the whitelist by creating a new issue in https://github.com/golang/go.

**Comment by Pienkaito** [comment]
Thanks to the hint from qarlosh, I could also compile it in Windows by setting an environment variable called `CGO_CFLAGS_ALLOW` with its value `-fgnu89-inline`.
Now it works with the latest go library. But I would also like to know what happens if `-fgnu89-inline` is removed.

**Comment by gen2brain** [comment]
`-fgnu89-inline` is removed from CFLAGS, it seems it is not that important, see https://github.com/raysan5/raylib/issues/478 .
