### ISSUE TITLE
Window Scaling for DESKTOP

### ISSUE THREAD

**Issue by Pienkaito** [gen2brain/raylib-go#33]
I hope it's okay to ask here. Is there a way to define a seperate size for rendering and actual screen size?
Like let's say my game runs at 240x160. I increase the window size, so the graphics will adapt relative to that. But the game still thinks it's at 240x160.

**Comment by raysan5** [comment]
Sure! Just use a `RenderTexture2D target` to do the render at 240x160 and then render that `target.texture` to window size. You can find an [example here](https://github.com/gen2brain/raylib-go/blob/master/examples/shaders/custom_uniform/main.go).

**Comment by Pienkaito** [comment]
I think I nearly have it. My only problem right now would be "RenderTexture2d rendered upside down" issue, which was addressed in the forums.

Because of how DrawTextureRec works differently as I expected, I opted to use DrawTextureEx instead and it works perfectly for my intended use. But the problem is that I can't adjust the rendering height.

I could solve it by rendering it twice on two different textures, but perhaps there is another (and better) method.

**Comment by raysan5** [comment]
> But the problem is that I can't adjust the rendering height.

I don't understand exactly what you mean, could you post some example of what are you trying to accomplish?

**Comment by Pienkaito** [comment]
In your example, you flipped the texture by its y-axis like so.
```
// NOTE: Render texture must be y-flipped due to default OpenGL coordinates (left-bottom)
raylib.DrawTextureRec(target.Texture, raylib.NewRectangle(0, 0, target.Texture.Width, -target.Texture.Height), raylib.NewVector2(0, 0), raylib.White)
```
I'm using this function to scale my output
`raylib.DrawTextureEx(target.Texture, raylib.NewVector2(0, 0), 0, float32(scale), raylib.White)`

My texture can be scaled accordingly by using this function, but the texture itself is upside down.
So in order to fix this I've done the following.

```
raylib.BeginTextureMode(target)
{
	//Draw stuff onto the texure
}
raylib.EndTextureMode()

raylib.BeginTextureMode(targetflipped)
{
	raylib.DrawTextureRec(target.Texture, raylib.NewRectangle(0, 0, target.Texture.Width, target.Texture.Height), raylib.NewVector2(0, 0), raylib.White)
}
raylib.EndTextureMode()

raylib.DrawTextureEx(targetflipped.Texture, raylib.NewVector2(0, 0), 0, float32(scale), raylib.White)
```

It feels sort of redundant and I was wondering if there's a better way for doing this.

**Comment by nehpe** [comment]
@Pienkaito yeah, that is pretty inefficient. I recommend using DrawTexturePro --

```golang
raylib.DrawTexturePro(target.Texture, rl.NewRectangle(0, 0, target.Texture.Width, -target.Texture.Height), rl.NewRectangle(0, 0, target.Texture.Width, target.Texture.Height), rl.Vector2{0, 0}, 0, rl.White)
```
