### ISSUE TITLE
Why no releases?

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#331]
How come `raylib-go` is using tags instead of releases? I am not a Git/GitHub expert, so there might be a very good reason for this that I don't understand.

My go.mod file looks like this:

  require github.com/gen2brain/raylib-go/raylib v0.0.0-20231118131254-fed470e4458f

But wouldn't it be better/simpler if it looked like this (matching Raylib version):

  require github.com/gen2brain/raylib-go/raylib v5.0.0

Anyway, this is of course not a deal breaker, just something I am wondering about...

**Comment by gen2brain** [comment]
That has nothing to do with tags vs releases. It is like that because of sub dir.
