### ISSUE TITLE
cgo-builtin-prolog:1: stddef.h: No such file or directory

### ISSUE THREAD

**Issue by dabla1710** [gen2brain/raylib-go#335]
I'm under windows and followed the instructions and installed MinGW-w64 using the installer:

https://github.com/niXman/mingw-builds-binaries?tab=readme-ov-file

then downloaded the raylib zip 

https://github.com/raysan5/raylib/releases

and extracted the raylib.dll to Windows/System32/ and also in my project root.
Tried 2 different zip files:

raylib-5.0_win64_mingw-w64.zip
raylib-5.0_win64_msvc16.zip

Both do not seem to work when using the example and end up with the same error:

go run main.go

# runtime/cgo
cgo-builtin-prolog:1: stddef.h: No such file or directory

also gcc is in path (also using it for c++):

gcc -v 
Using builtin specs.
gcc version 2.95 19990728 (release)

I'm not experienced with cgo or that library so I do not know why this does occure.
Also I cannot find a cgo or raylib related issue online 

Help would be appreciate. Thanks

**Comment by gen2brain** [comment]
You either need a C compiler or use the alternative method that only works in Windows. I suggest you first solve the cgo in Windows, as obviously, it cannot find the header files, where is your stddef.h? If it wants this then you are using CGO_ENABLED=1, when cgo is disabled it will use the DLL.

**Comment by Gamerfiend** [comment]
It seems you already installed a compiler? For what it's worth, this one linked on the README, https://jmeubank.github.io/tdm-gcc/, worked very well for me with no configuration.

**Comment by dabla1710** [comment]
> You either need a C compiler or use the alternative method that only works in Windows. I suggest you first solve the cgo in Windows, as obviously, it cannot find the header files, where is your stddef.h? If it wants this then you are using CGO_ENABLED=1, when cgo is disabled it will use the DLL.

Actually I do have multiple stddef.h files, mostly zig related.
The others are in:

"\msys64\ucrt64\include\stddef.h"
"\mingw64\lib\gcc\x86_64-w64-mingw32\13.2.0\include\stddef.h"
"\mingw64\x86_64-w64-mingw32\include\stddef.h"
"\msys64\ucrt64\lib\gcc\x86_64-w64-mingw32\13.2.0\include\stddef.h"


Maybe im blind but disabling cgo was a a pain, because I could not find one resource showing a example how to actually set it.
For anyone encountering that problem in the future, use:

go env -w CGO_ENABLED=0 // set the enviroment variable
go env // show enviroment variables

Everything is working as expected now, thank you !

Also I tried the raylib bindings on linux yesterday. Everything works smoothly there. Thanks for you work :)


> It seems you already installed a compiler? For what it's worth, this one linked on the README, https://jmeubank.github.io/tdm-gcc/, worked very well for me with no configuration.

I will try that as well, thanks for the advice
