### ISSUE TITLE
`<nil>` body from `physics.GetBodies()`

### ISSUE THREAD

**Issue by a-alhusaini** [gen2brain/raylib-go#336]
When looping through the objects returned from `physics.GetBodies()` I am getting `nil` values for quite a few bodies. Is this normal?

Here is the code:
```go
	for !rl.WindowShouldClose() {
		physics.Update()

		timeAccumilation += float64(rl.GetFrameTime())

		if timeAccumilation > float64(1.0) {
			physics.NewBodyCircle(rl.NewVector2(300, 0), 24.0, 1.0)
			timeAccumilation = 0.0
		}

		rl.BeginDrawing()

		for _, body := range physics.GetBodies() {
			if body != nil {
				rl.DrawCircle(int32(body.Position.X), int32(body.Position.Y), 32.0, rl.Yellow)
			}
		}

		rl.ClearBackground(rl.Black)
		rl.DrawText("Congrats! You created your first window!", 190, 200, 20, rl.White)

		rl.EndDrawing()
	}
```

Remove the line `if body != nil` and you end up getting a nil error.

Sorry if this isn't the right place to post. This seemed like nonstandard behaviour so I thought it might be something to do with the bindings.

System details
OS: MacOS 1.14
Processor: M1

**Comment by JupiterRider** [comment]
@a-alhusaini 
This is the only place. The physics package is not a binding, it's a rewrite in go.

How many bodies do you get? 64?
That's the code:

Line 154:
```golang
// Physics bodies pointers array
bodies [64]*Body
```

Line 527:
```golang
// GetBodies - Returns the slice of created physics bodies
func GetBodies() []*Body {
	return bodies[:]
}
```

Maybe this is intended or we could do this:
```golang
func GetBodies() []*Body {
	return bodies[:bodiesCount]
}
```

@gen2brain: What do you think?

**Comment by gen2brain** [comment]
I don't remember this code, but I don't see anything wrong in checking if the pointer is nil, any pointer can be nil? But, sure, if that will help with not opening new issues I am for it.

**Comment by a-alhusaini** [comment]
Well, for me, it just seemed like odd behaviour that immediately raised a few questions in my mind: Is the physics library losing track of my objects? Are they getting deleted? Why does.the array have nils in it?

Oh, and what happens if we exceed the 64 body limit? 

These thoughts are what lead me to open this issue.. So I guess only returning  the actual bodies instead of the entire slice is better. Less issues and more performance since you don't need to check if an item is nil on every frame.

**Comment by gen2brain** [comment]
@a-alhusaini Sure, thanks for opening the issue, I don't think there are a lot of Go physics/physac users so feedback is always welcome.
