### ISSUE TITLE
Request to Expose Additional Compute Shader and SSBO Management Functions in raylib-go

### ISSUE THREAD

**Issue by shellfu** [gen2brain/raylib-go#343]
During the development process, I encountered a limitation within raylib-go concerning compute shaders and Shader Buffer Storage Object (SSBO) management. The raylib C library includes a set of functions for compute shader management and SSBOs, which are crucial for advanced rendering and computation tasks. However, these functions are not exposed in the raylib-go bindings, which limits the capabilities that can be leveraged in Go-based projects.

The missing functions are as follows [Raylib C rlgl.h](https://github.com/raysan5/raylib/blob/master/src/rlgl.h#L737-L748):

    Compute Shader Management:
        rlLoadComputeShaderProgram(unsigned int shaderId)

    Shader Buffer Storage Object (SSBO) Management:
        rlLoadShaderBuffer(unsigned int size, const void *data, int usageHint)
        rlUnloadShaderBuffer(unsigned int ssboId)
        rlUpdateShaderBuffer(unsigned int id, const void *data, unsigned int dataSize, unsigned int offset)
        rlBindShaderBuffer(unsigned int id, unsigned int index)
        rlReadShaderBuffer(unsigned int id, void *dest, unsigned int count, unsigned int offset)
        rlCopyShaderBuffer(unsigned int destId, unsigned int srcId, unsigned int destOffset, unsigned int srcOffset, unsigned int count)

These functions are essential for my current project, and their inclusion in raylib-go would greatly enhance its capabilities, allowing for more complex and compute-intensive graphics operations.

**Proposed Solution**

I propose the addition of bindings for these functions in raylib-go, enabling Go developers to utilize the full spectrum of raylib's functionality. This enhancement would not only benefit my project but also the wider community of developers who rely on raylib-go for game development and other graphical applications.

**Impact**

The inclusion of these functions would significantly expand the scope of projects that can be developed with raylib-go, especially those requiring advanced GPU computations and shader manipulations.

**Comment by shellfu** [comment]
Will be closed by #344

**Comment by gen2brain** [comment]
Please, leave it open. Now there is inconsistency between cgo and purego.

**Comment by shellfu** [comment]
:+1: 

I'll take a look at the inconsistency after I get off work and see what can be done about it.

**Comment by shellfu** [comment]
Closed by #345 for purego
