### ISSUE TITLE
Question (not issue) - Should there not be a link to the Raylib Discord in the Readme?

### ISSUE THREAD

**Issue by unklnik** [gen2brain/raylib-go#347]
I have been thinking, not everyone is aware there is a Raylib Discord, with a channel for Raylib-Go (https://discord.com/channels/426912293134270465/435849658695286784) and it would make sense to link to it in the Readme IMO. This would mean less stupid questions would be opened as Issues on GitHub (saving you time) as people would often ask on Discord and it would make more people aware of the Discord Channel.

Didn't want to open a PR without first asking whether you think this is a good idea or not.

**Comment by gen2brain** [comment]
Yes, nice idea. Please send a PR, not sure where is the best though, maybe in the section where there are links for docs and examples.
