### ISSUE TITLE
Try to use raylib gui but go fail to buid

### ISSUE THREAD

**Issue by yatagarasu25** [gen2brain/raylib-go#349]
When I import raygui library with command `go get -v -u github.com/gen2brain/raylib-go/raygui` it kind build ok, but when I import raygiu in my program I get strange error

`imports github.com/gen2brain/raylib-go/raygui: build constraints exclude all Go files in C:\Users\yatag\go\pkg\mod\github.com\gen2brain\raylib-go\raygui@v0.0.0-20240125111008-83d871a38f28 (exit status 1)`

Why? How to fix that? I am noob in go package management
But is it ok to use such versions ? does go parse them correctly?

**Comment by gen2brain** [comment]
You probably are trying to use it with CGO_ENABLED=0, so set it to1. You are not trying to cross-conpile maybe? Please, send all info, so I don't need to guess what you are doing.

**Comment by yatagarasu25** [comment]
No, I am just building on windows for windows. Idk about CGO_ENABLED=0 i am not actively setting it anywhere

**Comment by yatagarasu25** [comment]
Can raygui be used in purego way? I should build a dll for it myself? or it will not work that way?

**Comment by yatagarasu25** [comment]
Yes, thank you. It works with CGO_ENABLED=1 now.
If anybody have no idea just install mingw from chocolately and use `go env -w CGO_ENABLED=1` to set the var.
