### ISSUE TITLE
Raspberry PI example not compiling

### ISSUE THREAD

**Issue by Pienkaito** [gen2brain/raylib-go#35]
Welp, wasted a day on this.

I tried to compile the RPI example and followed the guide. The installation went fine, but the compiler throws me this error.

```
# github.com/gen2brain/raylib-go/raylib
In file included from /usr/local/vc/include/interface/vcos/vcos.h:118:0,
                 from /usr/local/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /usr/local/vc/include/bcm_host.h:50,
                 from core.c:185:
/usr/local/vc/include/interface/vcos/pthreads/vcos_platform.h: In function ‘vcos_semaphore_wait_timeout’:
/usr/local/vc/include/interface/vcos/pthreads/vcos_platform.h:307:7: warning: implicit declaration of function ‘sem_timedwait’ [-Wimplicit-function-declaration]
       ret = sem_timedwait( sem, &ts );
       ^
# github.com/gen2brain/raylib-go/raylib
In file included from mini_al.c:4:0:
external/src/github.com/gen2brain/raylib-go/raylib/external/mini_al.h:5517:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
                            ^
compilation terminated.
```

Surely a library must be missing, so I installed libasound2-dev and tried it again with no success. Adding -I/usr/include/alsa as CFLAG didn't work either.

**Comment by gen2brain** [comment]
I guess you are trying to cross compile for RPi, so libasound2-dev you installed is just for system.
Try just to copy alsa includes to e.g. /usr/local/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/include so compiler can find it by default. mini_al opens alsa on runtime, doesn't link library so that should be ok.

On real device instructions for ubuntu/debian should just work.

**Comment by Pienkaito** [comment]
There are some wierd behaviours regarding my RPI build.

Here's a simple code example, that I've tested.
```
for !raylib.WindowShouldClose() {
	raylib.BeginDrawing()
	raylib.ClearBackground(raylib.RayWhite)

	if raylib.IsKeyDown(raylib.KeyA) {
		raylib.DrawCircle(50, 50, 19, raylib.Blue)
	}
	raylib.EndDrawing()
}
```
The supposed outcome should be that if I hold the A-Key on my keyboard then it should show a blue circle on the screen.
It does, but it flickers.
The second issue is that I can only execute my build via terminal only. Without it my Raspberry freezes.

As gen2brain said, I've cross-compiled my build with WSL.

**Comment by gen2brain** [comment]
ALSA headers are now included/bundled, also, instructions for Android and RPi are changed.

**Comment by gen2brain** [comment]
@Pienkaito also, see https://github.com/raysan5/raylib/issues/379

**Comment by gen2brain** [comment]
ALSA headers are not needed anymore, dlopen is used instead.
