### ISSUE TITLE
`raygui.TextBox()` space character not working properly

### ISSUE THREAD

**Issue by a-alhusaini** [gen2brain/raylib-go#351]
When I try to press space at the end of the text inside a TextBox. nothing happens.

**Comment by JupiterRider** [comment]
Hey @a-alhusaini ,

sorry for the late response, but I can reproduce your issue.

controls_test_suite go example:
![go](https://github.com/gen2brain/raylib-go/assets/60042618/182d01a9-927b-496a-8d76-41e56764c188)

controls_test_suite C-example from raysan5:
![c](https://github.com/gen2brain/raylib-go/assets/60042618/793f975f-f647-4107-9193-9432d2bc1eae)

As you can see, it is not possible to have a trailing space character.
