### ISSUE TITLE
WASM

### ISSUE THREAD

**Issue by znaniye** [gen2brain/raylib-go#356]
Are you still having the issue of not being able to compile to WASM/web with raylib-go?

**Comment by gen2brain** [comment]
There are no issues, it just is not possible to compile CGo to WASM, you need pure Go for that.
 
In theory, it should be possible to bundle `raylib.wasm` and to use `wazero` runtime to bind functions. That would be the third binding to maintain, besides cgo and purego. I recently tried a similar i.e. https://github.com/gen2brain/jpegxl, it is not pleasant to use and there are many functions here, and not even sure if all that would work. I don't have time to try it.
