### ISSUE TITLE
Building for Android arm64

### ISSUE THREAD

**Issue by Alireza-Ta** [gen2brain/raylib-go#358]
Hi There!

I can build with arm64 specified as `GOARCH` in the Android example; However, in the `cgo_android.go` file there's a cgo flag only for `arm`:
`#cgo android,arm CFLAGS: -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16`
So my question is does the Go compiler decide to use arm version even there's no arm64 flag? and also should we add `arm64` cgo flag for integrity?

Thanks!

**Comment by gen2brain** [comment]
That line is when you build for `GOARCH=arm`, there were some issues so flags were added, I'm not sure if it is still needed. But that is not related to you if you are building for arm64.

**Comment by Alireza-Ta** [comment]
True. I thought when building with CGO we have to specify every architecture flag!
Thank you!
