### ISSUE TITLE
log android

### ISSUE THREAD

**Issue by MatejMagat305** [gen2brain/raylib-go#362]
I give PR, but it is only sugest, maybe to  separate package (because it get little bigger binary)
on android fmt.Print() do not work, it must be inicialized by special ...

**Comment by gen2brain** [comment]
Android logs used to work, so the solution would be to find when it break.  I am not sure what your PR is supposed to do, you created only some example?

**Comment by MatejMagat305** [comment]
yes, it is working, I put it into example to ilustrate that can be everywhere, I do not know where I should place ...
