### ISSUE TITLE
cannot locate symbol "internal_storage_path"

### ISSUE THREAD

**Issue by MatejMagat305** [gen2brain/raylib-go#365]
I do not want to be bad guy, but I found error:
` java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/~~vDp8ObOmVQKrdz3ml3931g==/opencl.raylib.purego-RakQS1JU6grDady51TQKJA==/lib/arm64/libexample.so": dlopen failed: cannot locate symbol "internal_storage_path" referenced by "/data/app/~~vDp8ObOmVQKrdz3ml3931g==/opencl.raylib.purego-RakQS1JU6grDady51TQKJA==/lib/arm64/libexample.so"...
`
it is coused by `fmt.Println(rl.HomeDir())`, the hypothetical solution is:
put as function ...

**Comment by gen2brain** [comment]
Well, you are using something unsupported, how did you manage to have combination of java and purego, what is that?

**Comment by gen2brain** [comment]
Purego will only work on Windows, and raylib doesn't use Java for android, only NativeActivity.

**Comment by MatejMagat305** [comment]
it is from `rl.HomeDir()`, when it is comment, there is no error ..., I fix it, but I do not know whether it is good solution ...

**Comment by gen2brain** [comment]
Did you see this issue https://github.com/gen2brain/raylib-go/issues/353 ? Are you using the latest master version?

**Comment by gen2brain** [comment]
Also, I just tested the Android example, and there are no issues with symbols and TraceLog works just fine. I also added a line with something like `rl.TraceLog(rl.LogInfo, "hello %s", "world")`:
```
03-25 10:58:30.748 26650 26694 I raylib  : Initializing raylib 5.0
03-25 10:58:30.748 26650 26694 I raylib  : Platform backend: ANDROID
03-25 10:58:30.748 26650 26694 I raylib  : Supported raylib modules:
03-25 10:58:30.748 26650 26694 I raylib  :     > rcore:..... loaded (mandatory)
03-25 10:58:30.748 26650 26694 I raylib  :     > rlgl:...... loaded (mandatory)
03-25 10:58:30.748 26650 26694 I raylib  :     > rshapes:... loaded (optional)
03-25 10:58:30.748 26650 26694 I raylib  :     > rtextures:. loaded (optional)
03-25 10:58:30.748 26650 26694 I raylib  :     > rtext:..... loaded (optional)
03-25 10:58:30.748 26650 26694 I raylib  :     > rmodels:... loaded (optional)
03-25 10:58:30.748 26650 26694 I raylib  :     > raudio:.... loaded (optional)
03-25 10:58:30.748 26650 26694 I raylib  : ANDROID: Window orientation set as landscape
03-25 10:58:30.748 26650 26694 W raylib  : ANDROID: Window orientation changed to landscape
03-25 10:58:30.748 26650 26694 I raylib  : PLATFORM: ANDROID: Initialized successfully
03-25 10:58:30.906 26650 26694 I raylib  : DISPLAY: Upscaling required: Screen size (800x450) smaller than display size (2312x1080)
03-25 10:58:30.906 26650 26694 I raylib  : DISPLAY: Device initialized successfully
03-25 10:58:30.906 26650 26694 I raylib  :     > Display size: 2312 x 1080
03-25 10:58:30.906 26650 26694 I raylib  :     > Screen size:  800 x 450
03-25 10:58:30.906 26650 26694 I raylib  :     > Render size:  800 x 450
03-25 10:58:30.906 26650 26694 I raylib  :     > Viewport offsets: 163, 0
03-25 10:58:30.906 26650 26694 I raylib  : GL: Supported extensions count: 104
03-25 10:58:30.907 26650 26694 I raylib  : GL: OpenGL device information:
03-25 10:58:30.907 26650 26694 I raylib  :     > Vendor:   ARM
03-25 10:58:30.907 26650 26694 I raylib  :     > Renderer: Mali-G68
03-25 10:58:30.907 26650 26694 I raylib  :     > Version:  OpenGL ES 3.2 v1.r32p1-01bet2-mbs2v39_0.24a5b8b8abb488a61e5e48232a460c3e
03-25 10:58:30.907 26650 26694 I raylib  :     > GLSL:     OpenGL ES GLSL ES 3.20
03-25 10:58:30.907 26650 26694 I raylib  : GL: VAO extension detected, VAO functions loaded successfully
03-25 10:58:30.907 26650 26694 I raylib  : GL: NPOT textures extension detected, full NPOT textures supported
03-25 10:58:30.907 26650 26694 I raylib  : GL: ETC1 compressed textures supported
03-25 10:58:30.907 26650 26694 I raylib  : GL: ASTC compressed textures supported
03-25 10:58:30.907 26650 26694 I raylib  : TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
03-25 10:58:30.907 26650 26694 I raylib  : TEXTURE: [ID 1] Default texture loaded successfully
03-25 10:58:30.910 26650 26694 I raylib  : SHADER: [ID 1] Vertex shader compiled successfully
03-25 10:58:30.911 26650 26694 I raylib  : SHADER: [ID 2] Fragment shader compiled successfully
03-25 10:58:30.937 26650 26694 I raylib  : SHADER: [ID 3] Program shader loaded successfully
03-25 10:58:30.937 26650 26694 I raylib  : SHADER: [ID 3] Default shader loaded successfully
03-25 10:58:30.937 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
03-25 10:58:30.938 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
03-25 10:58:30.938 26650 26694 I raylib  : RLGL: Default OpenGL state initialized successfully
03-25 10:58:30.956 26650 26694 I raylib  : TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
03-25 10:58:30.957 26650 26694 I raylib  : FONT: Default font loaded successfully (224 glyphs)
03-25 10:58:30.957 26650 26694 I raylib  : TEXTURE: [ID 3] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
03-25 10:58:30.957 26650 26694 I raylib  : TEXTURE: [ID 3] Default texture loaded successfully
03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 4] Vertex shader compiled successfully
03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 5] Fragment shader compiled successfully
03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 6] Program shader loaded successfully
03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 6] Default shader loaded successfully
03-25 10:58:30.958 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
03-25 10:58:30.958 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
03-25 10:58:30.958 26650 26694 I raylib  : RLGL: Default OpenGL state initialized successfully
03-25 10:58:30.958 26650 26694 I raylib  : TEXTURE: [ID 4] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
03-25 10:58:30.958 26650 26694 I raylib  : FONT: Default font loaded successfully (224 glyphs)
03-25 10:58:31.409 26650 26694 I raylib  : AUDIO: Device initialized successfully
03-25 10:58:31.409 26650 26694 I raylib  :     > Backend:       miniaudio / AAudio
03-25 10:58:31.409 26650 26694 I raylib  :     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
03-25 10:58:31.409 26650 26694 I raylib  :     > Channels:      2 -> 2
03-25 10:58:31.409 26650 26694 I raylib  :     > Sample rate:   48000 -> 48000
03-25 10:58:31.409 26650 26694 I raylib  :     > Periods size:  1440
03-25 10:58:31.410 26650 26694 I raylib  : FILEIO: [raylib_logo.png] File loaded successfully
03-25 10:58:31.411 26650 26694 I raylib  : IMAGE: Data loaded successfully (256x256 | R8G8B8 | 1 mipmaps)
03-25 10:58:31.411 26650 26694 I raylib  : TEXTURE: [ID 5] Texture loaded successfully (256x256 | R8G8B8 | 1 mipmaps)
03-25 10:58:31.411 26650 26694 I raylib  : FILEIO: [coin.wav] File loaded successfully
03-25 10:58:31.412 26650 26694 I raylib  : WAVE: Data loaded successfully (22050 Hz, 16 bit, 1 channels)
03-25 10:58:31.415 26650 26694 I raylib  : STREAM: Initialized successfully (44100 Hz, 16 bit, Stereo)
03-25 10:58:31.418 26650 26694 I raylib  : FILEIO: [ambient.ogg] Music file loaded successfully
03-25 10:58:31.418 26650 26694 I raylib  :     > Sample rate:   44100 Hz
03-25 10:58:31.418 26650 26694 I raylib  :     > Sample size:   16 bits
03-25 10:58:31.418 26650 26694 I raylib  :     > Channels:      2 (Stereo)
03-25 10:58:31.418 26650 26694 I raylib  :     > Total frames:  6810624
**03-25 10:58:31.418 26650 26694 I raylib  : hello world**
03-25 10:58:36.864 26650 26694 I raylib  : STREAM: Unloaded audio stream data from RAM
03-25 10:58:36.993 26650 26694 I raylib  : AUDIO: Device closed successfully
03-25 10:58:36.993 26650 26694 I raylib  : TEXTURE: [ID 5] Unloaded texture data from VRAM (GPU)
03-25 10:58:36.993 26650 26694 I raylib  : TEXTURE: [ID 4] Unloaded texture data from VRAM (GPU)
03-25 10:58:36.994 26650 26694 I raylib  : SHADER: [ID 6] Default shader unloaded successfully
03-25 10:58:36.994 26650 26694 I raylib  : TEXTURE: [ID 3] Default texture unloaded successfully
03-25 10:58:37.002 26650 26694 I raylib  : Window closed successfully
03-25 10:58:37.228 28975 29154 I SuggestedItemsFacade: DPS items : raylib-go, ComponentInfo{com.example.android/android.app.NativeActivity}
```

**Comment by MatejMagat305** [comment]
> Did you see this issue #353 ? Are you using the latest master version?

I should, because I use static version

**Comment by gen2brain** [comment]
I mean, the latest raylib-go, how is that related to the static version, what static version? The raylib-go includes C sources.

**Comment by MatejMagat305** [comment]
> Also, I just tested the Android example, and there are no issues with symbols and TraceLog works just fine. I also added a line with something like `rl.TraceLog(rl.LogInfo, "hello %s", "world")`:
> 
> ```
> 03-25 10:58:30.748 26650 26694 I raylib  : Initializing raylib 5.0
> 03-25 10:58:30.748 26650 26694 I raylib  : Platform backend: ANDROID
> 03-25 10:58:30.748 26650 26694 I raylib  : Supported raylib modules:
> 03-25 10:58:30.748 26650 26694 I raylib  :     > rcore:..... loaded (mandatory)
> 03-25 10:58:30.748 26650 26694 I raylib  :     > rlgl:...... loaded (mandatory)
> 03-25 10:58:30.748 26650 26694 I raylib  :     > rshapes:... loaded (optional)
> 03-25 10:58:30.748 26650 26694 I raylib  :     > rtextures:. loaded (optional)
> 03-25 10:58:30.748 26650 26694 I raylib  :     > rtext:..... loaded (optional)
> 03-25 10:58:30.748 26650 26694 I raylib  :     > rmodels:... loaded (optional)
> 03-25 10:58:30.748 26650 26694 I raylib  :     > raudio:.... loaded (optional)
> 03-25 10:58:30.748 26650 26694 I raylib  : ANDROID: Window orientation set as landscape
> 03-25 10:58:30.748 26650 26694 W raylib  : ANDROID: Window orientation changed to landscape
> 03-25 10:58:30.748 26650 26694 I raylib  : PLATFORM: ANDROID: Initialized successfully
> 03-25 10:58:30.906 26650 26694 I raylib  : DISPLAY: Upscaling required: Screen size (800x450) smaller than display size (2312x1080)
> 03-25 10:58:30.906 26650 26694 I raylib  : DISPLAY: Device initialized successfully
> 03-25 10:58:30.906 26650 26694 I raylib  :     > Display size: 2312 x 1080
> 03-25 10:58:30.906 26650 26694 I raylib  :     > Screen size:  800 x 450
> 03-25 10:58:30.906 26650 26694 I raylib  :     > Render size:  800 x 450
> 03-25 10:58:30.906 26650 26694 I raylib  :     > Viewport offsets: 163, 0
> 03-25 10:58:30.906 26650 26694 I raylib  : GL: Supported extensions count: 104
> 03-25 10:58:30.907 26650 26694 I raylib  : GL: OpenGL device information:
> 03-25 10:58:30.907 26650 26694 I raylib  :     > Vendor:   ARM
> 03-25 10:58:30.907 26650 26694 I raylib  :     > Renderer: Mali-G68
> 03-25 10:58:30.907 26650 26694 I raylib  :     > Version:  OpenGL ES 3.2 v1.r32p1-01bet2-mbs2v39_0.24a5b8b8abb488a61e5e48232a460c3e
> 03-25 10:58:30.907 26650 26694 I raylib  :     > GLSL:     OpenGL ES GLSL ES 3.20
> 03-25 10:58:30.907 26650 26694 I raylib  : GL: VAO extension detected, VAO functions loaded successfully
> 03-25 10:58:30.907 26650 26694 I raylib  : GL: NPOT textures extension detected, full NPOT textures supported
> 03-25 10:58:30.907 26650 26694 I raylib  : GL: ETC1 compressed textures supported
> 03-25 10:58:30.907 26650 26694 I raylib  : GL: ASTC compressed textures supported
> 03-25 10:58:30.907 26650 26694 I raylib  : TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
> 03-25 10:58:30.907 26650 26694 I raylib  : TEXTURE: [ID 1] Default texture loaded successfully
> 03-25 10:58:30.910 26650 26694 I raylib  : SHADER: [ID 1] Vertex shader compiled successfully
> 03-25 10:58:30.911 26650 26694 I raylib  : SHADER: [ID 2] Fragment shader compiled successfully
> 03-25 10:58:30.937 26650 26694 I raylib  : SHADER: [ID 3] Program shader loaded successfully
> 03-25 10:58:30.937 26650 26694 I raylib  : SHADER: [ID 3] Default shader loaded successfully
> 03-25 10:58:30.937 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
> 03-25 10:58:30.938 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
> 03-25 10:58:30.938 26650 26694 I raylib  : RLGL: Default OpenGL state initialized successfully
> 03-25 10:58:30.956 26650 26694 I raylib  : TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
> 03-25 10:58:30.957 26650 26694 I raylib  : FONT: Default font loaded successfully (224 glyphs)
> 03-25 10:58:30.957 26650 26694 I raylib  : TEXTURE: [ID 3] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
> 03-25 10:58:30.957 26650 26694 I raylib  : TEXTURE: [ID 3] Default texture loaded successfully
> 03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 4] Vertex shader compiled successfully
> 03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 5] Fragment shader compiled successfully
> 03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 6] Program shader loaded successfully
> 03-25 10:58:30.957 26650 26694 I raylib  : SHADER: [ID 6] Default shader loaded successfully
> 03-25 10:58:30.958 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
> 03-25 10:58:30.958 26650 26694 I raylib  : RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
> 03-25 10:58:30.958 26650 26694 I raylib  : RLGL: Default OpenGL state initialized successfully
> 03-25 10:58:30.958 26650 26694 I raylib  : TEXTURE: [ID 4] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
> 03-25 10:58:30.958 26650 26694 I raylib  : FONT: Default font loaded successfully (224 glyphs)
> 03-25 10:58:31.409 26650 26694 I raylib  : AUDIO: Device initialized successfully
> 03-25 10:58:31.409 26650 26694 I raylib  :     > Backend:       miniaudio / AAudio
> 03-25 10:58:31.409 26650 26694 I raylib  :     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
> 03-25 10:58:31.409 26650 26694 I raylib  :     > Channels:      2 -> 2
> 03-25 10:58:31.409 26650 26694 I raylib  :     > Sample rate:   48000 -> 48000
> 03-25 10:58:31.409 26650 26694 I raylib  :     > Periods size:  1440
> 03-25 10:58:31.410 26650 26694 I raylib  : FILEIO: [raylib_logo.png] File loaded successfully
> 03-25 10:58:31.411 26650 26694 I raylib  : IMAGE: Data loaded successfully (256x256 | R8G8B8 | 1 mipmaps)
> 03-25 10:58:31.411 26650 26694 I raylib  : TEXTURE: [ID 5] Texture loaded successfully (256x256 | R8G8B8 | 1 mipmaps)
> 03-25 10:58:31.411 26650 26694 I raylib  : FILEIO: [coin.wav] File loaded successfully
> 03-25 10:58:31.412 26650 26694 I raylib  : WAVE: Data loaded successfully (22050 Hz, 16 bit, 1 channels)
> 03-25 10:58:31.415 26650 26694 I raylib  : STREAM: Initialized successfully (44100 Hz, 16 bit, Stereo)
> 03-25 10:58:31.418 26650 26694 I raylib  : FILEIO: [ambient.ogg] Music file loaded successfully
> 03-25 10:58:31.418 26650 26694 I raylib  :     > Sample rate:   44100 Hz
> 03-25 10:58:31.418 26650 26694 I raylib  :     > Sample size:   16 bits
> 03-25 10:58:31.418 26650 26694 I raylib  :     > Channels:      2 (Stereo)
> 03-25 10:58:31.418 26650 26694 I raylib  :     > Total frames:  6810624
> 03-25 10:58:31.418 26650 26694 I raylib  : hello world
> 03-25 10:58:36.864 26650 26694 I raylib  : STREAM: Unloaded audio stream data from RAM
> 03-25 10:58:36.993 26650 26694 I raylib  : AUDIO: Device closed successfully
> 03-25 10:58:36.993 26650 26694 I raylib  : TEXTURE: [ID 5] Unloaded texture data from VRAM (GPU)
> 03-25 10:58:36.993 26650 26694 I raylib  : TEXTURE: [ID 4] Unloaded texture data from VRAM (GPU)
> 03-25 10:58:36.994 26650 26694 I raylib  : SHADER: [ID 6] Default shader unloaded successfully
> 03-25 10:58:36.994 26650 26694 I raylib  : TEXTURE: [ID 3] Default texture unloaded successfully
> 03-25 10:58:37.002 26650 26694 I raylib  : Window closed successfully
> 03-25 10:58:37.228 28975 29154 I SuggestedItemsFacade: DPS items : raylib-go, ComponentInfo{com.example.android/android.app.NativeActivity}
> ```

ok, I give up, when is until now forbiten use "-`w -s`", then ok ..., is not,. please try `rl.TraceLog(rl.LogInfo, "hello %s", rl.HomeDir()) `

and sorry for this annoing ...

**Comment by MatejMagat305** [comment]
> I mean, the latest raylib-go, how is that related to the static version, what static version? The raylib-go includes C sources.


![Screenshot from 2024-03-25 11-44-52](https://github.com/gen2brain/raylib-go/assets/61238240/0de9baf2-dfae-42f8-b7eb-dccacf31325a)

**Comment by gen2brain** [comment]
Please, try to use a language translator, I can barely understand you. What is forbidden, where it says so? I don't have time anymore, will come back sometime, sorry.

**Comment by MatejMagat305** [comment]
well, sorry, I want to say if ldflags and static variable can"t work together, then ok and I give up, but when it should work together, then I do not understand why `rl.HomeDir()` caused error ...

**Comment by gen2brain** [comment]
Sorry, you were right, I just tested again. This is fixed in https://github.com/gen2brain/raylib-go/commit/9b53342ac0617583005414aac357b1854cf58fae.
It will correctly print the `I raylib  : hello /data/user/0/com.example.android/files`
