### ISSUE TITLE
Dear IMGUI support

### ISSUE THREAD

**Issue by Tieysson** [gen2brain/raylib-go#367]
Is it possible to integrate this library with Dear IMGUI?
If that's not something you are aiming for could you point me out in the direction to achieve it if possible?

**Comment by gen2brain** [comment]
No idea, usually combining two libraries that both render and both have a main loop should not be the aim. There is something here https://github.com/raylib-extras/rlImGui and https://github.com/oskaritimperi/imgui-impl-raylib.
