### ISSUE TITLE
2 or 3 second build times?

### ISSUE THREAD

**Issue by Triangle345** [gen2brain/raylib-go#368]
Is it normal to have 2 or 3 second build times with every change of source code? I notice that every ``` go build ``` or ``` go run ``` takes a few seconds even during a small Raylib-go test program (RayGUI based).  Currently running on Windows 11. My Go architecture is set appropriately so no surprises there.  I'm assuming this is unfortunately normal due to recompiling using CGO? Maybe I'm doing something wrong and missing some caching opportunities somewhere? Using ``` go build -x ``` command it seems the major slowdown is during the linking stage.

**Comment by gen2brain** [comment]
I have no idea, for me, it builds in a half second, but I am not on Windows and do not use antivirus real-time scanning, etc. However, I don't see a big issue if it is 2 instead of 1s.

**Comment by Triangle345** [comment]
Thanks! Turning off real time scanning improved things. I was just hoping for almost instantaneous builds since iterations can add up quickly.
