### ISSUE TITLE
audio examples hanging 

### ISSUE THREAD

**Issue by dbriemann** [gen2brain/raylib-go#37]
Hi I'm on Arch Linux. All examples run fine with the exception of audio. When I run e.g. "module_playing" it opens the window but only shows a black screen. I hear nothing and Gnome asks me to close the hanging program.

I wonder if you have an idea what causes this? All of these examples run fine when I compile them for original raylib(C) 1.8.0.

**Comment by gen2brain** [comment]
Hi, just checked in Gentoo and it works fine. Also in Ubuntu in VM. Are there anything in log output?

Note that raylib 1.8.0 uses OpenAL for audio, 1.9 dev uses single header mini_al library.

**Comment by raysan5** [comment]
Probably related: https://github.com/raysan5/rfxgen/issues/13

@mackron is working on a new [mini_al](https://github.com/dr-soft/mini_al) version with lots of improvements, it will probably address this issue... hopefully by the end of the month.

**Comment by dbriemann** [comment]
Well it strangely works if I compile the C samples included in raylib. If I compile the Go samples however it doesn't. I assumed that your Go bindings use raylib 1.8.0.. 

I just tested again and the log says: INFO: Initializing raylib (v1.9.4-dev). Now I went back and compiled raylib 1.9.4-dev and the example and it shows the same problem.

I then checked out raylib master (1.9.6-dev) and there it works again.

**Comment by mackron** [comment]
@raysan5 I think this is related to that hanging bug I fixed a few weeks ago in rfxgen.

**Comment by raysan5** [comment]
@mackron yeap, you're right, just updated version number to 1.9.6-dev after your fix.

**Comment by dbriemann** [comment]
@gen2brain do you follow raylib master or do you only update on certain releases?

Also how do you do it? Do you manually copy over those files?

**Comment by gen2brain** [comment]
@dbriemann first I followed dev branch, now master is dev. C files are manually copied and all new changes are reviewed and added for Go, i.e. new functions, renames etc. Currently there are some new functions to add, and a different method for android_main I need to review.

**Comment by dbriemann** [comment]
@gen2brain Thanks for the explanation. That sounds good but I have a minor suggestion. Could you add tags to raylib-go when you integrate a new version of raylib. 

That way users could easily check out older versions if and vendor them. Awesome work you are doing here btw!

**Comment by gen2brain** [comment]
@dbriemann C sources are updated and changes are added.
