### ISSUE TITLE
No function for `GuiLoadIcons`

### ISSUE THREAD

**Issue by iamthenoname** [gen2brain/raylib-go#370]
Would it be possible to add something like `raygui.LoadIcons()`?

**Comment by JupiterRider** [comment]
Hey @iamthenoname ,
yes we can, but I don't know how icons work. Maybe you or raysan5 have an example: https://github.com/raysan5/raygui/issues/404

I won't open a pull request for code, I haven't tested before. When I see a working example, I can write the go-binding and go-example for that function.
