### ISSUE TITLE
Cross compiling error

### ISSUE THREAD

**Issue by BH3Panzer** [gen2brain/raylib-go#372]
I have a problem, when i try to cross compile compile from linux arm64 to linux amd64 I have a problem:
executing this: GOOS=linux GOARCH=amd64 go build .
returning this:
# github.com/gen2brain/raylib-go/raylib
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:196:27: undefined: GetMouseDelta
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:220:56: undefined: GetFrameTime
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:226:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:229:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:232:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:235:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:238:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:241:6: undefined: IsKeyDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:246:8: undefined: IsGamepadAvailable
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:248:29: undefined: IsMouseButtonDown
../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240408130534-53f26d8a0802/rcamera.go:248:29: too many errors

I know that cross compile work for windows and rember that few days ago for linux amd64 worked too, but now linux amd64 and linux i386 doesn't work.

**Comment by gen2brain** [comment]
Add `CGO_ENABLED=1`, when cross-compile Go will by default disable CGO. Next, you will probably have errors because you are trying to use the arm compiler for amd64.

**Comment by BH3Panzer** [comment]
Ok, now I've executed: CGO_ENABLED=1 CC=x86_64-linux-gnu-gcc GOOS=linux GOARCH=amd64 go build .
Returned:
# ping-pong-pun
/usr/local/go/pkg/tool/linux_arm64/link: running x86_64-linux-gnu-gcc failed: exit status 1
/usr/lib/gcc-cross/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld : ne peut pas trouver -lwayland-client : Aucun fichier ou dossier de ce type
/usr/lib/gcc-cross/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld : ne peut pas trouver -lwayland-cursor : Aucun fichier ou dossier de ce type
/usr/lib/gcc-cross/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld : ne peut pas trouver -lwayland-egl : Aucun fichier ou dossier de ce type
/usr/lib/gcc-cross/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld : ne peut pas trouver -lxkbcommon : Aucun fichier ou dossier de ce type
/usr/lib/gcc-cross/x86_64-linux-gnu/12/../../../../x86_64-linux-gnu/bin/ld : ne peut pas trouver -lGL : Aucun fichier ou dossier de ce type
collect2: erreur: ld a retourné le statut de sortie 1

**Comment by BH3Panzer** [comment]
i never found how to install amd64 libs (through apt doesn't work, can't install)

**Comment by gen2brain** [comment]
No idea how to just install with apt a different architecture beside your current one, is that even supported? You can always compile all dependencies with the appropriate compiler for your target architecture. Anyway, nothing that is related to raylib-go.

**Comment by BH3Panzer** [comment]
I'll try to install amd64 deps.

**Comment by BH3Panzer** [comment]
For compile all deps, I don't know how to do that lol
