### ISSUE TITLE
Adding `SwapScreenBuffer()` and `PollInputEvents()` functions

### ISSUE THREAD

**Issue by gabriel-marques** [gen2brain/raylib-go#378]
Hello there :)

For the purpose of a personal project I wanted to use raylib with the `SUPPORT_CUSTOM_FRAME_CONTROL` in the `config.h` file option defined, but it was impossible with the actual implementation in Go because functions `PollInputEvents()` and `SwapScreenBuffer()` were not exported. So I added the following to the `rcore.go` file : 

```go
// This is to be called only if SUPPORT_CUSTOM_FRAME_CONTROL in config.h is defined
// SwapScreenBuffer - Swap back buffer to front buffer
func SwapScreenBuffer() {
	C.SwapScreenBuffer()
}

// Register all input events
func PollInputEvents() {
	C.PollInputEvents()
}
``` 

and it works fine. I was thinking about doing a pull request but not before asking you if it's a feature that you want to add or that you choosed to avoid. 

Also, the `SUPPORT_CUSTOM_FRAME_CONTROL` is a define in a C file which implies to clone the repo in order to do the modifications. I was thinking about adding a build tag to enable custom framerate, but again, I'm asking your input on that.

Thanks  :)

**Comment by gen2brain** [comment]
Hi, sure, send a PR, but please note that now any new functions must be added for both C and Purego bindings. The reason why they were not added was probably that no one needed to use them. As for the build tag, I would prefer to avoid adding new tags for something most users will never need, and in your case, you don't even need a tag, just `CGO_CFLAGS="-DSUPPORT_CUSTOM_FRAME_CONTROL=1" go build` should work.

**Comment by JupiterRider** [comment]
I've seen - purego already has these two functions. 
@gabriel-marques If you do your PR, it would be nice to put additional information in the function comments, that people need to recompile the raylib.dll.
Maybe something like this:
https://github.com/raysan5/raylib/blob/5.0/src/raylib.h#L1062

```
// Custom frame control functions
// NOTE: Those functions are intended for advance users that want full control over the frame processing
// By default EndDrawing() does this job: draws everything + SwapScreenBuffer() + manage frame timing + PollInputEvents()
// To avoid that behaviour and control frame processes manually, enable in config.h: SUPPORT_CUSTOM_FRAME_CONTROL
```

**Comment by gen2brain** [comment]
This can be closed, thanks.
