### ISSUE TITLE
Can not build for windows/darwin

### ISSUE THREAD

**Issue by 0x3alex** [gen2brain/raylib-go#380]
When trying to compile any project, which uses raylib-go, there is is build problem:
```
alex@zen:~/pathfinding$ GOOS=windows go build
go: downloading github.com/gen2brain/raylib-go/raygui v0.0.0-20240227114648-c3665eb9abf8
go: downloading github.com/gen2brain/raylib-go/raylib v0.0.0-20240227114648-c3665eb9abf8
go: downloading golang.org/x/sys v0.18.0
go: downloading github.com/ebitengine/purego v0.6.1
package pathfinding
        imports github.com/gen2brain/raylib-go/raygui: build constraints exclude all Go files in /home/alex/go/pkg/mod/github.com/gen2brain/raylib-go/raygui@v0.0.0-20240227114648-c3665eb9abf8
alex@zen:~/pathfinding$
```
compiling for linux is working as expected. `windows` and `darwin` seem to have the same issue.

**Comment by gen2brain** [comment]
When you are cross-compiling Go will by default disable CGO, so add CGO_ENABLED=1, which will tell you the real error. The error would be related to you trying to compile for Windows or Darwin using Linux GCC. There are many issues where this is explained.

**Comment by gen2brain** [comment]
You also have an example in the main README of how to cross-compile from Linux.
