### ISSUE TITLE
Update to 2.0

### ISSUE THREAD

**Issue by D3nX** [gen2brain/raylib-go#39]
Version 2.0 of raylib is released and the raylib GUI have a lot changed, an update is highly welcome ;)

**Comment by raysan5** [comment]
Note that just updated version number to 2.0-dev, still no official release. Jumped version because latest commit changes were really breaking the API a lot. 

You can still expect some more things breaking in the following weeks... i my opinion, better wait a while for an official update...

**Comment by gen2brain** [comment]
Sure, I know it is still 2.0-dev, I updated C sources just now, because it is easier to follow changes then do everything at once.

**Comment by egonelbre** [comment]
@gen2brain Can you also add tags so a particular version would be easier to find.

**Comment by gen2brain** [comment]
@egonelbre Tags are added.

**Comment by D3nX** [comment]
raylib 2.0 is fully released now, I guess it's the time to update the lib !

**Comment by D3nX** [comment]
@gen2brain For when raylib 2.0 bindings ?

**Comment by gen2brain** [comment]
@D3nX I will try to update to 2.0 these days, I am busy with other projects and it is time of holidays :)
I don't think much has changed since, so it should not be difficult, but also you don't miss much currently.

**Comment by raysan5** [comment]
@gen2brain no hurries, you're right, it"s summer time, take it easy! As you say not much has changed in terms of API, just some renames and a couple of new functions... I also have to take care of some bugs and updates... And adding animated models support will break some things... probably moved to next version...
