### ISSUE TITLE
Not support win7? Is there any way to work with win7?

### ISSUE THREAD

**Issue by Timfu2019** [gen2brain/raylib-go#392]
go >=1.21 not support win7 any more. so i am try to install raylib-go in go version go1.20.14 windows/amd64. But failed :
_# go get -v -u github.com/gen2brain/raylib-go/raylib
github.com/gen2brain/raylib-go/raylib imports
        slices: package slices is not in GOROOT (D:\win10\Program Files\Go\src\slices)_
After some search ,slices is a new package in go >=1.21.  And if i use go >=1.21 , it worked well but  not support win7.
Is there any way to work with win7?

**Comment by gen2brain** [comment]
Unfortunately, it is not just the `slices` package, that can be easily supported via `golang.org/x/exp/slices` on older versions, but there is also a usage of `runtime.Pinner` here https://github.com/gen2brain/raylib-go/blob/master/raylib/rmodels.go#L390. I will check if that can be replaced with `runtime.Keepalive` (it will keep pointers from GC, but will not stop Go from moving them). If possible I too would prefer to have support for Windows 7.

**Comment by gen2brain** [comment]
Ok, support is added in https://github.com/gen2brain/raylib-go/commit/a997a44fb95b521f6ef5642dabd363cca7f89808, just use go1.20. I just tested if it is possible to build with go1.20, please confirm if it works now on Windows 7.

**Comment by gen2brain** [comment]
Just to add a note. There is a repo here https://github.com/Snawoot/go-win7, that reverts that patch for Go that broke Windows 7 support, so you can have the latest 1.23.3 version with support for Windows 7. And it looks like it can easily be modified for future releases.
