### ISSUE TITLE
delve fails to build, can't find utils_log.h

### ISSUE THREAD

**Issue by wintermute-cell** [gen2brain/raylib-go#394]
Hey!

Running `dlv debug cmd/game/main.go` fails:
![image](https://github.com/gen2brain/raylib-go/assets/64093588/c3433109-d17b-49c8-a960-d503d3013934)

So far, I have traced this down to this flag dlv uses to disable inlining and optimizations for gc:
`-gcflags "all=-N -l"`

When running `go build -o outfile -gcflags "all=-N -l" cmd/game/main.go`, the same error occurs:
![image](https://github.com/gen2brain/raylib-go/assets/64093588/9aa024df-f42e-4717-b56d-d207cc0ea6dd)

Both flags individually cause the same problem (so either `-N` or `-l` is enough to break it).
Edit: other gcflags seem to cause the same problem.

Not sure where I could continue searching from this point on.

**Comment by gen2brain** [comment]
https://github.com/gen2brain/raylib-go/issues/373

**Comment by wintermute-cell** [comment]
I don't think this issue is related to the issue you linked. https://github.com/gen2brain/raylib-go/issues/373 (and the delve and go issues related to it) seems to build down to the apple linker.
This issue does not appear to be affected by the underlying C compiler and linker (I tried gcc, clang and internal linking).

Furthermore, I was not able to reproduce the bug without raylib-go specifically. While it might be possible that the actual error lies somewhere within the go toolchain, I think further investigation why this problem occurs with specifically raylib-go would be worthwhile.

Hence I'd like to ask you to please reopen this.

**Comment by gen2brain** [comment]
The issue is the support for Delve and CGO, I don't think anyone managed to debug i.e. InitWIndow() and OpenGL context with Delve. Whatever the issue is, and how Delve works with C will not be fixed here in this repo. Unless you are sure that raylib-go is the problem and you can identify the issue, I don't see a reason for the issue to be kept open.

**Comment by wintermute-cell** [comment]
Okay, I found out more. The problem actually has nothing to do with the -gcflags, sorry for the misdirection.
Passing the gcflags simply skipped my existing build cache, which I discovered when clearing said cache.

Well, now I can't build raylib-go at all anymore, always encountering this error:

![image](https://github.com/gen2brain/raylib-go/assets/64093588/3dcf6d37-6983-4a75-ad48-9f2a94b83cea)

Since I don't know a lot about CGO, I am again pretty lost and would appreciate some insight if you have any.
I tried all kinds of Go versions, from 1.19 to 1.22, none work; so I'm not sure what could have broken the process since it last compiled successfully.

Sorry again for the incorrect investigation so far!

**Comment by gen2brain** [comment]
Do you have a C compiler installed?

**Comment by wintermute-cell** [comment]
yes
```
 ~ % gcc --version
gcc (GCC) 13.2.0
```

**Comment by gen2brain** [comment]
And you are not using vendor and CGO_ENABLED=1?

**Comment by wintermute-cell** [comment]
yes

**Comment by wintermute-cell** [comment]
Okay, I finally figured it out!

It was an `exec $SHELL` at the end of my CGO shell hook. I have no idea why it would cause this issue, but for me it is fixed now.

Thanks again, and sorry for the fuss.
