### ISSUE TITLE
strange errors

### ISSUE THREAD

**Issue by MatejMagat305** [gen2brain/raylib-go#395]
![Screenshot from 2024-06-19 20-52-09](https://github.com/gen2brain/raylib-go/assets/61238240/80646ef9-b6fd-44b6-9b97-8a45c5ffbc1a)

**Comment by gen2brain** [comment]
You either are missing the C compiler or trying to compile with CGO_ENABLED=0. There are dozens of similar issues.

**Comment by MatejMagat305** [comment]
ach sorry
