### ISSUE TITLE
Crash after LoadModel / Texture 

### ISSUE THREAD

**Issue by ewolution69** [gen2brain/raylib-go#399]
Hello, I am currently porting my “Odin language” code to Golang for performance tests.
( it loads the Sponza scene with lights and fog ) 

After loading the first texture the program crashes.

Output:

INFO: FILEIO: [Sponza/sponza.glb] File loaded successfully
INFO: MODEL: [Sponza/sponza.glb] Model basic data (glb) loaded successfully
INFO:     > Meshes count: 1
INFO:     > Materials count: 26 (+1 default)
INFO: FILEIO: [./Sponza/9902244931375451333.png] File loaded successfully
INFO: IMAGE: Data loaded successfully (1024x1024 | R8G8B8A8 | 1 mipmaps)
SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=1 addr=0x0
signal arrived during cgo execution

**Comment by JupiterRider** [comment]
Hey ewolution69,
could you provide a tiny example project, which produces that error?
Thanks in advance!

**Comment by ewolution69** [comment]
Hello, I have uploaded a very small project which triggers the error.

Build system is LMDE 6 Faye ( Mint Debian Edition )
Go version: 1.22.4

https://github.com/ewolution69/Learning

**Comment by JupiterRider** [comment]
The function `rl.InitWindow` has to be called before `rl.LoadModel`.
The reason for that is, that InitWindow initializes all the OpenGL stuff and without that, the Model cannot be loaded into your VRAM.

**Comment by gen2brain** [comment]
Thanks @JupiterRider , I guess this can be closed than?

**Comment by ewolution69** [comment]
Thank you very much, that was my mistake .... I didn't pay attention to it the whole time.

@gen2brain Yes you can close it.
