### ISSUE TITLE
raygui.TextBox problems

### ISSUE THREAD

**Issue by D3nX** [gen2brain/raylib-go#40]
I've found 2 problems with raygui.TextBox :
1. The golang function argument does not check with C version (two argument needed "freeEdit" & "textSize") : 
   -> C version : bool GuiTextBox(Rectangle bounds, char *text, int textSize, bool freeEdit);
   -> Go version : func TextBox(bounds raylib.Rectangle, text string) string
2. (On my computer, maybe on you too) Unnable to use backspace to delete character, work not.

Hope you l'ill fix soon, I really need these bug fix for my game :D

**Comment by raysan5** [comment]
Just note that raygui has changed substantially, even bumped version to 2.0. Still some controls (GuiScrollBar, GuiTextBoxMultiline) are under development.

**Comment by gen2brain** [comment]
I keep it more as a reminder. I know there are a lot of changes now, if I cannot handle it I can just wrap it and call C functions like in raylib module, I wanted to avoid that at first.

**Comment by gen2brain** [comment]
Closed in favor of https://github.com/gen2brain/raylib-go/issues/197.
