### ISSUE TITLE
The android template doesn't load assets on Windows

### ISSUE THREAD

**Issue by elMuso** [gen2brain/raylib-go#401]
I have found some (easily fixable) problems with the android template that might be worth checking. These problems make it so if I run the project on a Windows machine with vscode using only the official GO extension. The project loads and build, but the assets are not accessible

The problems are the following

- The assets folder is inside the android folder 
- The example code does not account for desktop asset loading

Problem number 1 can be fixed by changing ` assets.srcDirs = ['assets']` to ` assets.srcDirs = ['../assets']` and moving the assets folder to the root folder of the project.

Problem number 2 can be fixed by adding android targeted code to main.go
```
func getAsset(path string) string{
	if(runtime.GOOS != "android"){
		return "assets/"+path
	}
	return path
}
//Extra code goes here

 
        texture := rl.LoadTexture(getAsset("raylib_logo.png")) // Load texture (placed on assets folder)
	fx := rl.LoadSound(getAsset("coin.wav"))  // Load WAV audio file (placed on assets folder)
	ambient := rl.LoadMusicStream(getAsset("ambient.ogg")) // Load music

```

Does the example need these modifications? I don't know to be honest. They are quick fixes but might be difficult to see to someone who is starting with golang and doesn't have any android development experience, or plans to develop on desktop and then build to android. If it is not necessary to make the changes then this issue should just be closed.

**Comment by gen2brain** [comment]
What is the issue, i.e, what is expexted and what happens?

**Comment by gen2brain** [comment]
Android example is just an example. You are free to do whatever you want. Point is, this is for issues, for random questions, there are discussions, discord, etc. This is not place for random questions, sorry if maybe I misunderstood what you are asking.

**Comment by gen2brain** [comment]
Also, I do not care about people who just started with Golang, there are better places to ask such questions. Sorry, but I just can not keep up with all the random/not related questions. If you are a begginer in Go, I do not provide support for free. This is all about this single repo, nothing else.

**Comment by elMuso** [comment]
It was not a question, it was a suggestion that the android example could be adapted to work in windows and android using the same asset folder by modifying one line in the gradle build file. 
Since it seems that the example is just an example i will close the issue :)

**Comment by gen2brain** [comment]
Please, if you can contribute a better example send a PR.

**Comment by gen2brain** [comment]
Example already works on desktop (Linux) and android, that is enough for me, if it is easy to adapt for windows please send a pr, I guess it is worth the PR then, but this really is not an issue.

**Comment by gen2brain** [comment]
Anyway, it is just an example.
