### ISSUE TITLE
Request to add ExportWaveAsCode

### ISSUE THREAD

**Issue by sandy-30** [gen2brain/raylib-go#402]
Raylib has an API to export wave as array data [`ExportWaveAsCode`](https://github.com/raysan5/raylib/blob/master/src/raylib.h#L1627).

With go bindings we can use it for tooling. I can raise a PR if required.

**Comment by gen2brain** [comment]
But that export C code, what is the use of C code in Go bindings?

**Comment by sandy-30** [comment]
In my usecase it's for tooling, my game is in cpp, but I am planning to have some external tool support that ai my dev workflow. Maily to inport sound files (in any format), convert them to wave with ffmepg (ffmpeg-go module) and generate hederfiles for he same.

**Comment by gen2brain** [comment]
I don't like the idea of adding just that one function, if I am to accept this (which I prefer not to) then all `AsCode` functions should be added, of course for both cgo and purego. As that function is not so complicated you can replicate that in your code, I guess you would need a `data` member of the `Wave` struct to be exported, you can send a PR for that instead.

**Comment by gen2brain** [comment]
`Wave` data is exported in https://github.com/gen2brain/raylib-go/commit/b6bb8ec528ed633671d817adcf3ae13bcd37ea30.
