### ISSUE TITLE
Raylib Go is Slow?

### ISSUE THREAD

**Issue by codebbbb** [gen2brain/raylib-go#408]
Hello!
I don't know if this is necessarily a new issue, but Raylib go seem like it's slow. As in, it's slowing down my program. I think I am using purego as mentioned in the installation section of the readme, I ran the go profiler, and see purego syscall being red on the graph (I am no profiler expert but seems bad), thing causing the program to run way slower then it should be (I'm making a Intel 8080 Space Invaders emulator). I am using purego by just dropping the Raylib DLL in the root of project on running `go run .` I see a option for cgo, that needs a C compiler which I don't have (I'm on windows by the way), but now I am starting to think is cgo faster than purego? (I have attached the profile output graph svg)
![pprof001](https://github.com/user-attachments/assets/f200d44a-97de-4337-a2a2-ce1c2e7fb79a)

-CodeBBBB

**Comment by gen2brain** [comment]
There should be no difference with cgo compared to purego, so most probably the problem is in your code. It is slow compared to what?

**Comment by codebbbb** [comment]
Slow to how it should run, it should be running very fast

**Comment by codebbbb** [comment]
https://8080.cakers.io/ this is example, my is running probably half the speed, or slower at parts, in theory, it should be running way faster then that too.

**Comment by gen2brain** [comment]
So C code runs fast but Go doesn't?

**Comment by codebbbb** [comment]
I didn't test with C, it's just the program is running slow. Here's the code on how I did the drawing of pixels to the screen.
func main() {
	// Start profiling
	f, err := os.Create("myprogram.prof")
	if err != nil {
	 
	fmt.Println(err)
	return
	 
	}
	pprof.StartCPUProfile(f)
	defer pprof.StopCPUProfile()

    // Initialize Raylib window
    screenWidth := 224 * 3
    screenHeight := 256 * 3
    rl.InitWindow(int32(screenWidth), int32(screenHeight), "Space Invaders Emulator")
    defer rl.CloseWindow()

    rl.SetTargetFPS(60)

    cpu := cpuInit()

    cpu.interruptEnable = true

    cpu.loadRom("space-invaders.rom")

    textureWidth := 224
    textureHeight := 256
    screenTexture := rl.LoadRenderTexture(int32(textureWidth), int32(textureHeight))
    defer rl.UnloadRenderTexture(screenTexture)

    for !rl.WindowShouldClose() {
        // Begin drawing to the texture
        rl.BeginTextureMode(screenTexture)
        rl.ClearBackground(rl.Black)

        cpu.totalCycles = 0

        cpu.ir1()

        cpu.drawScreen()

        cpu.ir2()

        cpu.executeInterrupt(2)

        rl.EndTextureMode()

        rl.BeginDrawing()
        rl.ClearBackground(rl.Black)
        rl.DrawTextureEx(screenTexture.Texture, rl.NewVector2(0, 0), 0, 3, rl.White)
        rl.EndDrawing()
    }
}

func (cpu *cpu) drawScreen() {
    vramStart := 0x2400
    screenWidth := 224
    screenHeight := 256

    for y := 0; y < screenHeight; y++ {
        for x := 0; x < screenWidth; x++ {
            byteIndex := vramStart + (y / 8) + ((screenWidth - x - 1) * 32)
            bitIndex := uint8(y % 8)

            pixelColor := (cpu.memory[byteIndex] >> (bitIndex)) & 0x01

            color := rl.Black
            if pixelColor > 0 {
                color = rl.White
            }

            rl.DrawPixel(int32(screenWidth-x-1), int32(y), color)
        }
    }
}

**Comment by gen2brain** [comment]
Doesn't look like a very efficient way, not sure what are your goals, as I said, the problem seems to be in your code. If you can replicate something in C or some other bindings but here is slow then we can check further.

**Comment by JupiterRider** [comment]
Hey,

I used the the `example/core/basic_window/main.go`:
```golang
package main

import (
	"os"
	"runtime/pprof"

	rl "github.com/gen2brain/raylib-go/raylib"
)

func main() {
	f, _ := os.Create("cpu")
	defer f.Close()
	pprof.StartCPUProfile(f)
	defer pprof.StopCPUProfile()
	rl.SetConfigFlags(rl.FlagVsyncHint)
	rl.InitWindow(800, 450, "raylib [core] example - basic window")

	//rl.SetTargetFPS(60)

	for !rl.WindowShouldClose() {
		rl.BeginDrawing()

		rl.ClearBackground(rl.RayWhite)

		rl.DrawText("Congrats! You created your first window!", 190, 200, 20, rl.LightGray)

		rl.EndDrawing()
		break
	}

	rl.CloseWindow()
}
```
Here is the example:
**CGO**
![cgo](https://github.com/user-attachments/assets/6c84c4c7-e58d-42af-8e9c-41ac6e26b546)

**Purego**
![purego](https://github.com/user-attachments/assets/a483dfdf-0683-4d43-957b-65920a3f24e9)

**Comment by gen2brain** [comment]
There is no native code anywhere, so not sure how much and if pprof is useful at all in this case. There is not much difference in cgo vs purego. Also, there are no places where there are some critical paths that can be improved, these are just bindings for C code. Like in all binding there is overhead when calling C, but nothing that drastic. Create C example and compare, but there are already raylib bindings benchmarks.

**Comment by JupiterRider** [comment]
@codebbbb Maybe you can use a shader instead of rl.DrawPixel.

**Comment by codebbbb** [comment]
You guys could be right, I am going to look into mines.

**Comment by codebbbb** [comment]
@gen2brain @JupiterRider This could be a very dumb question, so bare with me here. So right now I have a single file that is 1800 lines of code doing the emulation and drawing and all of that. all the functions in one file. You guys thinking if all of that is in one file, it makes Go slow?

**Comment by gen2brain** [comment]
Nope, who cares if that is one file or not.

**Comment by codebbbb** [comment]
What about a 250 case long switch statement?

**Comment by codebbbb** [comment]
@gen2brain  and @JupiterRider, I figure something out, but I am going to need your guys help. So I been using DrawPixel but that's not efficient at all apparently, like it's slow. I got advice that it's "much more efficient to fill out an image, upload that image, and then draw it as a texture, drawing a texture and a pixel is the same data to the GPU
once the texture is on the GPU. This need to emulate a framebuffer, thus that's why you want to use an image, it represents the frame buffer.", They linked this example: https://github.com/raylib-extras/examples-c/tree/main/write_to_image But when I try using the similar approach I got errors like:
```
 .\8080.go:1778:43: cannot use displayTexture (variable of type rl.Texture2D) as *rl.Image value in argument to rl.LoadImageColors
.\8080.go:1779:47: cannot use imageBuffer.Data (variable of type unsafe.Pointer) as []color.RGBA value in argument to rl.UpdateTexture  
```  
So now I am lost, and need help converting my code. Here is the base I am working with:
```
func main() {
    screenWidth := 224 * 3
    screenHeight := 256 * 3
    rl.InitWindow(int32(screenWidth), int32(screenHeight), "Space Invaders Emulator")
    defer rl.CloseWindow()

    rl.SetTargetFPS(60)

    // Initialize CPU
    cpu := cpuInit()

    cpu.interruptEnable = true

    //cpu.dumpMemory("prememlog.txt")
    cpu.loadRom("space-invaders.rom")
    //cpu.dumpMemory("memlog.txt")

    textureWidth := 224
    textureHeight := 256
    screenTexture := rl.LoadRenderTexture(int32(textureWidth), int32(textureHeight))
    defer rl.UnloadRenderTexture(screenTexture)

    // Main loop
    for !rl.WindowShouldClose() {
        // Begin drawing to the texture
        rl.BeginTextureMode(screenTexture)
        rl.ClearBackground(rl.Black)

        cpu.totalCycles = 0

        for cpu.totalCycles < firstInterruptCycles {
			cycles := cpu.excuteInstruction()
			cpu.totalCycles += cycles
		}

		cpu.executeInterrupt(1)

        for cpu.totalCycles < secondInterruptCycles {
			cycles := cpu.excuteInstruction()
			cpu.totalCycles += cycles
		}

		cpu.executeInterrupt(2)

        cpu.drawScreen()

        rl.EndTextureMode()

        rl.BeginDrawing()
        rl.ClearBackground(rl.Black)
        rl.DrawTextureEx(screenTexture.Texture, rl.NewVector2(0, 0), 0, 3, rl.White)
        rl.EndDrawing()
    }
}

func (cpu *cpu) drawScreen() {
    vramStart := 0x2400
    screenWidth := 224
    screenHeight := 256

    for y := 0; y < screenHeight; y++ {
        for x := 0; x < screenWidth; x++ {
            byteIndex := vramStart + (y / 8) + ((screenWidth - x - 1) * 32)
            bitIndex := uint8(y % 8)

            pixelColor := (cpu.memory[byteIndex] >> (bitIndex)) & 0x01

            color := rl.Black
            if pixelColor > 0 {
                color = rl.White
            }

            rl.DrawPixel(int32(screenWidth-x-1), int32(y), color)
        }
    }
}
```
If you guys can help me out on this, this will be great. Thank you in advance.

**Comment by kaandesu** [comment]
Hello, just a quick disclaimer I am very new to all this but just wanted to share something hoping it may help.. I don't understand emulation and cpu stuff on the code so reproduced the problem separately without them than tried to use the same solution I found for it on your code above, here are some changes that might solve your problem:

instead of:
> screenTexture := rl.LoadRenderTexture(int32(textureWidth), int32(textureHeight))
```go
imageBuffer := rl.GenImageColor(int(textureWidth), int(textureHeight), rl.Black)
defer rl.UnloadImage(imageBuffer)
//  texture from the image buffer
screenTexture := rl.LoadTextureFromImage(imageBuffer)
defer rl.UnloadTexture(screenTexture)

// Main loop
...
```

drawScreen() to -> drawScreen(imageBuffer *rl.Image):
```go
func (cpu *cpu) drawScreen(imageBuffer *rl.Image) {
...
// instead of  rl.DrawPixel(int32(screenWidth-x-1), int32(y), color)
rl.ImageDrawPixel(imageBuffer, int32(screenWidth-x-1), int32(y), color)
}
```

In the main loop:
```go
   ...
    // Draw to the image buffer instead of directly to the screen
    cpu.drawScreen(&imageBuffer)
    
    // Update the texture with the new pixel data
    pixelData := convertImageDataToRGBA(*imageBuffer)
    rl.UpdateTexture(screenTexture, pixelData)
    
    // Draw the texture to the screen
    rl.BeginDrawing()
    rl.ClearBackground(rl.Black)
    rl.DrawTextureEx(screenTexture, rl.NewVector2(0, 0), 0, 3, rl.White)
    rl.EndDrawing()
    }
}
```
The convertImageDataToRGBA function is needed because rl.Image stores pixels as a raw byte array, but rl.UpdateTexture needs a []color.RGBA slice. 
> .\8080.go:1779:47: cannot use imageBuffer.Data (variable of type unsafe.Pointer) as []color.RGBA value in argument to rl.UpdateTexture  
convertImageDataToRGBA function
```go
func convertImageDataToRGBA(image rl.Image) []color.RGBA {
	pixelCount := int(image.Width * image.Height)

	// slice with the correct length and capacity
	pixelData := make([]color.RGBA, pixelCount)

	//  pointer to the image data
	src := unsafe.Slice((*uint8)(image.Data), pixelCount*4)

	// iterate over the source  and convert it to RGBA format
	for i := 0; i < pixelCount; i++ {
		pixelData[i] = color.RGBA{
			R: src[i*4],
			G: src[i*4+1],
			B: src[i*4+2],
			A: src[i*4+3],
		}
	}
	return pixelData
}
```

**Comment by codebbbb** [comment]
@kaandesu I got an error: .\8080.go:1764:24: cannot use &imageBuffer (value of type **rl.Image) as *rl.Image value in argument to cpu.drawScreen Also I am suppose to import "image/color" and import "unsafe"?

**Comment by JupiterRider** [comment]
@kaandesu `rl.UpdateTextureRec` or `rl.UpdateTexture` are looking promising. Under the hood they use [glTexSubImage2D](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glTexSubImage2D.xhtml).

**Comment by codebbbb** [comment]
@kaandesu @JupiterRider  This actually what I came up with
```go
func main() {
	// Start profiling
	f, err := os.Create("myprogram.prof")
	if err != nil {
		fmt.Println(err)
		return
	}
	pprof.StartCPUProfile(f)
	defer pprof.StopCPUProfile()

	// Initialize Raylib window
	screenWidth := 224 * 3
	screenHeight := 256 * 3
	rl.InitWindow(int32(screenWidth), int32(screenHeight), "Space Invaders Emulator")
	defer rl.CloseWindow()

	rl.SetTargetFPS(60)

	// Initialize CPU
	cpu := cpuInit()
	cpu.interruptEnable = true
	cpu.loadRom("space-invaders.rom")

	textureWidth := 224
	textureHeight := 256
	screenImage := rl.GenImageColor(int(textureWidth), int(textureHeight), rl.Black)
	screenTexture := rl.LoadTextureFromImage(screenImage)
	defer rl.UnloadTexture(screenTexture)
	defer rl.UnloadImage(screenImage)

	// Main loop
	for !rl.WindowShouldClose() {
		// Begin frame
		rl.BeginDrawing()
		rl.ClearBackground(rl.Black)

		cpu.totalCycles = 0

		for cpu.totalCycles < firstInterruptCycles {
			cycles := cpu.excuteInstruction() 
			cpu.totalCycles += cycles
		}
		cpu.executeInterrupt(1)

		for cpu.totalCycles < secondInterruptCycles {
			cycles := cpu.excuteInstruction() 
			cpu.totalCycles += cycles
		}
		cpu.executeInterrupt(2)

		cpu.drawScreen(screenImage)
 
		rl.UpdateTexture(screenTexture, rl.LoadImageColors(screenImage))  

		rl.DrawTextureEx(screenTexture, rl.NewVector2(0, 0), 0, 3, rl.White)

		rl.DrawFPS(0, 0)

		rl.EndDrawing()
	}
}

func (cpu *cpu) drawScreen(screenImage *rl.Image) {
	rl.ImageClearBackground(screenImage, rl.Black)
	vramStart := 0x2400
	screenWidth := 224
	screenHeight := 256

	for y := 0; y < screenHeight; y++ {
		for x := 0; x < screenWidth; x++ {
			byteIndex := vramStart + (y / 8) + ((x) * 32)
			bitIndex := uint8(y % 8)

			pixelColor := (cpu.memory[byteIndex] >> bitIndex) & 0x01

			if pixelColor > 0 {
				rl.ImageDrawPixel(screenImage, int32(x), int32(screenHeight-y-1), rl.White)
			}
		}
	}
}
```
No need to deal with convertImageDataToRGBA(). Also performance is better, but honestly what helped was doing this:
```go
if pixelColor > 0 {
     rl.ImageDrawPixel(screenImage, int32(x), int32(screenHeight-y-1), rl.White)
}
```
