### ISSUE TITLE
Go Run . error with Mac OS 14

### ISSUE THREAD

**Issue by Ronin15** [gen2brain/raylib-go#417]
# github.com/gen2brain/raylib-go/raylib
In file included from ../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240930075631-c66f9e2942fe/cgo_darwin.go:7:
In file included from ../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240930075631-c66f9e2942fe/external/glfw/src/context.c:28:
In file included from ../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240930075631-c66f9e2942fe/external/glfw/src/internal.h:325:
In file included from ../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240930075631-c66f9e2942fe/external/glfw/src/platform.h:58:
In file included from ../../go/pkg/mod/github.com/gen2brain/raylib-go/raylib@v0.0.0-20240930075631-c66f9e2942fe/external/glfw/src/cocoa_platform.h:29:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:24:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:39:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CoreText.h:26:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTFramesetter.h:21:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTTypesetter.h:20:
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreText.framework/Headers/CTLine.h:138:5: error: unknown type name 'CFAttributedStringRef'; did you mean 'NSAttributedString'?

**Comment by Ronin15** [comment]
installed go with home brew and no more issues. Issues above happened with official arm go .pkg

**Comment by JupiterRider** [comment]
Hey @Ronin15 ,
can you compare the output of `go env` for both go installations?
