### ISSUE TITLE
raymath.Vector2Angle incorrect?

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#42]
Hey, there! It seems like the angles returned by raymath.Vector2Angle isn't correct? 

Here's a quick example:

```go

left := raylib.NewVector2(-1, 0)
right := raylib.NewVector2(1, 0)
fmt.Println(raymath.Vector2Angle(left, right))  // Prints out "0", which is wrong
fmt.Println(raymath.Vector2Angle(right, left))  // Prints out "180", which is correct

down := raylib.NewVector2(0, 1)
fmt.Println(raymath.Vector2Angle(down, right))  // Prints out "315", which is wrong
fmt.Println(raymath.Vector2Angle(right, down))  // Prints out "135", which is also wrong
// Shouldn't it be 90 or 270?

```

EDIT: Huh, looks like for my purposes (telling which direction the player is heading in), just providing an empty Vector2 for the actual vector to check against works...?

```go
left := raylib.NewVector2(-1, 0)
noDir := raylib.NewVector2(0, 0)
fmt.Println(raymath.Vector2Angle(noDir, left))  // Prints out "180", which is correct.
```

EDIT 2: But I notice that when I do it this way, it increases going clockwise, rather than counter-clockwise, as it "should" be when thinking of rotations with radians (though I know that this returns degrees, not radians).

**Comment by gen2brain** [comment]
Is this still an issue?

**Comment by SolarLune** [comment]
Hello, sorry for the late reply.

Yes, it is still an issue; I'm using the most up-to-date version of raylib-go currently available.

**Comment by JupiterRider** [comment]
Something like this should work:

```
	angle := math.Atan2(float64(right.X*left.Y-right.Y*left.X), float64(right.X*left.X+right.Y*left.Y)) * 180 / math.Pi

	if angle < 0 {
		angle += 360
	}

	return float32(angle)
```

Got it from libgdx: [https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Vector2.java#L348](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Vector2.java#L348)

**Comment by gen2brain** [comment]
Closed with https://github.com/gen2brain/raylib-go/pull/176
