### ISSUE TITLE
Missing texture filter Trilinear

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#424]
In the example https://www.raylib.com/examples/textures/loader.html?name=textures_draw_tiled they use `TEXTURE_FILTER_TRILINEAR` when calling the `SetTextureFilter` method:

    SetTextureFilter(texPattern, TEXTURE_FILTER_TRILINEAR);

This constant seems to be missing in raylib-go.

**Comment by JupiterRider** [comment]
In raylib-go this constant is the type `TextureFilterMode`:
https://pkg.go.dev/github.com/gen2brain/raylib-go/raylib#TextureFilterMode
