### ISSUE TITLE
AutomationEventsList implemented incorrectly?

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#431]
AutomationEventsList is implemented like this:

    // AutomationEventList - Automation event list
    type AutomationEventList struct {
        Capacity uint32
        Count    uint32
        Events   *AutomationEvent
    }
where Events is a pointer to a single AutomationEvent. But if you look at the [Automation Events example](https://www.raylib.com/examples/core/loader.html?name=core_automation_events) it looks like is should actually be a list of AutomationEvents. Shouldn't this be a slice, or an array in raylib-go, or is it supposed to be a linked list and AutomationEvent is missing a next pointer?

Otherwise, could someone please show me how to implement this logic in go?
```
// NOTE: Multiple events could be executed in a single frame
while (playFrameCounter == aelist.events[currentPlayFrame].frame)
{
    PlayAutomationEvent(aelist.events[currentPlayFrame]);
    currentPlayFrame++;

    ....
}
```

**Comment by gen2brain** [comment]
That is a C array. @JupiterRider added a wrapper in https://github.com/gen2brain/raylib-go/pull/439.
