### ISSUE TITLE
Conflicts with malgo

### ISSUE THREAD

**Issue by make-42** [gen2brain/raylib-go#434]
When building a project using both of your bindings for raylib and miniaudio, there's a conflict while linking. Is there anyway around this?
![image](https://github.com/user-attachments/assets/04004427-19c2-41f1-9d36-43f567334a84)

Thank you!

**Comment by gen2brain** [comment]
Well, if you are not using raylib miniaudio compile with `-tags noaudio`. Or, you can pass `-ldflags '-extldflags=-Wl,--allow-multiple-definition'` to allow it to compile.

**Comment by make-42** [comment]
It works! Thank you very much!
