### ISSUE TITLE
DrawRectangleRoundedLines implemented incorrectly?

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#435]
It looks like `DrawRectangleRoundedLines` is implemented incorrectly, in [Raylib](https://github.com/raysan5/raylib/blob/master/src/rshapes.c#L1087) there are two functions called 
```
    DrawRectangleRoundedLines 
    DrawRectangleRoundedLinesEx
```
where `DrawRectangleRoundedLinesEx` takes `thickness` as an extra argument, while `DrawRectangleRoundedLines` assumes `thickness` 1.0.

In raylib-go, only `DrawRectangleRoundedLines` exists, and it accepts the ´thickness` but it is ignored.

This makes it hard to complete the [draw_rectangle_rounded](https://www.raylib.com/examples/shapes/loader.html?name=shapes_draw_rectangle_rounded) example.

**Comment by JupiterRider** [comment]
raylib-go purego version works with raylib 5.0 and raylib-go cgo version works with raylib v5.1-dev.

If I add these functions to the cgo version, the signature of the functions would differ and if I add them to the purego version, the user would need to compile a raylib v5.1-dev raylib.dll.

**Comment by gen2brain** [comment]
@JupiterRider Perhaps we can think about embedding the DLL in binary. The size of the gzipped library is about 700K, so on runtime, it can unpack it somewhere in /tmp and use the full path to the library. What do you think? However, it would make more sense if other platforms could also work, and it could be behind some build tag.

**Comment by JupiterRider** [comment]
@gen2brain Do you mean to gzip compress the .dll/.so file and put it base64 encoded into the source code?

**Comment by gen2brain** [comment]
Yes, well no need for base64, just gzip and `embed`.

**Comment by Caue-Aron** [comment]
So we'll get this correct eventually? Rn im working on a UI project similar to WxWidgets but with go and raylib, the incorrect rounded rect lines is really noticeable as of now.

**Comment by JupiterRider** [comment]
> Yes, well no need for base64, just gzip and `embed`.
@gen2brain I started a discussion for this to not pollute this issue: https://github.com/gen2brain/raylib-go/discussions/453
But yes, it is possible. We would only need our own build pipeline for the libraries.
