### ISSUE TITLE
Easing library improvements

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#44]
Hey, there!

The easing library is definitely useful, but the arguments being named single letters makes it hard to use, especially without any example. It might be good to rename the arguments to what they're expected to be (time / factor, min, max, etc). It might also be good to add an example, or something similar. I could do this myself, as well; I just have to get around to making a PR for it.

Thanks for the port, anyway! It's very useful.

**Comment by gen2brain** [comment]
Hi,

There is an example with easings here https://github.com/gen2brain/raylib-go/blob/master/examples/easings/easings/main.go , but you are right, it is difficult to guess what are the expected arguments. Maybe that can be just added to comment/doc.

**Comment by gen2brain** [comment]
Comments are added for functions.

**Comment by SolarLune** [comment]
I'm late to replying to this, but thanks!
