### ISSUE TITLE
Font.Chars should have type []GlyphInfo, instead of *GlyphInfo

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#446]
The type `Font` in `raylib-go` is declared as follows:
```
// Font type, includes texture and charSet array data
type Font struct {
	// Base size (default chars height)
	BaseSize int32
	// Number of characters
	CharsCount int32
	// Padding around the chars
	CharsPadding int32
	// Characters texture atlas
	Texture Texture2D
	// Characters rectangles in texture
	Recs *Rectangle               <- Should be []Rectangle?
	// Characters info data
	Chars *GlyphInfo              <- Should be []GlyphInfo?
}

```
In the example [text/font_sdf](https://www.raylib.com/examples/text/loader.html?name=text_font_sdf) on raylib.com, the value `fontDefault.Chars` is set to the return value of the function `LoadFontData` (it returns `[]GlyphInfo`). This leads me to think that `Font.Chars` should have the type `[]GlyphInfo` as well. 

And maybe `Font.Recs` should also be a slice (`[]Rectangle`)?

**Comment by JupiterRider** [comment]
We are passing structs between C and Go. So this field cannot be a slice, because slices only exist in Go.
But you can use `unsafe.Slice` and `unsafe.SliceData` to convert them.
