### ISSUE TITLE
Missing function GenImageFontAtlas()

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#447]
In the example [text/font_sdf](https://www.raylib.com/examples/text/loader.html?name=text_font_sdf) on raylib.com, they use a function called `GenImageFontAtlas`. That function seems to be missing, at least I cannot find a replacement for it.

**Comment by JupiterRider** [comment]
Thanks @Hultan ! I provided a PR #448 which also adds this example

**Comment by Hultan** [comment]
Fantastic, then I can check that of my list of missing examples in raylib-go.
