### ISSUE TITLE
Missing function : GetScreenToWorldRay

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#457]
The function GetScreenToWorldRay seems to be missing. It is needed to complete the example [draw_3d](https://www.raylib.com/examples/text/loader.html?name=text_draw_3d) in the `text` section...

**Comment by Hultan** [comment]
The example seems to work fine using rl.GetMouseRay() though, so no rush with this one...

**Comment by gen2brain** [comment]
Well, that is a renamed function, you are looking at what is to become raylib 5.5, so when is released this is probably not the only function that will have something to work on.

**Comment by Hultan** [comment]
I understand, then I will close this one...

**Comment by gen2brain** [comment]
Sure, it will have to be done on a new release anyway. Thanks for going through and reviewing all the examples.
