### ISSUE TITLE
Missing functions on type ModelAnimation

### ISSUE THREAD

**Issue by Hultan** [gen2brain/raylib-go#466]
The type `Model` has the methods GetBones() and GetBindPoses(). I think that the type `ModelAnimation` should have these methods as well. Otherwise the `m3d_loading` example code looks a little bit weird (see below).

Maybe it should have a `GetTransform(frame, bone int)` method as well? 

```
modelBones := model.GetBones()
modelPoses := model.GetBindPose()
animBones := unsafe.Slice(anims[animID].Bones, anims[animID].BoneCount)
animPoses := unsafe.Slice(anims[animID].FramePoses, anims[animID].FrameCount)
transforms := unsafe.Slice(animPoses[animFrameCounter], anims[animID].BoneCount)
```

**Comment by JupiterRider** [comment]
@Hultan @gen2brain I created a PR #474 for this :)
