### ISSUE TITLE
Tags do not work

### ISSUE THREAD

**Issue by JupiterRider** [gen2brain/raylib-go#473]
It says: "github.com/gen2brain/raylib-go/raylib@v5.0.0" could not be found:

![Screenshot_20241129_201412](https://github.com/user-attachments/assets/5b77c356-92b9-49e9-ac3b-58d883ff4f6e)

Is that because we would need `module github.com/gen2brain/raylib-go/raylib/v5` in go.mod?

**Comment by gen2brain** [comment]
The version tags never worked properly. `raylib` is in the subdirectory, so per the documentation, tags should be named `raylib/v5.0.0`. Now they are, but it will still not find the latest tag properly. I prefer not to mess with `v5` or similar.

**Comment by gen2brain** [comment]
And it looks like what you mention is the issue. I will try it soon.

**Comment by gen2brain** [comment]
Well, there are other issues, but I will leave it as it was before and maybe address them in the future.

**Comment by gen2brain** [comment]
This is now fixed. I chose the easiest option, renamed the tags to, e.g. `raylib/v0.55.0` for raylib `5.5`, and the patch version can be used for Go-specific changes. Much better, users will now get a stable version while I just committed `5.6-dev` sources to master.
