### ISSUE TITLE
Query available monitor resolutions / max window sizes?

### ISSUE THREAD

**Issue by justinclift** [gen2brain/raylib-go#56]
Is there a way to retrieve a list of potential maximum window sizes?

Looking at [an upstream issue](https://github.com/raysan5/raylib/issues/31) related to window/monitor sizing, it points to the [GLFW docs](http://www.glfw.org/docs/latest/window.html).

Reading through the info there, it seems like this is something GLFW can report back.

Is there presently a way to get that info with raylib/raylib-go? :smile:

**Comment by raysan5** [comment]
not yet...

**Comment by justinclift** [comment]
Oh well, was a thought.  I'll just use hard coded values for my personal application for now. :smile:
