### ISSUE TITLE
Weird bug with repeated calls to DrawCube()

### ISSUE THREAD

**Issue by justinclift** [gen2brain/raylib-go#57]
Found a weird bug earlier today, and took some time to confirm it on a 2nd system (just in case).

The bug is really easy to reproduce.  It just needs a medium sized grid of Cubes to be created.

When the number of cubes passes some threshold, instead of rendering in the correct location the cubes start getting rendered directly in front of the camera **as part of the camera**.

Example code, with the threshold passed:

```go
for i := -10; i < 10; i++ {
        for j := -10; j < 11; j++ { // Change the 11 to 6 or lower, and the bug goes away
                r.DrawCube(r.Vector3{X:float32(i), Z:float32(j)}, 0.2, 0.2, 0.2, r.Red)
        }
}
```

Screenshots, showing the cubes incorrectly rendered directly in front of the camera:

![bug_boxes_rendered_in_the_camera_instead4](https://user-images.githubusercontent.com/406299/44612588-808da400-a801-11e8-9631-f3d6c9d8f696.png)
![bug_boxes_rendered_in_the_camera_instead1](https://user-images.githubusercontent.com/406299/44612585-779cd280-a801-11e8-963f-9e9317b85384.png)

When panning the camera around (eg using the mouse), the incorrectly placed cubes move with the camera.  eg they're always fixed right in front, with the rest of the scene moving around.

This code is underneath the threshold, so things work:

```go
for i := -10; i < 10; i++ {
        for j := -10; j < 6; j++ { // Change the 6 to a higher number and a bug appears
                r.DrawCube(r.Vector3{X:float32(i), Z:float32(j)}, 0.2, 0.2, 0.2, r.Red)
        }
}
```

When things work correctly, this is how it's supposed to look:

![screenshot_showing_expected_scene](https://user-images.githubusercontent.com/406299/44612652-f5f97480-a801-11e8-9f03-e2266af19025.png)

For reference (as I tested this on two systems, with different OpenGL versions) the full code is here:

&nbsp; &nbsp; https://github.com/justinclift/raylib_bug1

It's super simple code. :smile:

**Comment by gen2brain** [comment]
Please check with the new release, there were many changes. If you still have issues you can reopen.
