### ISSUE TITLE
Black screenshot

### ISSUE THREAD

**Issue by balwes** [gen2brain/raylib-go#59]
Hi, I wanted to take a screenshot of the basic window example:
```
package main

import (
	rl "github.com/gen2brain/raylib-go/raylib"
	"time"
)

func main() {
	rl.InitWindow(800, 450, "raylib [core] example - basic window")
	rl.SetTargetFPS(60)
	rl.BeginDrawing()
	rl.ClearBackground(rl.RayWhite)
	rl.DrawText("Congrats! You created your first window!", 190, 200, 20, rl.LightGray)
	rl.EndDrawing()
	time.Sleep(time.Second)
	rl.TakeScreenshot("bar.png")
	rl.CloseWindow()
}
```
Despite the window showing the correct background and text, the resulting image bar.png is just a black image (not transparent, confirmed with Photoshop). I added the pause just to be sure it wasn't some parallelism issue.

I ran this on W10.

Edit: I tried pausing also AFTER the screenshot call but got the same result.

**Comment by raysan5** [comment]
mmmh... where is the game loop?

**Comment by gen2brain** [comment]
@balwes just tested your example in Linux and it works ok, even without loop and without sleep. But that is meant to be used with loop I guess, with some assigned shortcut for action.

**Comment by balwes** [comment]
> mmmh... where is the game loop?

I tried adding it:
package main

```
import (
	rl "github.com/gen2brain/raylib-go/raylib"
)

func main() {
	rl.InitWindow(800, 450, "raylib [core] example - basic window")
	rl.SetTargetFPS(60)

	for !rl.WindowShouldClose() {
		rl.BeginDrawing()
		rl.ClearBackground(rl.RayWhite)
		rl.DrawText("Congrats! You created your first window!", 190, 200, 20, rl.LightGray)
		rl.EndDrawing()
	}
	rl.TakeScreenshot("bar.png")
	rl.CloseWindow()
}
```
And it worked! I don't see why it should matter though, but thanks for the help.

**Comment by VincentToups** [comment]
I'm seeing this same issue (intermittently) in more or less the same sort of situation. I'm attempting to take a screenshot on exit, before calling CloseWindow. Some of the time (about half) I get the screenshot, and the rest of the time I get a black image of the correct size.
