### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by andrewwatson** [gen2brain/raylib-go#6]
I'd love to build this and run it myself, especially on mobile.  Could you include some basic steps for building the game so people can build it and add on to it?

Thanks!

**Comment by gen2brain** [comment]
There is an Android example with build instructions here https://github.com/gen2brain/raylib-go/tree/master/examples/android/example . Just replace android/assets and build shared library from game/project. If you change library name you also have to change it in AndroidManifest.xml.

**Comment by andrewwatson** [comment]
Great! I'll do that, thanks!
