### ISSUE TITLE
MP3 files won't play.

### ISSUE THREAD

**Issue by sheppe** [gen2brain/raylib-go#61]
I've tried loading MP3 files instead of the OGG file included in the example, and the following info and error gets thrown. Note that the OGG file does play correctly, and I've tested this with a couple of different MP3 files that I know are not corrupt. Each MP3 fails with the same error.

INFO: Initializing raylib 2.0-dev
INFO: Display device initialized successfully
INFO: Display size: 3000 x 2000
INFO: Render size: 800 x 450
INFO: Screen size: 800 x 450
INFO: Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: OpenGL 3.3 Core profile supported
INFO: GPU: Vendor:   NVIDIA Corporation
INFO: GPU: Renderer: GeForce GTX 1050/PCIe/SSE2
INFO: GPU: Version:  3.3.0 NVIDIA 391.40
INFO: GPU: GLSL:     3.30 NVIDIA via Cg compiler
INFO: Number of supported extensions: 374
INFO: [EXTENSION] DXT compressed textures supported
INFO: [EXTENSION] ETC2/EAC compressed textures supported
INFO: [EXTENSION] Anisotropic textures filtering supported (max: 16X)
INFO: [EXTENSION] Clamp mirror wrap texture mode supported
INFO: [TEX ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: [TEX ID 1] Base white texture loaded successfully
INFO: [SHDR ID 1] Shader compiled successfully
INFO: [SHDR ID 2] Shader compiled successfully
INFO: [SHDR ID 3] Shader program loaded successfully
INFO: [SHDR ID 3] Default shader loaded successfully
INFO: [CPU] Default buffers initialized successfully (lines, triangles, quads)
INFO: [VAO ID 1] Default buffers VAO initialized successfully (lines)
INFO: [VAO ID 2] Default buffers VAO initialized successfully (triangles)
INFO: [VAO ID 3] Default buffers VAO initialized successfully (quads)
INFO: OpenGL default states initialized successfully
INFO: [TEX ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: [TEX ID 2] Default font loaded successfully
INFO: Audio device initialized successfully: Default Playback Device
INFO: Audio backend: mini_al / WASAPI
INFO: Audio format: 32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO: Audio channels: 2 -> 2
INFO: Audio sample rate: 44100 -> 48000
INFO: Audio buffer size: 1197
could not create context: module is not sane
WARNING: [test.mp3] XM file could not be opened
ERROR: PlayMusicStream() : No audio buffer
exit status 1

**Comment by gen2brain** [comment]
I think this is resolved already in raylib, it will be ok when I update the library.

**Comment by sheppe** [comment]
Cool. Any idea when that will be?

**Comment by raysan5** [comment]
I'm sorry but I'm afraid it's not working yet on raylib... requires some more testing...

**Comment by sheppe** [comment]
>           I'm sorry but I'm afraid it's not working yet on raylib... requires some more testing...

Any idea when it may be fixed? I'm working on an audio app, and it'd sure be nice to include the ability to play MP3's.

**Comment by gen2brain** [comment]
C sources are updated and MP3 works now.

**Comment by SolarLune** [comment]
You could probably close this, then, @gen2brain; not sure if sheppe is around.

**Comment by sheppe** [comment]
I'm here, but had to move on to an alternative library. 

Thanks nonetheless!
