### ISSUE TITLE
Issues installing on macOS

### ISSUE THREAD

**Issue by hagemajr** [gen2brain/raylib-go#62]
When running go get -v -u github.com/gen2brain/raylib-go/raylib

I get the below stream of errors. Any ideas what could be causing this?

> # github.com/gen2brain/raylib-go/raylib
> In file included from core.c:143:
> In file included from go/src/github.com/gen2brain/raylib-go/raylib/external/glfw/include/GLFW/glfw3.h:195:
> /System/Library/Frameworks/OpenGL.framework/Headers/gl.h:5:2: warning: gl.h and gl3.h are both included.  Compiler will not invoke errors if using removed OpenGL functionality. [-W#warnings]
> core.c:667:6: error: conflicting types for 'IsWindowReady'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:803:12: note: previous declaration is here
> core.c:673:6: error: conflicting types for 'WindowShouldClose'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:804:12: note: previous declaration is here
> core.c:703:6: error: conflicting types for 'IsWindowMinimized'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:805:12: note: previous declaration is here
> core.c:945:6: error: conflicting types for 'IsCursorHidden'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:826:12: note: previous declaration is here
> core.c:1463:6: error: conflicting types for 'IsFileExtension'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:869:12: note: previous declaration is here
> core.c:1602:6: error: conflicting types for 'ChangeDirectory'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:876:12: note: previous declaration is here
> core.c:1608:6: error: conflicting types for 'IsFileDropped'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:877:12: note: previous declaration is here
> core.c:1727:6: error: conflicting types for 'IsKeyPressed'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:890:12: note: previous declaration is here
> core.c:1738:6: error: conflicting types for 'IsKeyDown'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:891:12: note: previous declaration is here
> core.c:1745:6: error: conflicting types for 'IsKeyReleased'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:892:12: note: previous declaration is here
> core.c:1756:6: error: conflicting types for 'IsKeyUp'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:893:12: note: previous declaration is here
> core.c:1780:6: error: conflicting types for 'IsGamepadAvailable'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:898:12: note: previous declaration is here
> core.c:1792:6: error: conflicting types for 'IsGamepadName'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:899:12: note: previous declaration is here
> core.c:1845:6: error: conflicting types for 'IsGamepadButtonPressed'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:901:12: note: previous declaration is here
> core.c:1859:6: error: conflicting types for 'IsGamepadButtonDown'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:902:12: note: previous declaration is here
> core.c:1872:6: error: conflicting types for 'IsGamepadButtonReleased'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:903:12: note: previous declaration is here
> core.c:1886:6: error: conflicting types for 'IsGamepadButtonUp'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:904:12: note: previous declaration is here
> core.c:1905:6: error: conflicting types for 'IsMouseButtonPressed'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:910:12: note: previous declaration is here
> core.c:1920:6: error: conflicting types for 'IsMouseButtonDown'
> go/src/github.com/gen2brain/raylib-go/raylib/raylib.h:911:12: note: previous declaration is here
> fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by gen2brain** [comment]
Ok, it should be fixed in https://github.com/gen2brain/raylib-go/commit/8d36ebe392441e065d2d6cd54a64da54b039b66a .

**Comment by hagemajr** [comment]
Works for me now, thank you!
