### ISSUE TITLE
x386 build

### ISSUE THREAD

**Issue by OnePatchMan** [gen2brain/raylib-go#63]
I do the "go build MyProgramWithRaylibgo.go" with GOARCH=386 and get that error
"
 github.com/gen2brain/raylib-go/raylib
..\github.com\gen2brain\raylib-go\raylib\raylib.go:1120:9: undefined: LoadImageEx
"
aslso after "go get -v -u github.com/gen2brain/raylib-go/raylib", same error.

**Comment by gen2brain** [comment]
Are you on 386 platform? You cannot cross compile cgo just with GOARCH.

**Comment by gen2brain** [comment]
You can configure 386 mingw toolchain on your machine and point CC, CFLAGS etc. to that location. In Linux that is easier but it is the same, you can see example here https://github.com/gen2brain/cam2ip/blob/master/make.bash .

**Comment by OnePatchMan** [comment]
So, CC variable sets command for Mingw? Where i can find information about golang env viriables?

**Comment by gen2brain** [comment]
You can find some info on https://golang.org/cmd/cgo/ , but you will need just CGO_CFLAGS and CGO_LDFLAGS , and CC. What I sent you was just an example, pkgconfig is not needed for raylib-go.

**Comment by OnePatchMan** [comment]
Thank you for aswer and for raylib-go. I'll go to explore all that information)

**Comment by OnePatchMan** [comment]
Just check how it works)
