### ISSUE TITLE
Raymath C vs go - differing behaviour

### ISSUE THREAD

**Issue by ovaillancourt** [gen2brain/raylib-go#65]
Hi! Great job on the port, been having a blast using it over the past few days.

I noticed today that a number of Vector related Raymath functions in the go port are mutating the vector instead of returning a transformed copy, which seems to diverge in behaviour from Raymath C.

(Raylib C also initially had this behaviour but this was changed in [this commit](https://github.com/raysan5/raylib/commit/61e0e4b4f37cc66135445bc87af7c92399fa69ee) from last March.)

To illustrate my point, `Vector2Scale` is one example of such difference:

Raymath C: https://github.com/raysan5/raylib/blob/master/src/raymath.h#L219-L223
Raymath go: https://github.com/gen2brain/raylib-go/blob/master/raymath/raymath.go#L57-L60

Would you consider updating Raymath-go to normalize with the behaviour of Raymath-C? (I am a novice Go developer but could help with this.)

Thanks!

**Comment by gen2brain** [comment]
This will be fixed together with https://github.com/gen2brain/raylib-go/issues/58 , but not sure when will I find time. Help is welcomed.
