### ISSUE TITLE
[Install] A error??

### ISSUE THREAD

**Issue by EtianAM** [gen2brain/raylib-go#66]
**_Hi, I'm a new go developer and I don't know much about this project so it might not be a mistake, but when I install the library it tells me the following:_**

> In file included from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib\cgo_windows.go:18:0:
 Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c: In function 'updateCursorImage':
 Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:247:41: warning: passing argument 2 of 'LoadCursorW' from incompatible pointer type [-Wincompatible-pointer-types]
             SetCursor(LoadCursorW(NULL, IDC_ARROW));
                                         ^~~~~~~~~
In file included from c:\mingw\include\windows.h:48:0,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_platform.h:65,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/internal.h:186,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/context.c:28,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib\cgo_windows.go:6:
c:\mingw\include\winuser.h:4003:27: note: expected 'LPCWSTR {aka const short unsigned int *}' but argument is of type 'CHAR * {aka char *}'
 WINUSERAPI HCURSOR WINAPI LoadCursorW (HINSTANCE, LPCWSTR);
                           ^~~~~~~~~~~
In file included from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib\cgo_windows.go:18:0:
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c: In function 'translateCursorShape':
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:406:20: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
             return IDC_ARROW;
                    ^~~~~~~~~
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:408:20: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
             return IDC_IBEAM;
                    ^~~~~~~~~
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:410:20: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
             return IDC_CROSS;
                    ^~~~~~~~~
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:412:20: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
             return IDC_HAND;
                    ^~~~~~~~
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:414:20: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
             return IDC_SIZEWE;
                    ^~~~~~~~~~
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:416:20: warning: return from incompatible pointer type [-Wincompatible-pointer-types]
             return IDC_SIZENS;
                    ^~~~~~~~~~
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c: In function '_glfwRegisterWindowClassWin32':
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:1198:42: warning: passing argument 2 of 'LoadCursorW' from incompatible pointer type [-Wincompatible-pointer-types]
     wc.hCursor       = LoadCursorW(NULL, IDC_ARROW);
                                          ^~~~~~~~~
In file included from c:\mingw\include\windows.h:48:0,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_platform.h:65,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/internal.h:186,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/context.c:28,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib\cgo_windows.go:6:
c:\mingw\include\winuser.h:4003:27: note: expected 'LPCWSTR {aka const short unsigned int *}' but argument is of type 'CHAR * {aka char *}'
 WINUSERAPI HCURSOR WINAPI LoadCursorW (HINSTANCE, LPCWSTR);
                           ^~~~~~~~~~~
In file included from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib\cgo_windows.go:18:0:
Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_window.c:1209:31: warning: passing argument 2 of 'LoadImageW' from incompatible pointer type [-Wincompatible-pointer-types]
                               IDI_APPLICATION, IMAGE_ICON,
                               ^~~~~~~~~~~~~~~
In file included from c:\mingw\include\windows.h:48:0,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/win32_platform.h:65,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/internal.h:186,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib/external/glfw/src/context.c:28,
                 from Users\etian_ya1t1\go\src\github.com\gen2brain\raylib-go\raylib\cgo_windows.go:6:
c:\mingw\include\winuser.h:4015:26: note: expected 'LPCWSTR {aka const short unsigned int *}' but argument is of type 'CHAR * {aka char *}'
 WINUSERAPI HANDLE WINAPI LoadImageW (HINSTANCE, LPCWSTR, UINT, int, int, UINT);`

**_Thanks_.**

`Pd: I can use the library... I do not know if that is a error`

**Comment by EtianAM** [comment]
I do not know how I got that warning, I just followed the readme.md instructions, execute this command, I am on Windows 10 86x:

> go get -v -u github.com/gen2brain/raylib-go/raylib`

It only appeared to me that and already, I could use it, but I wanted to report it just in case...

`Pd: This and the previous thing can be badly translated because I used an automatic translation page.`

**Comment by gen2brain** [comment]
That looks like you have 32bit compiler only on 64bit platform. You can try to add `GOARCH=386` . What compiler did you install on both systems?

**Comment by EtianAM** [comment]
Thanks, thats work, but...
I recive the same "error"
