### ISSUE TITLE
How to build for different targets

### ISSUE THREAD

**Issue by eriknielsen** [gen2brain/raylib-go#67]
Hello, I have never used bindings like this before. Considering that raylib can build to many targets, how does one do that with this library?

**Comment by gen2brain** [comment]
Hello,

You cannot just cross compile with simple `GOOS=darwin GOARCH=amd64 go build` for example, library uses https://golang.org/cmd/cgo/, so you need to have compiler and toolchain for arch you  want to build for. For example I have on my Linux system mingw toolchain in /usr/x86_64-w64-mingw32 and x86_64-w64-mingw32-gcc in PATH, so I can just `CC=x86_64-w64-mingw32-gcc GOOS=darwin GOARCH=amd64 go build` to cross compile for Windows.

You have links in README.md for examples how to compile for Android and RPi.
Web platform is not supported, both GopherJS and Go WASM can not work with cgo, some solution would be to create JavaScript bindings for raylib C with embind and emscripten, and then GopherJS/WASM can be used to create wrapper for those js binding.

**Comment by eriknielsen** [comment]
Ok, thanks for the thorough explaination! I was mostly interested in the web as a target, it's a shame it's not possible yet!
