### ISSUE TITLE
FPS modify velocity

### ISSUE THREAD

**Issue by EtianAM** [gen2brain/raylib-go#68]
**_Hello, I recently tried several examples, when trying to change the FPS I realized that the speed of movement in objects changes, here I leave the codes changed:_**

> package main
>
>import (
	"github.com/gen2brain/raylib-go/raylib"
)
>
>func main() {
	var screenHeight, screenWith int32
	screenHeight = 480
	screenWith = 720
>
>	rl.InitWindow(screenWith, screenHeight, "60 FPS")
	ballPosition := rl.NewVector2(float32(screenWith)/2, float32(screenHeight)/2)
	rl.SetTargetFPS(60)
>
>	for !rl.WindowShouldClose() {
		if rl.IsKeyDown(rl.KeyLeft) {
			ballPosition.X-- // ballPosition.X += 1
		}
		if rl.IsKeyDown(rl.KeyRight) {
			ballPosition.X++
		}
		if rl.IsKeyDown(rl.KeyUp) {
			ballPosition.Y--
		}
		if rl.IsKeyDown(rl.KeyDown) {
			ballPosition.Y++
		}
		rl.BeginDrawing()
		//***************************************************************
		rl.DrawFPS(0, 0)
		rl.ClearBackground(rl.Black)
		rl.DrawCircleV(ballPosition, 100, rl.White)
		//***************************************************************
		rl.EndDrawing()
	}
>}

120 FPS:
> package main
>
>import (
	"github.com/gen2brain/raylib-go/raylib"
)
>
>func main() {
	var screenHeight, screenWith int32
	screenHeight = 480
	screenWith = 720
>
>	rl.InitWindow(screenWith, screenHeight, "120 FPS")
	ballPosition := rl.NewVector2(float32(screenWith)/2, float32(screenHeight)/2)
	rl.SetTargetFPS(120)
>
>	for !rl.WindowShouldClose() {
		if rl.IsKeyDown(rl.KeyLeft) {
			ballPosition.X-- // ballPosition.X += 1
		}
		if rl.IsKeyDown(rl.KeyRight) {
			ballPosition.X++
		}
		if rl.IsKeyDown(rl.KeyUp) {
			ballPosition.Y--
		}
		if rl.IsKeyDown(rl.KeyDown) {
			ballPosition.Y++
		}
		rl.BeginDrawing()
		//***************************************************************
		rl.DrawFPS(0, 0)
		rl.ClearBackground(rl.Black)
		rl.DrawCircleV(ballPosition, 100, rl.White)
		//***************************************************************
		rl.EndDrawing()
	}
>}

**_Thanks._**

`Pd: That was translated with a page of automatic translation, so it can have errors.`

**Comment by raysan5** [comment]
Expected behaviour. If you process more frames per second, more value updates are done and object speed increases. To avoid that you can use frame delta-time for time independent behaviour.

**Comment by raysan5** [comment]
Multiply a fixed incremental position value by:
```c
float GetFrameTime(void);  // Returns time in seconds for last frame drawn
double GetTime(void);      // Returns elapsed time in seconds since InitWindow()
```
