### ISSUE TITLE
Updating raylib-go

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#70]
Hey, there. 

It's been awhile since the last update of the C sources in raylib - It'd be nice to get an update. I'm asking specifically because there is an issue with render textures clearing themselves in this version of raylib-go that isn't there in the latest version. 

Thanks!

**Comment by SolarLune** [comment]
Oh, OK. That'd be fine, then. I'll do something else for the meantime.

**Comment by refacto** [comment]
`raylib 2.5.0` is out now, just fyi.

**Comment by gen2brain** [comment]
C sources are updated. New functions will be added later.
