### ISSUE TITLE
Install with OpenGL1.1

### ISSUE THREAD

**Issue by TerensTare** [gen2brain/raylib-go#73]
What command should I run to get the bindings work with OpenGL1.1?

**Comment by gen2brain** [comment]
You just add `-tags opengl11` to your build command, as noted in README.

**Comment by TerensTare** [comment]
you mean like
go build -tags opengl11 file.fo file2.go?

**Comment by TerensTare** [comment]
I tried the command and it says 
# github.com/gen2brain/raylib-go/raylib
core.c: In function 'GetDirectoryPath':
core.c:1623:5: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncpy(filePath, fileName, strlen(fileName) - (strlen(lastSlash) - 1));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core.c:1623:33: note: length computed here
     strncpy(filePath, fileName, strlen(fileName) - (strlen(lastSlash) - 1));
                                 ^~~~~~~~~~~~~~~~
# github.com/gen2brain/raylib-go/raylib
In function 'LoadBMFont',
    inlined from 'LoadFont' at text.c:279:51:
text.c:1016:5: warning: 'strncat' specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncat(texPath, fileName, strlen(fileName) - strlen(lastSlash) + 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
text.c: In function 'LoadFont':
text.c:1016:32: note: length computed here
     strncat(texPath, fileName, strlen(fileName) - strlen(lastSlash) + 1);
                                ^~~~~~~~~~~~~~~~
In function 'LoadBMFont',
    inlined from 'LoadFont' at text.c:279:51:
text.c:1017:5: warning: 'strncat' specified bound depends on the length of the source argument [-Wstringop-overflow=]
     strncat(texPath, texFileName, strlen(texFileName));

then i ran the executable and it outputs
INFO: Initializing raylib 2.1-dev
WARNING: [GLFW3 Error] Code: 65542 Decription: WGL: The driver does not appear to support OpenGL
WARNING: GLFW Failed to initialize Window
WARNING: [GLFW3 Error] Code: 65537 Decription: The GLFW library is not initialized
INFO: Window closed successfully

**Comment by TerensTare** [comment]
I have an Intel GPU
Is that OK?
