### ISSUE TITLE
Windows build from linux gives error undefined function

### ISSUE THREAD

**Issue by oxilgk** [gen2brain/raylib-go#74]
When I try to build a binary for the windows platform as well as darwin an error pops up

> gen2brain/raylib-go/raylib/raylib.go:1120:9: undefined: LoadImageEx

![2019-03-23-223618_842x374_scrot](https://user-images.githubusercontent.com/26058964/54871400-16030d80-4dbc-11e9-9a3a-6fd20c1d409d.png)

This is my small Program which loads an image, creates a texture and draws into the screen (I've not added all of the code here).

**Comment by gen2brain** [comment]
Textures MUST be loaded after Window initialization (OpenGL context is required).

**Comment by oxilgk** [comment]
But I do initialize the window first
> rl.InitWindow(WINH, WINW, TITLE)

And after that I am loading the textures with LoadTextureFromImage.
Should I load the image after the initialization of the OpenGL context as well?

**Comment by gen2brain** [comment]
Yes, that `rl.LoadImage` from screenshot should also go after the window is initialized.
Do you have any errors if you try to compile some basic example?

**Comment by oxilgk** [comment]
Yeah I tried that also but it didn't work.
Also I tried to compile one basic example with the raylib_logo as a texture and I still get this kind of error when building for windows.

![2019-03-25-010145_1348x755_scrot](https://user-images.githubusercontent.com/26058964/54887261-816edd00-4e99-11e9-9a9b-231318620862.png)

**Comment by gen2brain** [comment]
See https://github.com/gen2brain/raylib-go/issues/67#issuecomment-441109222 .

**Comment by oxilgk** [comment]
Okay thanks.
The toolchain (I haven't installed) should solve my problem!

**Comment by Bendimester23** [comment]
![Screenshot_20211120_123327](https://user-images.githubusercontent.com/58264102/142724794-a7954b08-3d7b-45e3-a036-7541f4e712c9.png)
i am trying to build my project to windows, but it gives me this error(i have mingw installed)

**Comment by gen2brain** [comment]
@Bendimester23 add `CGO_ENABLED=1`

**Comment by Bendimester23** [comment]
it works, thank you
