### ISSUE TITLE
raylib.go:1120:9: undefined: LoadImageEx

### ISSUE THREAD

**Issue by jhautefeuille** [gen2brain/raylib-go#75]
When 

GOOS=linux GOARCH=mipsle go build -o simulationmips simulation.go

or

GOOS=js GOARCH=wasm go build -o simulation.wasm simulation.go

Then

github.com/gen2brain/raylib-go/raylib/raylib.go:1120:9: undefined: LoadImageEx

**Comment by gen2brain** [comment]
See https://github.com/gen2brain/raylib-go/issues/67#issuecomment-441109222 .
