### ISSUE TITLE
Not All Functions Available 

### ISSUE THREAD

**Issue by nicholassimon** [gen2brain/raylib-go#77]
Hi again, just wondering I am new to using Raylib (only a month or two) and am very impressed. However I have noticed that not all features are available using Go (Golang) I am using this https://github.com/gen2brain/raylib-go

However I cannot for instance use DrawTextRec as it is not available it seems in the Go bindings. How does that work? Will they be updated? Was just wondering, though can understand it may be someone else's work.
void DrawTextRec(Font font, const char *text, Rectangle rec, float fontSize, float spacing, bool wordWrap, Color tint);

Otherwise really enjoying learning it, it is very fun to use.
![59271738-a67f1a80-8c54-11e9-9e1e-5c1c0b4975c3](https://user-images.githubusercontent.com/33998213/59345386-48b00880-8d10-11e9-849d-4a22909cd664.png)

**Comment by gen2brain** [comment]
Hello, new functions will be added when I find time to update the C library that is included here. Not sure when will that happen, maybe for some weekend. Btw. opening many issues about this will not speed anything.

**Comment by nicholassimon** [comment]
Do understand, new to GitHub so was wondering how it works. So, you basically you are a separate person from Raylib and the Go bindings are a personal project I assume? Was just interested, thought it was as such. Can understand time is an issue so whenever will be fine with me, thanks for the great work anyway.

**Comment by fr3fou** [comment]
Is this still the case?

**Comment by nicholasimon** [comment]
Not sure, I have in fact switched to using the other version of Raylib https://github.com/Lachee/raylib-goplus 

I do know that it includes a number of Raylib features from newer versions of Raylib that were not available in this version when I stopped using it.

**Comment by gen2brain** [comment]
Many functions are added, those listed above also. Open new issues if you need something not available.
