### ISSUE TITLE
alloca.h: No such file or directory

### ISSUE THREAD

**Issue by 5k3105** [gen2brain/raylib-go#8]
```
$ go get -v github.com/gen2brain/raylib-go/raylib
github.com/gen2brain/raylib-go/raylib
# github.com/gen2brain/raylib-go/raylib
In file included from C:\goworksp\src\github.com\gen2brain\raylib-go\raylib\audio.go:4:0:
./external/stb_vorbis.c:175:26: fatal error: alloca.h: No such file or directory
       #include <alloca.h>
                          ^
compilation terminated.
```

**Comment by raysan5** [comment]
File corrected on main raylib branch:

https://github.com/raysan5/raylib/blob/master/src/external/stb_vorbis.c#L170

**Comment by 5k3105** [comment]
Hi,

I'm using MINGW64 though

**Comment by raysan5** [comment]
Maybe just check for __MINGW64__ defined? Don't know, just an idea...

**Comment by gen2brain** [comment]
It looks like __MINGW32__ is enough https://sourceforge.net/p/mingw-w64/discussion/723798/thread/ea355c1f/#d4db . There is also a method on that link to differentiate between mingw.org and mingw-w64.org if ever needed.

**Comment by 5k3105** [comment]
Thanks!
