### ISSUE TITLE
Port inclusion

### ISSUE THREAD

**Issue by nehpe** [gen2brain/raylib-go#80]
Hi,

I've written a port of one of the original Raylib C examples (https://github.com/raysan5/raylib/blob/master/games/arkanoid.c) over to raylib-go: https://github.com/nehpe/arkanoid-raylibgo

I wasn't sure if you wanted to include it in the raylib-go repo, but I'd be happy to make a pull request if you'd like it.

--nehpe

**Comment by gen2brain** [comment]
Hi, sure, all ported examples are welcomed, just send PR. Also, all fixes to current examples are welcomed, they are not up to date with raylib. Thanks.
