### ISSUE TITLE
Android example compilation

### ISSUE THREAD

**Issue by fordarian** [gen2brain/raylib-go#82]
Hi!

I got a trouble compiling android example (raylib-go/examples/others/android/example/). The apk part is ok, but i cant manage shared library compilation.
According to README:

    export ANDROID_NDK_HOME=...
    export PATH=${ANDROID_NDK_HOME}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:${PATH}
    export ANDROID_SYSROOT=${ANDROID_NDK_HOME}/platforms/android-16/arch-arm
    CC=arm-linux-androideabi-gcc \
    CGO_CFLAGS="-I${ANDROID_SYSROOT}/usr/include --sysroot=${ANDROID_SYSROOT}" \
    CGO_LDFLAGS="-L${ANDROID_SYSROOT}/usr/lib --sysroot=${ANDROID_SYSROOT}" \
    CGO_ENABLED=1 GOOS=android GOARCH=arm \
    go build -buildmode=c-shared -ldflags="-s -w -extldflags=-Wl,-soname,libexample.so" \
    -o=android/libs/armeabi-v7a/libexample.so

The trick is - provided build command is not working with the last NDK (r20), due to migration from gcc to clang. I tried r17c version which dated as an example and includes gcc toolchain, but with no success - looks like headers was unified and moved to ndkroot/sysroot, and they wont work either.

Does anyone got the actual build commands? Thanks.

**Comment by gen2brain** [comment]
Try to add `-D__ANDROID_API__=16` to CFLAGS, that is probably needed so unified headers don't throw errors.

**Comment by fordarian** [comment]
Thanks a lot, it helps!
My final routine for last (r20) ndk is looks like this:

    export ANDROID_NDK_HOME=/c/Users/frd/AppData/Local/Android/Sdk/ndk-bundle
    export PATH=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/windows-x86_64/bin:${PATH}
    export ANDROID_SYSROOT=${ANDROID_NDK_HOME}/platforms/android-16/arch-arm
    CC=armv7a-linux-androideabi16-clang \
    CGO_CFLAGS="-Wno-error=attributes -D__ANDROID_API__=16 -I${ANDROID_NDK_HOME}/sysroot/usr/include -I${ANDROID_NDK_HOME}/sysroot/usr/include/arm-linux-androideabi" \
    CGO_LDFLAGS="-L${ANDROID_SYSROOT}/usr/lib -L${ANDROID_NDK_HOME}/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/" \
    CGO_ENABLED=1 GOOS=android GOARCH=arm \
    go build -tags static -buildmode=c-shared -ldflags="-s -w -extldflags=-Wl,-soname,libexample.so" -o=android/libs/armeabi-v7a/libexample.so

The only issue i faced was this error:

    # github.com/gen2brain/raylib-go/raylib
    ..\..\..\gen2brain\raylib-go\raylib\platform_android.go:31:8: could not determine kind of name for C.free

Which is gone after adding `#include <stdlib.h>` to the file.
The example works as intended on real device, unlike my own app :)
