### ISSUE TITLE
Updating c sources

### ISSUE THREAD

**Issue by saucesaft** [gen2brain/raylib-go#84]
Hi,
Thanks for the awesome job of porting this library to go, some days ago I made an issue in the main raylib repo, saying if they could implement a function that was no exposed to raylib. At the end that function did came out in a commit, so now that we have different c sources, can we update the one in here, to avoid different programmimg languages having and not having a function for the same library? 

So can we update the c sources? How can I make this possible? 

Thanks!

**Comment by nicholassimon** [comment]
Would love this to happen as well, there are many new functions not available as it is for an older version of Raylib. I would do it though don't have the skill to be able to, it would be great if whomever could update the source to the latest version of Raylib and RayGui

**Comment by gen2brain** [comment]
C sources are updated. New functions will be added later.
