### ISSUE TITLE
Font special characters

### ISSUE THREAD

**Issue by Razikus** [gen2brain/raylib-go#87]
Im using Roboto-Medium.ttf with latin extended fonts, and i can't make it, that it will support characters like "ąćęł" etc, that font supports"

I tried:

standardFont = rl.LoadFontEx("/xx/Roboto-Medium.ttf", 32, 0, nil)

But this not works

Any hints here?

**Comment by SolarLune** [comment]
This is late, but you can do this by specifying nil for the `fontChars` argument and the number of characters to load for the last argument. This would look like:

`standardFont = rl.LoadFontEx("/xx/Roboto-Medium.ttf", 32, nil, 256)`

**Comment by Razikus** [comment]
Good to know for the future
I had to recode everything to C in 2019

**Comment by SolarLune** [comment]
Ah, OK. You could close this, then~

**Comment by Razikus** [comment]
I will test it first and back in some days
