### ISSUE TITLE
Music streams too short - probably a Raylib issue

### ISSUE THREAD

**Issue by rasteric** [gen2brain/raylib-go#90]
Hi, I'm reporting this here because I cannot test with Raylib itself. On my Linux, loading a music stream and playing it by `rl.UpdateMusicStream(music)` in a loop plays only about 62% of the stream and then stops. The length is reported incorrectly, for example Raylib outputs `INFO: [resources/music/mini1111.xm] XM track length:   62.042751 sec` for the mini1111.xm tune in Raylib's github repository at https://github.com/raysan5/raylib/blob/master/examples/audio/resources/mini1111.xm

My Linux player reports 1min 02 sec for the file. The same for any file format I've tried. 

Is there a fix for this? A newer version of Raylib?

**Comment by raysan5** [comment]
@rasteric this problem should be solved for ogg and mp3 on latest master branch, xm and mod still failing... there is an open issue https://github.com/raysan5/raylib/issues/989

**Comment by rasteric** [comment]
Thanks, I thought it's a raylib problem. Stupid question, if I may: Once this is fixed in Raylib, if I tell go mod to upgrade raylib-go, will this fix the issue in Go or will I need to do something else?

**Comment by gen2brain** [comment]
It doesn't work like that, C sources are included in Go repo, it needs to be updated first, manually.

**Comment by gen2brain** [comment]
C sources are updated.
