### ISSUE TITLE
Update README to specify which version of raylib this binds to

### ISSUE THREAD

**Issue by wlycdgr** [gen2brain/raylib-go#91]
Thank you very much for doing this project. Could you please update the readme to say which version of raylib these bindings map to? (Is it 2.5, now?)

**Comment by gen2brain** [comment]
Hi, I would like to add new functions from 2.5/2.6-dev before I add the tag here. This now is version 2.6-dev, raylib-go from the beginning was following dev/master branch, not official releases.

**Comment by wlycdgr** [comment]
Thank you!

**Comment by gen2brain** [comment]
Tags added, for an old and new release.
