### ISSUE TITLE
Issues installing on Mac OSx Catalina 10.15.1

### ISSUE THREAD

**Issue by flagadajones** [gen2brain/raylib-go#92]
When running go get -v -u github.com/gen2brain/raylib-go/raylib

I get the below stream of errors. 

github.com/gen2brain/raylib-go (download)
github.com/gen2brain/raylib-go/raylib
github.com/gen2brain/raylib-go/raylib
core.c:2645:20: error: use of undeclared identifier 'GLFW_SCALE_TO_MONITOR'

**Comment by antonskwr** [comment]
Same for me on macOS Mojave, seems like it’s really not definied in GLFW at the moment. I will try to replace whole GLFW dependency with one from the upstream repo, procedure went well on ubuntu 16.04, I will test on mac a little later.

**Comment by gen2brain** [comment]
This should be fixed now, please check.

**Comment by ryanhartje** [comment]
@flagadajones any update here? Works for me after the PR above.
