### ISSUE TITLE
Fedora Installation Issue

### ISSUE THREAD

**Issue by byronic** [gen2brain/raylib-go#99]
I created PR #98 in regards to this issue.

When I did a fresh install of Fedora 31, go, and this raylib repository I ran into an issue with respect to the X11/Wayland divide. I still don't know exactly what it was (I had tried `go get` with and without the wayland tag), and had done the Wayland installation as specified in the README, but kept getting missing header complaints. 

In the spirit of solving this problem in perhaps the worst possible way, I tried following the X11 requirements as well. After following the instructions for both X11 and Wayland under the Fedora header, I was able to successfully build my raylib-go dependent apps.

I wrote what I hope is a clear instruction about that in the README and opened the aforementioned PR #98 to hopefully help the next person running into this frustration.

That said, if I missed contribution guidelines or otherwise mis-stepped please feel free to review and I will withdraw and re-submit with revisions. Thanks!

**Comment by antonskwr** [comment]
I think it might be related to #93 and my concern there, updating the GLFW from upstream repo wiped out several wayland headers, you could try to bring them back and see how the installation proceeds

**Comment by byronic** [comment]
@antonskwr I agree with your findings but can't verify them without a fresh Fedora box. I'll put it on my to-do list to see if we can deprecate my issue XD

Many thanks!

**Comment by gen2brain** [comment]
There is a script here https://github.com/gen2brain/raylib-go/blob/master/raylib/external/scripts/glfw-generate-wayland.sh to regenerate all needed files for GLFW/Wayland, that was supposed to be done after the update.
 I will add those files when I update C version here, I have no time for adding new functions but core files can be updated.

**Comment by gen2brain** [comment]
This should be fixed now. Wayland files added.
